### ISSUE TITLE
sbt skips tests if scala-js is used

### ISSUE THREAD

**Issue by fommil** [scala-js/scala-js#1446]
I created a little project that I plan to turn into a simple one page HTML page

  https://github.com/fommil/kerbal-calculator

but if I uncomment the lines in `build.sbt` to enable scalajs, then `sbt test` no longer runs my tests.

**Comment by lihaoyi** [comment]
Scalatest doesn't work in Scala.js. You'll have to use one of 

- https://github.com/lihaoyi/utest
- https://github.com/monifu/minitest
- https://github.com/cgta/otest

Or something else that cross-compiles =)

**Comment by fommil** [comment]
but I want to run the tests for the compiled scala code, not the compiled javascript. Isn't that allowed?

**Comment by fommil** [comment]
I mean, the javascript output is just an experiment for me, I want to keep writing my code with scalatest. If I decide that scalajs is a target I care about here (I might do) then I suppose I should port all my tests.

**Comment by lihaoyi** [comment]
The problem is that turning on Scala.js for the main project means you will both compile it to Javascript, and run tests for it in Javascript. If you want to run tests in Scala but also compile it to Javascript, you can create a subproject with Scala.js plugin enabled, copy over all your settings to it, make it share the source code, and use that to generate Javascript output. This is documented here:

http://www.scala-js.org/doc/sbt/cross-building.html

Generally you can't use the same SBT project for both JVM and Javascript, which is unfortunate, but that's the way things are ^_^
