### ISSUE TITLE
Def macros on facade traits & SJS 1.0

### ISSUE THREAD

**Issue by jokade** [scala-js/scala-js#1465]
Sorry if this is a duplicate, but I didn't find an issue on this topic...

I'm using def macros to enhance bindings to a native JS library, e.g.
```scala
trait Foo extends js.Object {
  def bar() : Unit = macro ...
}
```
Since SJS 0.6 the compiler warns me that from 1.0 on only members calling `js.native` will be allowed. Will there be an exception for macros?

I know that I could use implicits to create a `RichFoo` from my `Foo`, but I don't know how to use this pattern without actually having a `RichFoo` instantiated at runtime (which would be quite unnecessary, since my `bar()` can be easily replaced with a simple call to the native JS API of the library).

**Comment by sjrd** [comment]
There won't be exceptions for macros, unless people really really want that.
The way to go is to use an implicit extension method, as you suggest with `RichFoo`. Since it's a macro, you can easily unwrap the implicit conversion on your `prefix` at compile time (in your macro) so that the implicit class is not instantiated.

Note that, unless you really want the power of macros as such, you don't need macros to extend the features of your raw JS types. Just use a good old `implicit class extends AnyVal`:
```scala
implicit class RichFoo(val self: Foo) extends AnyVal {
  def bar(): Unit = ...
}
```
Thanks to `AnyVal`, there won't be any instance creation of `RichFoo`. And the optimizer will do the rest of the job (inlining `bar` if it's small enough).

**Comment by jokade** [comment]
Ok. Didn't know about the trick with `AnyVal` ...
However, since I need to do some compile time reflection (extracting parameter names for runtime DI), I will probably go with your first suggestion. Thanks!
