### ISSUE TITLE
Why not package in jar?

### ISSUE THREAD

**Issue by rparree** [scala-js/scala-js#1472]
Hi,

I am surely missing something. But what is the reason the javascript files don't make it into the (or "a") jar file? 

I am migrating some coffee code to scalajs and am first building a reference project (which i will also publish in a blog article).

I would like my server project just to depend on the "client" (js) project using regular jar files. I can then serve the javascript from using the  resources (like with webjars).

At this moment i am forcing the javascript to go into the jar, but i my feeling says that because this is not the default behaviour i must be missing something.

The forcing is now done like:

```scala
lazy val client = (project in file("client")).
  settings(scalaJSSettings: _*).
  settings(commonSettings: _*).
  settings(
    libraryDependencies ++= Seq(`scalajs-dom`.value, `scalajs-jquery`.value)
  ).
  settings(
    skip in ScalaJSKeys.packageJSDependencies := false,
    crossTarget in (packageLauncher) := (classDirectory in Compile).value / "META-INF", 
    crossTarget in (fullOptJS) := (classDirectory in Compile).value / "META-INF", 
    crossTarget in (fastOptJS) := (classDirectory in Compile).value / "META-INF" 
    ScalaJSKeys.persistLauncher in Compile := true,
  )
```

When i then do `'fastOptJS;package` i get the package i need.

So my questions (or rather suggested answers)
- should i not do this, because there is a standard way of doing this?
- should i not do this because it will create problems (and this is possible the reason it is not default behaviour)
- I can safely do this

tx.,

**Comment by sjrd** [comment]
The main reason is that the resulting .js file is not composable. It contains the whole program, and cannot be combined later with other Scala.js libraries. We want to keep .jars composable by default, which is why they contain the `.sjsir` files instead.

If you want to create a .jar that contains the .js file, for consumption as a Webjar, you probably do *not* want it to contain .sjsir files, and you do not want it to maintain dependencies to the jars of the Scala.js libraries you depend on. The standard mechanism of `package` in sbt does the wrong thing for your use case.

The easiest and maybe most sensible thing would probably be for you to create a separate sbt project to assemble a Webjar-like jar for your client. In that project, you would import the `.js` files produced by `client/{fast,full}OptJS` (the way you do with your `crossTarget` settings), but you would not actually `dependsOn(client)`, so that the dependencies on Scala.js libraries are forgotten.

Does that make sense?

**Comment by rparree** [comment]
Yes that makes sense

I have created a third project:

```scala
lazy val webjar = project.aggregate(client).
  settings(
    unmanagedResourceDirectories in Compile += (crossTarget in (client)).value,
    includeFilter in(Compile, unmanagedResources) := "*.js"
  )
```

I can now have the server project depend on this `webjar` project 

I would still have to add some directories and that will be sufficient for this project. 

I am not sure how other people deal with this (i have seen tricks where the `crossTarget` of the clientjs project is set to the classes output of another). Should such a jar possibly not be part of plugin itself you think?

**Comment by sjrd** [comment]
> Should such a jar possibly not be part of plugin itself you think?

Not by default. Many Scala.js projects do not end up as Webjars. But we could have a mechanism in the sbt plugin that would allow this kind of output with a minimum of boilerplate. It would probably still require a dedicated sbt project (simply so that we can reuse all the built-in per-project metadata handling of sbt), but would otherwise be reduced to a single line of code. Maybe something like this:
```scala
lazy val webjar = project.
  scalaJSWebjarFor(client)
```

**Comment by rparree** [comment]
I can image that the situation i have is not uncommon:

- Have some "server" project (spray, lift, play) 
- server project exposing a rest api and some html app
- html app uses some front-end framework (angular, reactjs, ember,...)
- people would love to write that code in scalajs ;)

btw it does not have to be a webjar (but that probably would make sense when using it in spray/play etc)

I can image, like myself, one would want to have one multi-project sbt structure.

I have only developed one very simple plugin  (https://github.com/edc4it/sbt-activemq) ,i would like to contribute and see if we could come to some easy solution (either it being part of the plugin as a task or something else). I do want to respect the original thought behind this plugin. Let me pull it down and experiment a bit in the next couple of days (mostly weekend)

**Comment by sjrd** [comment]
For that use case, typically people don't even go through a Webjar. They just send the output of Scala.js to the public assets of the Webserver. For Play! there is an example project here: https://github.com/vmunier/play-with-scalajs-example

Publishing an actual Webjar is quite uncommon.

**Comment by rparree** [comment]
That makes sense. However now they are not available as "resources" during development of the jvm project. I am now using the following and this makes the compiled javascript files available during development (hence can use/reference them in my IDE/IntelliJ)

```scala
compile in Compile <<= (compile in Compile) dependsOn (fastOptJS in(client, Compile)),
resourceGenerators in Compile += Def.task {
  val files = ((crossTarget in(client, Compile)).value ** "*.js").get
  val mappings: Seq[(File,String)] = files pair rebase((crossTarget in(client, Compile)).value, ((resourceManaged in  Compile).value / "assets/").getAbsolutePath )
  val map: Seq[(File, File)] = mappings.map { case (s, t) => (s, file(t))}
  IO.copy(map).toSeq
}.taskValue
```
