### ISSUE TITLE
SBT crossProject does not respect scalaSource

### ISSUE THREAD

**Issue by mrerrormessage** [scala-js/scala-js#1486]
In the process of upgrading to scala.js 0.6.0, I noticed that there is a slight inconsistency in the way that crossProjects treat the `scalaSource` directory. In my build.sbt, I have
```scala
lazy val cp = crossProject.crossType(CrossType.Full).
  in(file(".")).
  settings(
  //...
  scalaSource in Compile := baseDirectory.value / "src" / "main",
  scalaSource in Test := baseDirectory.value / "src" / "test",
  //...
)
```
What I expect to happen here is that it will look for shared sources in `shared/src/main`, for js sources in `js/src/main`, and jvm sources in `jvm/src/main`. This expectation is encouraged by
[the CrossProject scaladoc](http://www.scala-js.org/api/sbt-scalajs/0.6.0/#org.scalajs.sbtplugin.cross.CrossProject), which shows `src/main` for each subdirectory. Instead, crossBuild looks for my project sources in `shared/src/main/scala`, `js/src/main`, and `jvm/src/main`.

I'm not certain that this is a bug, but the behavior is certainly surprising. I would be happy to contribute time towards fixing this if you can help me understand what the desired resolution is. Perhaps it's a simple documentation change, perhaps it is a more involved fix where `crossProject` looks at any `scalaSource` configuration values passed in and adds them to the unmanagedSourceDirectories of the js and jvm projects, perhaps it's another option.

Thanks so much for the awesome work on 0.6.0! Scala.js is amazing!

**Comment by sjrd** [comment]
Hi,

This is not a bug. It is the expected behavior. You have to remember that `crossProject` is *not* an abstraction. It is a builder. It helps you build two projects which share a lot of settings and (hopefully) sources.

The `scalaSource` settings that you write reference the `baseDirectory` setting, which is `js/` for the JS project and `jvm/` for the JVM project. These new values for these settings affect the "principal" Scala source directory put in `sourceDirectories in Compile` by the default value of that setting. They do not enter in the composition of the additional `shared/` source directory that `crossProject` adds.

In order to achieve what you want, you probably need a custom `CrossType` with an appropriate implementation of `sharedSrcDir`.

**Comment by mrerrormessage** [comment]
That makes sense. Thank you for explaining.
