### ISSUE TITLE
JS dependency in webjars: specify the file to import using a part of the path

### ISSUE THREAD

**Issue by fxmouthuy** [scala-js/scala-js#1496]
The current version allows to do such configuration:
```
 jsDependencies += "org.webjars" % "historyjs" % "1.8.0" / "history.js"
```

However, some webjars have multiple files with the same name. It would be better to allow partial parts:

```
 jsDependencies += "org.webjars" % "historyjs" % "1.8.0" / "uncompressed/history.js"
```

**Comment by gzm0** [comment]
This is unfortunately both absolutely reasonable and a non-trivial change. 

We currently identify raw JS libraries globally by their file name. This was notably done to reasonably support `dependsOn`, without requiring users to having to write a separate "library definition" (or huge strings in multiple places).

`dependsOn` itself was introduced, since webjars do not have any metadata about required libraries, so we asked the user to reproduce these dependencies at the usage site (which is kind of a WTF on its own).

This design choice percolates through the whole class design. N.b. in the `PartialClasspath` (and what we derive thereof), we represent raw JS libraries as `Map[String, VirtualJSFile]`, where the key is the name of the JS file.

This has a tons of issues:

- Multiple same named files in a webjar
- Multiple same named files in different webjars
- JS files that do not have a descriptive name for the library they contain (e.g. Jasmine 2)
- Libraries that are divided into multiple files (does that exist)
- Bad support for compressed / uncompressed aka prod / dev JS files

We might be able to hack-patch support for partial paths, but maybe we should think of a cleaner way to manage these guys we want to get towards.

**Comment by sjrd** [comment]
Hum, I didn't realize our state on this was so bad ^^

We should probably try to sort of support partial paths in the short run, with the understanding that the partial path becomes the identifier, which means all dependencies referring to a webjar must agree on what partial path is used.

**Comment by gzm0** [comment]
For webjars this is fine, since the JS files are always in `META-INF/resources/webjars/<libname>/<libver>/<library-speicifc>`. The question is what do we do with non-webjar JS. Do we really want to force people to abide to this scheme even for simple things?

**Comment by sjrd** [comment]
Even the `ClasspathContentHandler`s and hence the `ClasspathBuilder`s only retain the file name part. So the knowledge of the relative path wrt the classpath entry is lost very early. :-(
