### ISSUE TITLE
Atomic write of -fastop.js

### ISSUE THREAD

**Issue by ramnivas** [scala-js/scala-js#1512]
I am using scala.js with webpack [1] that watches my -fastopt.js file (along with other resources in the asset pipeline). It appears that the -fastopt.js file is written out to the disk in chunks. As a result, webpack often sees a half-written file that leads to incorrectly built bundle. Earlier I used gulp [2] for the same purpose and encountered the same problem.

I can reduce the frequency of this issue by setting my watch delay to a large number (5-10 seconds instead of the default 200ms), but that works only by trial and error, is machine and source code change dependent, and requires waiting more than necessary (when scala.js finishes sooner) to see the results.

Could scala.js write output files "atomically" (i.e. happens in relatively short period), perhaps by writing to a temporary file and then renaming?

[1] http://webpack.github.io
[2] http://gulpjs.com

**Comment by gzm0** [comment]
Hmmm... This seems indeed to be hindering for tools that watch files. @sjrd do you know how other tools handle that? Renaming seems indeed to be an option...

**Comment by sjrd** [comment]
I have no idea how this works in the wild. Maybe there are documented best practices somewhere. 

But I would question the relevance of doing this here. Does sbt do atomic writes of other files, in general? I don't think so. If it doesn't, I don't think we should do it either. It is possible to implement this in user-space for builds that need it (since it is a build-specific issue, caused by the interaction with another build tool) by overriding the `fastOptJS` task.

**Comment by ramnivas** [comment]
@sjrd I see your point. However, I believe in non-ScalaJS usages of SBT, usually the output files are smaller and/or don't take that long to write. Furthermore, in real-world apps using ScalaJS, a use of some watch-based tool is very likely. So it will be nice to have it be resolved for user before he faces this issue.

Alternatively, as you suggested users can override the `fastOptJS` task. I can give it a shot (let me know if you have pointers on how I may achieve it). Then if it indeed becomes a common need, such a solution can be moved to a more central location.

**Comment by yelbota** [comment]
I have same problem with gulp.

**Comment by caseylucas** [comment]
@ramnivas Have you tried the watchDelay webpack option? Based on docs at http://webpack.github.io/docs/configuration.html it might be what you want or at least help.

**Comment by gzm0** [comment]
@sjrd maybe we should consider this anyways. It seems to be pretty hard to implement this in user space (n.b. because of how we handle caching in the tools).

One way to do this would be to add an `AtomicWritableFileVirtualTextFile` that basically moves on close of the writer (just like `WritableFileVirtualTextFile`).

**Comment by sjrd** [comment]
I guess we'll have to do that, yes.

**Comment by gzm0** [comment]
Hmmm... this is actually not reliably doable in Java 6. The `renameTo` method does not give any guarantee to work.

I guess we'll have to implement it with `renameTo` and hope it works and fix this, once we switch to JDK 7 only.

**Comment by antonkulaga** [comment]
>I guess we'll have to implement it with renameTo and hope it works and fix this, once we switch to JDK 7 only.

Does anybody need JDK6 at all? I think scala-js users use scalajs mostly for their own projects that do not have JDK6 legacy stuff.
