### ISSUE TITLE
java.net.URI does not support Unicode

### ISSUE THREAD

**Issue by betehess** [scala-js/scala-js#1520]
`new java.net.URI("http://cs.dbpedia.org/resource/Víno")` fails with `Uncaught java.net.URISyntaxException: Malformed URI in http://cs.dbpedia.org/resource/Víno at -1`. It works fine on the JVM.

**Comment by sjrd** [comment]
@gzm0 Was this a limitation by design of the first implementation? I don't remember whether we discussed this at some point or not.

**Comment by gzm0** [comment]
Yes, I think this is by design, since we don't have the tooling to determine the characters that are allowed. See #964

**Comment by gzm0** [comment]
Hmmm... Unfortunately I have not written anything detailed. Basically, escaping of the *other* category is not done. See the section "Escaped octets, quotation, encoding, and decoding" in the [URI Javadoc][1].

[1]: http://docs.oracle.com/javase/7/docs/api/java/net/URI.html

**Comment by gzm0** [comment]
So it boils down to the following choices:

- RFC 2396 only support (US ASCII only, deviates from java)
- Loosen up the *other* category and allow more things than the JVM does
- Implement `isSpace` and find a way to use it (together with `isControl`) in the regex (this is the fully java compliant solution)

WDYT?

**Comment by gzm0** [comment]
If we go down unicode land with `URI`, we also have to think of supplemental characters, which we probably don't have support for in the regexes...

**Comment by sjrd** [comment]
I believe we should strive for maximum compliance with the JVM. We should probably use sub-regexes for spaces and control chars. Control chars [are easy](http://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isISOControl%28int%29). [isSpaceChar](http://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isSpaceChar%28char%29) is not much harder: there are only 19 chars total in [SPACE_SEPARATOR](http://www.fileformat.info/info/unicode/category/Zs/list.htm), [LINE_SEPARATOR](http://www.fileformat.info/info/unicode/category/Zl/list.htm) and [PARAGRAPH_SEPARATOR](http://www.fileformat.info/info/unicode/category/Zp/list.htm), apparently, none of them being a supplementary character.

**Comment by sjrd** [comment]
So, I believe a good regex for the *other* category of Java's URI spec is the following:
```
[^ // anything but:
  \u0000-\u00a0  // ASCII (contains some control chars and SPACE) + control chars + no-break-space
  \u1680\u2000-\u20a0\u202f\u205f\u3000 // other SPACE_SEPARATOR
  \u2028 // LINE_SEPARATOR
  \u2029 // PARAGRAPH_SEPARATOR
]
```

**Comment by sjrd** [comment]
As for supplementary characters, the only "trick" is that they have to be encoded using UTF-8 in `.toASCIIString`. For this, we have a perfectly capable UTF-8 encoder.

Otherwise, they are Other characters anyway, and high surrogates and low surrogates are Other as well, so nothing special to do about them.

**Comment by gzm0** [comment]
Sounds reasonable. I'll have a look into that, hopefully this week.

**Comment by gzm0** [comment]
It turns out, that the hardest parts are actually the [regexes][1] that decide what to encode in the mutli-argument ctors. It seems that the character class `[a-z^b-e]` does not work as expected in JavaScript (at least not in V8, which makes it a show stopper).

So I'll have to manually disentangle stuff like:

```
[\u0000-\u00a0\u1680\u2000-\u200a\u202f\u205f\u3000\u2028\u2029^a-z0-9-_.!~*'(),;:$&+=%]
```

unless someone has a better idea...

[1]: https://github.com/scala-js/scala-js/blob/986ea428f7ca3b1a91db731d9a7a77ecb8c7abaf/javalib/src/main/scala/java/net/URI.scala#L616

**Comment by sjrd** [comment]
Yee I guess you need to use positive ranges only, which means going from `\u0000`, stop at `+` or something, then continue until the next one, etc. It's not too bad, if a bit cumbersome.
