### ISSUE TITLE
`Scala.js cannot be run in a forked JVM`

### ISSUE THREAD

**Issue by peterbecich** [scala-js/scala-js#1590]
I'm trying to add Scala.js 0.6.2 to a Play project, but cannot load the project due to this error.  I believe that the `ENSIME` plugin creates its own JVM process, but that is shut down.  There are no other instances of SBT running, and there is only one Java process running.

The Play project originally used Play 2.3.2 and SBT 13.5, and has since been updated to Play 2.3.8 and SBT 13.8.

The only other distinguishing feature of my Play project, that I can think of, is that the instance of `Project` exists in `Build.scala` and not `build.sbt`.  This was necessary for compatibility with `ENSIME`:

```
  lazy val mainProject = Project(
    id = "parkinsons-server",
    base = file("."),
    settings = Defaults.coreDefaultSettings ++ Seq(
      version       := "1.0",
      scalaVersion  := "2.11.6",
      libraryDependencies ++= dependencies,
      slick <<= slickCodeGenTask
    )
  ).enablePlugins(PlayScala)
    .enablePlugins(SbtWeb)
    .enablePlugins(ScalaJSPlugin)
```

The imports are included in `Build.scala`:
```
import org.scalajs.sbtplugin.ScalaJSPlugin
import org.scalajs.sbtplugin.ScalaJSPlugin.autoImport._
```

Here is the error given when loading the project:
```
[debug] [Loading] Done in /home/peterbecich/parkinsons/parkinsons-play-framework-server, returning: (parkinsons-server)
java.lang.RuntimeException: Scala.js cannot be run in a forked JVM
	at scala.sys.package$.error(package.scala:27)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$26.apply(ScalaJSPluginInternal.scala:308)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$26.apply(ScalaJSPluginInternal.scala:306)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] Scala.js cannot be run in a forked JVM
```
Thanks for your help!

**Comment by sjrd** [comment]
That's because you mix both JVM stuff (Play) and JS stuff in the same sbt project. You cannot do that. You need separate sbt projects (in the same build). See https://github.com/vmunier/play-with-scalajs-example for how to use Scala.js with Play!.

**Comment by eswenson1** [comment]
We have an SBT plugin that builds perfectly fine with both Play and ScalaJS support.  It is the use of this plugin that is causing us to get this error: Scala.js cannot be run in a forked JVM. This used to work.  It seems "wrong" to force us to create two plugins, so that projects that use both Play and ScalaJS can be built. Can someone explain WHY you can't mix these in an SBT project and any workarounds?

**Comment by ryan-williams** [comment]
I'm seeing this error just trying to run SBT with `fork := true` to avoid the SBT repl OOMing every 30mins or so, cf. https://github.com/sbt/sbt/issues/3983

Would love some more discussion/clarity around why scala-js can't allow `fork := true`

**Comment by sjrd** [comment]
Scala.js necessarily *always* "forks" to actually run/test stuff, since it spawns a process for the JS interpreter. `fork := true` is therefore useless in Scala.js. For technical reasons that are really difficult to explain without deep sbt knowledge, we have to keep `fork := false` for the rest of the sbt machinery not to break down, but it will in fact actually fork anyway.

You should only apply `fork := true` in your JVM projects (e.g., in `jvmSettings` for a cross-project).

**Comment by ryan-williams** [comment]
Thanks for the context! It seems like I should be able to say e.g.

```scala
fork := (if (isScalaJSProject.value) false else fork.value)
```

in a plugin's `projectSettings`, and then set `fork := true` in my global settings (or e.g. `fork in ThisBuild := true` at the top of my `build.sbt`) and have JVM vs. JS projects get the right values, but I still get the error. 

I'm trying to look now to see what scope scala-js is checking the existing value of `fork` in such that my snippet above doesn't overwrite it to `false` in time.

In the meantime, I think we should call this a "bug" and re-open the issue… global `fork := true` seems necessary due to https://github.com/sbt/sbt/issues/3983, so having scala-js break that when it is actually requiring and implementing `fork := true` under the hood is a pretty weird state of affairs, we should at least solicit better ways to do it.

**Comment by olafurpg** [comment]
I encountered this error today and found it difficult to track down in what scope `fork := true` was defined. It would be helpful if the error message provided more information, especially because it's not even possible to load the sbt shell for `inspect`. In my case, `fork.in(Test) := true` was defined by an external sbt plugin with `trigger = allRequirements` so it was not trivial to work around it (see [workaround](https://github.com/JetBrains/sbt-idea-plugin/commit/d56a8c0641329eddeb340baa0a15a3786d0c73f8#commitcomment-29963247) if anyone is interested).

**Comment by sjrd** [comment]
It's already much better in 1.x. In particular, it only fails when one tries to `test`, not when the build is loaded. So `inspect` can be used. In addition it tells you in what scope it looked, so you know exactly what to ask to `inspect`, which will in turn tell you in what scope it was defined and where.

I don't think there's anything more we can or should do.

**Comment by olafurpg** [comment]
If the error is improved in 1.x then that's good enough for me 👍

**Comment by SethTisue** [comment]
fwiw, I ran into this error when upgrading nyaya from sbt 0.13 to sbt 1 over at https://github.com/japgolly/nyaya/pull/40 — by trial and error, I discovered that it went away if I removed sbt-idea-plugin from project/plugins.sbt

**Comment by Veske** [comment]
I happened to have `fork in Test := true` in `~/.sbt/1.0/fork.sbt` and had completely forgotten about it. If there is anyone like me then know that you will have to remove that to use a project with Scalajs plugin :)
