### ISSUE TITLE
docs: document general style for contributing

### ISSUE THREAD

**Issue by yawnt** [scala-js/scala-js#1644]
Since scala-js has some strict requirements when it comes to style, commit messages, etc, I think it would be beneficial to write down a document people can look at to make sure their contributions comply to the standard

**Comment by sjrd** [comment]
Yea, we really should do that. About commit messages, we already have some good stuff at https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md
But for coding style, people tend to learn from their first few PRs so far.

**Comment by yawnt** [comment]
true that, but I think a lot of time could be saved with a doc, especially when some newcomers' PR are as heavy as #1636, for instance

**Comment by mfirry** [comment]
:+1:

**Comment by andreaTP** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by andreaferretti** [comment]
:+1:

**Comment by gianluca-sabena** [comment]
:+1:

**Comment by gzm0** [comment]
I wouldn't spend too much time on it. People don't bother reading that stuff. For example: In `CONTRIBUTING.md` we are *very* explicit about how commit messages are to be formulated. Nevertheless, we have to correct people on every PR.
I think it is worth much more to invest some time in configuring a stylechecker properly.

**Comment by japgolly** [comment]
> But for coding style, people tend to learn from their first few PRs so far.

"prefer"...
No, I did not prefer having to resubmit my patch to scala-js-dom like 5 times to have it nitpicked each time about whitespace and style, even tense in commit message.

It would've saved me time and energy if I were just pointed to a doc so I could adhere to all the rules the first time.

**Comment by sjrd** [comment]
@japgolly I didn't say "prefer", I said "tend to", which is factual (at least in French, maybe that subtlety is lost with my translation).

I actually agree we should have a style guide, even if people don't follow it. At least on the first review we could just say: here is the style guide, go fix your code ^^

**Comment by japgolly** [comment]
wtf??! Am I losing my mind? I even copied & pasted, how the hell did I misread that 3 times??... Mea culpa. :hand: 

Ok, my apparent mental illness problem aside, being pointed to an existing doc once would be much preferred.

Also a trick a learned at my last job, people are much more receptive to this kind of thing when it comes from a machine instead of a human (resentment doesn't stick to machines as much). If the style check or even correction were automated, it would be win/win for everyone's time.

**Comment by gzm0** [comment]
There is a PR outstanding for scalastyle... #1566

**Comment by andreaTP** [comment]
A stylechecker well configured will do most of the job.
It will be an help for newcomers to the project.

**Comment by InTheNow** [comment]
Whilst I would also like something like scalastyle, looking _quickly_ at its built in rules, they do not look that they cover much of the issues raised in CR's. So new rules would be required.

As a side note, we also have the same, unresolved issue on banana-rdf -  https://github.com/w3c/banana-rdf/issues/148 . I mention this as I would be more than happy to share anything from scalajs on this topic :)

As a suggestion: If many new rules have to be added to any new tool, they have to be documented first, right? So it make sense to start/do the the docs first?

Why not just add a wiki page and add things as they pop up? I have some "rules" from https://github.com/scala-js/scala-js/pull/1633, @andreaTP has a few more from https://github.com/scala-js/scala-js/pull/1636 that we can start with. 

Perhaps we can use [the scalastyle guide](http://docs.scala-lang.org/style) as a template, or as a default unless specified otherwise?

**Comment by InTheNow** [comment]
This is also worth a read https://github.com/w3c/banana-rdf/pull/270#issuecomment-105644398
