### ISSUE TITLE
java.lang.Class.cast() is missing

### ISSUE THREAD

**Issue by yawnt** [scala-js/scala-js#1653]
`Class.cast(obj)` is not available in Scala-js, so the current implementation of `Future.mapTo` coming from the scala stdlib causes linking errors.
I suppose we could drop `.cast()` and just rely on `asInstanceOf[]`, sacrificing some safety

**Comment by sjrd** [comment]
Or, easier, implement `Class.cast()` by trivially returning `obj.asInstanceOf[T]`.

**Comment by sjrd** [comment]
Ah, ah, well, this turns out to be *way* more complicated than I expected ^^ By definition, `classOf[C].cast(obj)` must be the dynamic equivalent of `obj.asInstanceOf[C]`, just like `classOf[C].isInstanceOf(obj)` must be the dynamic equivalent of `obj.isInstanceOf[C]`. We already had trouble implementing `isInstance` correctly for raw JS types.

In Unchecked behavior, `obj.asInstanceOf[C]` can indeed be erased, so the implementation `obj.asInstanceOf[T]` is correct.

But in Compliant/Fatal behavior, it should throw, so it must call `isInstance(obj)`, and if it's false, throw an exception.

First problem: which exception? A `ClassCastException` or an `UndefinedBehaviorError`? That must depend on the semantics configuration. Neither is strictly stronger than the other, so neither can be used safely in all cases. But in the Scala code, we don't know what semantics configuration we have (and testing it experimentally by forcing a known bad behavior and catching the thrown exception would itself be undefined behavior in Unchecked mode).

Solution: store in `runtime.environmentInfo` a flag telling whether `asInstanceOfs` is compliant or not.

Second problem: `asInstanceOf[C]` must always succeed for all raw JS types `C`. But `isInstance(obj)` will either throw a `TypeError` or return `false` when we would like `true`.

Solution: we need `java.lang.Class` to be aware whether it represents a raw JS type or not, which we must store in its `data`.

Fortunately, we can do all of this in a backward binary compatible way :-)
