### ISSUE TITLE
PhantomJS: access to webpage

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1687]
Is it possible to get access to the PhantomJS webpage? I see it in the launcher js.

 The following don't work:
```scala
scalajs.js.eval("require('webpage')")
js.Dynamic.global.page
js.Dynamic.global.phantom.page
```

**Comment by gzm0** [comment]
In PhantomJS, you can run code in different contexts. In the base context, you have access to all of [PhanomJS' modules][1]. However, you are not in a webpage, so there is no DOM:

```
$ phantomjs 
phantomjs> window
SECURITY_ERR: DOM Exception 18
```

On the other hand, you can run inside a webpage context, you have the DOM at your disposal.

The `PhantomJSEnv` that ships with Scala.js executes code inside the webpage module, since we believe that this is what most people want to quickly start.

If you need to run in the PhantomJS base context, I guess it is best to define a new JSEnv. This is pretty easy if you just want to run code (just extend `ExternalJSEnv` and get examples from `NodeJSEnv`).

However, if you need your tests to run in PhantomJS, you need to implement a communication channel between the JVM and the PhantomJS VM. In the webpage module we use websockets to do so. Looking at the [PhantomJS API][1], they still seem the only viable option to do so (in `NodeJSEnv` we just use a TCP socket). Therefore, you would need to spin up a dummy webpage just to be able to open a websocket.

I hope this sheds a bit of light on the whole thing. Let me know what you actually want this for and we'll figure something out.

[1]: http://phantomjs.org/api/

**Comment by japgolly** [comment]
>  Let me know what you actually want this for

The usual: working around PhantomJS bugs. :weary: In my tests I'm trying to simulate a key being pressed but due to some bug in PhantomJS it seems impossible to create an event which returns anything apart from 0 as the `keyCode`. I've been trying many tricks, hacks, polyfills I discover online but to no avail. Looking around PhantomJS itself it seems that if I had access to `page` I could do `page.sendEvent("keydown", page.event.key.F2)`.

Thanks for the informative reply. It sounds like more work than I think is worth it for a workaround. Instead I think I'll find a workaround that avoids firing the event.

I'm happy to close this if that's ok with you?

**Comment by gzm0** [comment]
> I'm happy to close this if that's ok with you?

Yes. Let's close it for now. If you don't find a workaround, get me on gitter and we'll figure something out. Maybe it's enough to slightly generalize our instrumentation code so you can trigger your events from inside the webpage module.
