### ISSUE TITLE
Charset decoding fails with read-only byte buffers

### ISSUE THREAD

**Issue by mpilquist** [scala-js/scala-js#1734]
The scala.js version of `Charset#decode` fails to decode with a `MalformedInputException` when using charsets other than UTF-8 and when decoding a read-only byte buffer.

```scala
import java.nio.ByteBuffer
import java.nio.charset.Charset

def decode(charset: Charset, data: Array[Byte]) = {
  val decoder = charset.newDecoder
  //decoder.decode(ByteBuffer.wrap(data)).toString <-- works
  decoder.decode(ByteBuffer.wrap(data).asReadOnlyBuffer).toString // <-- doesn't work
}

val arr = Array[Byte](0x74, 0x65, 0x73, 0x74)
assert(decode(Charset.forName("UTF-8"), arr) == "test") // <-- passes for both RO and RW
assert(decode(Charset.forName("US-ASCII"), arr) == "test") // <-- passes for RW, throws for RW
assert(decode(Charset.forName("ISO-8859-1"), arr) == "test")  // <-- passes for RW, throws for RW
```

**Comment by sjrd** [comment]
Note-to-self:
The cause of this bug is that the else branch at
https://github.com/scala-js/scala-js/blob/276f4f2df9b3b1eb683a5c401c98c528b68cf6e2/library/src/main/scala/scala/scalajs/niocharset/ISO_8859_1_And_US_ASCII_Common.scala#L69-L77
doesn't update the `position` of the two buffers, contrary to the then branch.
