### ISSUE TITLE
Support for (limited) standard Java reflection via annotations/linking options

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#1744]
Just a reminder,
as discussed with @sjrd at Scala Days Amsterdam (thanks for that!) a basic reflection though annotations is definitely implementable in standard library, and this will target a lot of common use case of library inter-compatibility issues, so, we are waiting for it from you! ^^

**Comment by yawnt** [comment]
:+1:

**Comment by sjrd** [comment]
IIUC, all Akka really needs is nicely abstracted away in [`DynamicAccess`](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/DynamicAccess.scala). So my proposal would be to give enough tools to be able implement that abstract class, with the exception of `classLoader`.

So basically we need to support these four factories:
```scala
def createInstanceFor[T: ClassTag](clazz: Class[_],
    args: immutable.Seq[(Class[_], AnyRef)]): Try[T]

def getClassFor[T: ClassTag](fqcn: String): Try[Class[_ <: T]]

def createInstanceFor[T: ClassTag](fqcn: String,
    args: immutable.Seq[(Class[_], AnyRef)]): Try[T]

def getObjectFor[T: ClassTag](fqcn: String): Try[T]
```
which basically boils down to three capabilities:
* From of fully qualified class name, get its `Class[_]`
* From a `Class[_]`, instantiate it using a constructor identified by its formal parameter types as a `Seq[Class[_]]`
* From a `Class[_]` of a module class, get its module

All of these things are of course under the condition that the target class/object was explicitly exported for "reflection". I propose the following annotations:
* `@JSReflectClassByName` and `@JSReflectDescendentClassesByName`: allow to get a `Class[_]` from the fully qualified name for the designated classes. Note that this also applies to objects (module classes), abstract classes and traits.
* `@JSReflectCreateInstance` and `@JSReflectCreateInstanceForDescendentClasses`: from a `Class[_]` of a *concrete* class designated by the annotation, be able to create an instance using a *public* constructor identified by parameter types.
* `@JSReflectLoadObject` and `@JSReflectLoadDescendentObjects`: from a `Class[_]` of a module class designated by the annotation, get the module instance.

The exact API for those is less important. The low-level API would basically look like this:
```scala
object Reflect {
  def getClassByName(fqcn: String): Class[_] = ???
  def createInstanceFor[T](clazz: Class[T], params: js.Array[Class[_]],
      args: js.Array[Any]): T = ???
  def getObjectFor[T](clazz: Class[T]): T = ???
}
```
Comments welcome!

**Comment by andreaTP** [comment]
Thanks a lot for the effort,
I think your proposal make sense.

I have questions on ```constructors```, if it will be possible to use even ```protected``` constructors and what happens in case of multiple available constructors with different args for the same class.

**Comment by sjrd** [comment]
Why would you want to call protected constructors? That doesn't sound very sane to me.

> what happens in case of multiple available constructors with different args for the same class.

That's precisely why `createInstanceFor` takes `params: js.Array[Class[_]]`: to know which constructor to call.

**Comment by andreaTP** [comment]
Internal components loaded from configuration that are not exposed to developer API

**Comment by sjrd** [comment]
Do they really do that kind of ugly stuff in Akka!?

**Comment by mseddon** [comment]
As an aside, I wonder if it would be possible to expose `Class.forName("qualified.class.name").newInstance(args...)` for these annotated classes? If so, then it would be possible to share code that reflectively instances classes between js and the jvm.

**Comment by sjrd** [comment]
Nah, Akka actually uses `Class.forName("fqcn", false, classLoader).getDeclaredConstructor(params: _*).newInstance(args: _*)`. We can't really provide any kind of reasonable semantics for a class loader.

**Comment by mseddon** [comment]
I agree, for Akka's use case that's a non option., But if we supported the single argument version of forName, (which I believe would be possible to put into javalib using the Reflect object defined above), it would still work as though there was just a single classloader in scala-js (unless I'm mistaken).

**Comment by yawnt** [comment]
> Do they really do that kind of ugly stuff in Akka!?

[Yes](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala#L478), they [do](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L626)

**Comment by sjrd** [comment]
@yawnt No that's calling [this constructor](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala#L487-L491) which is public.

**Comment by sjrd** [comment]
@mseddon We could possibly do that.

**Comment by sjrd** [comment]
After thinking about the implementation of this stuff, I have second thoughts. There's no real value added by exposing a different API than that of Java reflection. So I'll keep the annotations, but make them expose stuff through the standard Java reflection API:

* `@JSReflectClassByName`: allows the class to be found by `Class.forName(fqcn)`, as well as with `Class.forName(fqcn, init, getClass.getClassLoader)`. The parameter `init` will be ignored and this will behave as if `init` was `false`.<sup>†</sup> This causes the class data to be reachable.
* `@JSReflectConstructors`: will cause `clazz.getDeclaredConstructors()` and derived to list all the constructors of the class.
* One can call `newInstance` on the constructors returned by `getDeclaredConstructors()`. If that method is reachable, then so are all the constructors that are reflectable and whose declaring classes' class data are reachable.
* `@JSReflectModule`: will cause `clazz.getDeclaredFields()` and derived to list a pseudo `MODULE$` field, which is static, and whose `get(null)` methods loads the module and returns it.
* If `get()` is reachable, module accessors that are reflectable will be reachable when the class data are reachable.

`getDeclaredConstructors()` and `getDeclaredFields()` are always callable, but they list only annotated members. On most classes, they will return an empty array. `Class.forName` can only find classes that are reflectable. It will fail with `ClassNotFoundException` for other classes, even if they are on the classpath, and even if their class data is otherwise reachable.

`Class.forName` uses the same fully qualified name as that returned by `getName`, which means it is affected by the link-time semantics `runtimeClassName`.

All in all, Akka's `DynamicAccess` will work unchanged (for property annotated classes).

<sup>†</sup> In Scala code, on the JVM, `init == true` causes a module to be loaded (its constructor runs) when its class is `forName`d. In Scala.js, that won't be the case. There is no other difference.

**Comment by andreaTP** [comment]
your proposal looks completely acceptable from my POV.
I just do not understand what will be the result of ```getClass.getClassLoader```

**Comment by sjrd** [comment]
`getClass.getClassLoader` will return a singleton instance of `ClassLoader` whose `loadClass` method can find classes annotated with `@JSReflectClassByName` (or `@JSReflectDescendentClassesByName`).

**Comment by andreaTP** [comment]
cool! does this will work even with private and inner classes?

**Comment by sjrd** [comment]
Yes. With this specification, there is no reason not to apply it to private, inner, and what not, stuff.

**Comment by gzm0** [comment]
I agree on putting this behind the Java reflection. It might also allow a small part of the Scala reflection to work.

However, I would like to bring the annotation discussion up again: Is an annotation really the right way of making something reflectable? Requiring an annotation on the class that is to be reflected upon goes against most use cases of reflection: Getting something done the initial class was not designed for (I know that Akka is an exception here).

I think we should keep this entirely at the linking stage:

- Introduce a function similar to `runtimeClassNames` for `@JSReflectConstructors` (but just returning a boolean). This can later be extended on a per-method level `reflectable: (LinkedClass, LinkedMember) => Boolean`.

- Give the linker a list of classes/modules we want to be reflectable (or come up with a more sophisticated mechanism that allows to express things like "all subclasses of", but incrementality will be non-trivial there)

IMO we will inevitably have to do the second one at some point in time, but we will then be stuck with several annotations and IR fields we don't need anymore. (Except if you think having both mechanisms is a good idea).

If anything should go in the IR about reflection IMO, then it is a kind of reflection callgraph:

```scala
// Compiler-intrinsic DSL stating all possible targets for the `forName` call, but allowing
// things like all subclasses of A, everything in package x, etc.
val a = Class.forName(...)
```

While this is definitely out of scope for a first version, it will allow for safe use of reflection in libraries where appropriate, while still allowing for full DCE of these libraries in case the relevant methods are not used.

**Comment by sjrd** [comment]
If we want to go there, we need to break backward binary compatibility of the IR, because we'll have to store reflection metadata for *all* classes and all their constructors a priori. Currently there is not enough information in the IR to implement `getDeclaredConstructors()`. So-called trivial constructors don't even appear in the IR (that was probably a mistake, but again, we can't fix that without a backward binary incompatible change).

Also, if we want to support any of the other methods of `Constructor` (besides `newInstance`), or if we want to support `getConstructors` and/or `getConstructor`, we need at least the Modifiers, which are not in the IR either.

Second thought: it *might* be possible to reverse-engineer that a class should have had a trivial constructor: if no constructor in the class calls a super constructor, that means there was a trivial constructor. But if there is no constructor whatsoever, and the superclass has more than one constructor, we still don't know the signature of the trivial constructor.

**Comment by gzm0** [comment]
Hmmm... I see. I did not think that we are missing information. This is of course a bummer...

Maybe we should take the following course:

- 0.6.5 Introduce reflection with annotations as proposed
- 0.6.<last> Always emit reflection information, deprecate usage via reflection
- 1.0 Link time reflection opt-in, no annotations
- 1.x In-source reflection declaration

If we have a 0.7.0 branch, the transition can of course be smoother by enabling both in the 0.7 branch. Further, if we still aim for forward and backwards compatibility in the 1.0 branch, in-source declaration (at least the IR part) needs to go into 1.0.0.

**Comment by sjrd** [comment]
Sorry, there are several things from your comment that I don't understand:

* 0.6. Always emit reflection information -> what for? They wouldn't be used because we could never rely on them
* 0.6  deprecate usage via reflection -> eh? What do you mean?
* 1.0 no annotations -> hum, we need to keep the annotations but deprecate them at that point
* 1.x In-source reflection declaration -> what do you mean?

> by enabling both in the 0.7 branch

both what?

> if we still aim for forward and backwards compatibility in the 1.0 branch

No we don't. There aren't actually any good reason to do so. Even the JVM does not have forward binary compatibility of its class files.

**Comment by sjrd** [comment]
If we want to do link time, let's do link time directly. Let us not create something now that we already know we'll deprecated later.

With the current state of the IR, we can support `forName` and `getDeclaredFields` for `MODULE$` at link time, as well as `Constructor.newInstance`.

We can "almost" support `getDeclaredConstructors`, but it will miss trivial constructors. We can talk ourselves into saying that not emitting trivial constructors was a bug in the compiler <= 0.6.4, and such constructors will be missed by reflection for classes compiled with an earlier version of the compiler.

With that, we can support Akka's use case.

We can support the rest when we break backward binary compatibility, by storing everything we can in the IR.

**Comment by gzm0** [comment]
I updated my old post.

Doing link time right away sounds reasonable if you say that it is feasible. Not being able to reflect on trivial ctors is acceptable and if they can be reconstructed, even better.

**Comment by sjrd** [comment]
There is another missing piece of information which is very annoying: we don't know whether a class is abstract or not.

Calling `newInstance` on a `Constructor` of an abstract class should throw an `InstantiationException`. At first I thought: no big deal, we'll just bluntly ignore and instantiate anyway. But from a linking point of view, this is a problem: we will try to make instantiable a class which contains abstract member, and that will cause linking errors.

We could reverse-engineer an under-approximation of the abstract flag of a class by the presence in its hierarchy of a method which is abstract and never implemented. Some abstract classes might be considered as concrete using this criterium, but all of such classes would link anyway, at least.

**Comment by sjrd** [comment]
Could you elaborate on your compiler intrinsic idea? Give at least one complete example of what you imagine? I fail to see how any kind of reflective operation wouldn't end up reaching the entire world.

**Comment by sjrd** [comment]
> Requiring an annotation on the class that is to be reflected upon goes against most use cases of reflection: Getting something done the initial class was not designed for (I know that Akka is an exception here).

I am not sure this is true, actually. Can you give one such example?
I have the feeling that most valid usages of reflection are actually in cases where it was intentional for something to be reflectable. Often, I will apply a given subset of reflective operations on classes that have at least one particular property which is meaningful for my library. That property should be encoded as a super trait, at least, in most cases.

One known counter-example of this is JUnit: it is the presence of one `@Test` *method* that causes the enclosing class to be lookup up and instantiated via reflection. But my point is they *could* have designed their API so that all test classes have to implement a particular (empty) interface `TestClass`, which identifies classes which are genuine test classes.

**Comment by gzm0** [comment]
> I am not sure this is true, actually. Can you give one such example?

No, not really. All the usages of runtime reflection I have made are for hacks. But I also fail to see an example where using runtime reflection (vs compile time reflection) is a valid use case. IMO Akka is not. An Actor could just be represented by a factory value.

> Could you elaborate on your compiler intrinsic idea

The idea is that when you call a reflection API in a particular point of your code, you should have a very good idea of what set of symbols you intend to reach with this call. Based on this you will do one/both of the following:

- annotate classes
- set linker options

All of these approaches have two fundamental problems:

- the reason why certain classes are reflectable is lost unless tracked via comments
- assuming a system that propagates reflection infos for libraries to builds (annotations or dependency info), this will make the classes reflectable even if the said method is not reachable (you can imagine a library where only a subsystem needs the reflection)

A solution to this problem is to emit call graph information for reflection, just like we do for the normal call graph. Of course this call graph information cannot automatically be created, but we could allow the programmer to put it in the right spot. For example:

```scala
def newMyIface(name: String): MyIface = {
  js.reflection.reflectSubclasses[MyIface] // or something like that
  Class.forName(name).getDeclaredConstructors().head.newInstance().asInstanceOf[MyIface]
}
```
All calls to `js.reflection` would be completely erased at runtime and just tell the compiler what to emit in the IR.

With something like that, the declaration what needs to be reflectable is nicely contained where it is actually going to be used. This will also much better tooling to find out why stuff is reachable (pointing to the upper line in the code, rather than saying: "Well... *you* said it should be... I don't know why...").

I'm assuming the above would also solve Akka's use case (although reachability is probably not a concern there, hardly imaginable that you define an Actor without ever creating an ActorRef).

**Comment by andreaTP** [comment]
```IMO Akka is not. An Actor could just be represented by a factory value.```
Akka uses runtime reflection to enable a better developer API, they set runtime fields as accessible, ad set them i.e.

**Comment by andreaTP** [comment]
moreover the suggested way to instantiate an Actor is through reflection too...

**Comment by sjrd** [comment]
> IMO Akka is not. An Actor could just be represented by a factory value.

Akka does not only use reflection to instantiate Actors. It also uses reflection to configure dispatchers/deployers/other config. This is pretty valid, IMO, although of course in a Scala.js environment, which is whole-program, you might as well "configure" that through code, and then you would have dce for free and no reflection needed.

Even for instantiating Actors, there is a valid reason for doing it the way they do: `Props` are serializable and can be sent to another process. You cannot do that with arbitrary factory functions.

> Akka uses runtime reflection to enable a better developer API, they set runtime fields as accessible, ad set them

That one is a heresy, though. They should have convinced Scala to support `@uncheckedStable` on `def`s instead, and be done with it at the language level.

> Of course this call graph information cannot automatically be created, but we could allow the programmer to put it in the right spot.

This is semantically dangerous. Unless you "annotate" *accurately* all your usages of the reflection API, you can write portions of programs that will *behave differently* depending on whether or not an entirely different piece of code is reachable or not! In other words, if the optimizer gets better, your program can change behavior. Example:
```scala
def newMyIface(name: String): MyIface = {
  Class.forName(name).getDeclaredConstructors().head.newInstance().asInstanceOf[MyIface]
}

def someOtherMethod(): Unit = {
  js.reflection.reflectSubclasses[MyIface] // or something like that
}
```
Depending on whether or not `someOtherMethod()` is reachable, `newMyIface`, which is completely unrelated, will produce different results.

We could of course solve this soundness issue with the holy Undefined Behavior:
* Calling any part of the reflection API is undefined behavior, unless you have *previously* called the appropriate `js.reflection` methods to register *all* the potential results of your reflection API call.

For example, calling `clz.getDeclaredConstructors()` is undefined behavior unless you have called `js.reflection.reflectConstructors[C]` and `clz == classOf[C]`, or called `js.reflection.reflectDescendentConstructors[C]` and `classOf[C].isAssignableFrom(clz)` is true.

But for `Class.forName(fqcn)`, this is more tricky, because you don't have the a priori filter on any kind of predicate. You can only filter after `Class.forName` has returned. So UB is out of the question. The best we can do is under-specify: `Class.forName(fqcn)` will return the class `C` if `js.reflection.reflectClassByName[C]` was called before. Note the absence of *only if* in the previous sentence.

**Comment by andreaTP** [comment]
```you might as well "configure" that through code```
sure but please consider that in future configuration can be loaded from other sources (let say an ajax call)

**Comment by andreaTP** [comment]
@sjrd have you got any idea on the schedule for this enhancement?

**Comment by sjrd** [comment]
[I am working on it.](https://github.com/sjrd/scala-js/tree/reflection-link-time) It's not easy. It requires substantial changes in the linker, especially around the reachability analysis.

**Comment by andreaTP** [comment]
tnx for the update!

**Comment by sjrd** [comment]
Due to the immaturity of the implementation and even what exactly we want, I'll delay this to the next version.

**Comment by mseddon** [comment]
My primary use case is fairly "straightforward"- all I really want to do is allow runtime dependencies that augment a base library.  For example, I have a rasteriser that supports CanvasRenderingContext2D, and an optional WebGLContext back-end.  I usually do this sort of dynamic linking in android/jvm by doing `Class.forName("f.q.p.OpenGLDriver")` and if I get a non-null result, newInstance() it, which then patches over a different implementation transparently for the user.  Proguard handles this by keeping any class named as a string literal argument to `forName` calls, so everything works out.

This isn't a terrible blocker for me since I've built an sbt plugin that generates "linker" code to work around ScalaJS limitations for now, and I'd rather wait for a solution that meets more people's needs. But it does require all libraries to include the plugin to work.  I'm looking forward to being able to remove this hair later :)

**Comment by andreaTP** [comment]
@sjrd any news on this side?
If I can do anything on this side to help you I can try to be at your disposal...

**Comment by sjrd** [comment]
I have set that aside for a time, since it didn't make it to 0.6.5 anyway. It's still scheduled for the next release. But these weeks we're focusing our efforts into fixing memory and runtime performance of the linker.

**Comment by andreaTP** [comment]
thanks a lot for the update!

**Comment by sjrd** [comment]
I have been thinking about this, lately. Currently, I have an implementation that supports `getDeclaredConstructors`, `newInstance`, `getDeclaredFields` and `get` (so everything but `Class.forName`), in my branch [reflection-link-time](https://github.com/scala-js/scala-js/compare/master...sjrd:reflection-link-time). But I don't like it.

The implementation requires a lot of code, and significantly complicates the `Analyzer`, one of the most sensitive pieces of the codebase. I grow more wary of including this in the codebase by the day.

I think, however, that the use cases for this features can be addressed in a non-core extension, based on upcoming *linker plugins*. For example, if a codebase needs to be able to find by name classes extending some `Foo`, a linker plugin could scan the IR files on the classpath, list all classes extending `Foo`, and generate a fairly simple object with a map from strings to the `classOf`s.

Arguably, linker plugins are still far off; at least they're not ready. But a prototype of the features addressed by the above reflection can be done simply with the refactoring of the tools in #2122. It is only a matter of writing another implementation of `GenLinker`, which preprocesses the `irFiles: Seq[VirtualScalaJSIRFile]` in the `link` methods, before handing them further to the original `Linker`, which does the actual job.

Such a prototype would probably not *compose* very well, if several libraries need several transformers. But that will be fixed with proper linker plugins later. The prototypes could also serve as a good measure of things that linker plugins need to support.

I would be happy to assist whoever needs such a prototype. From my point of view, it's much more comfortable to write a per-codebase sort-of-linker plugin than including the implementation of reflection in the core.

**Comment by sjrd** [comment]
I have started working on a prototype "linker plugin" that enables the necessary operations. You can find it here:
https://github.com/sjrd/linking-reflection-for-scalajs
Travis at https://travis-ci.org/sjrd/linking-reflection-for-scalajs/

Currently it supports `createInstanceFor[T]`, the hardest of the three methods to implement.

**Comment by sjrd** [comment]
@andreaTP 

Well there you go, it's basically complete.

Now it supports `getClassFor[T]` and `getObjectFor[T]` too. It's also separated as a runtime library and an sbt plugin, and the things that should be made reflectable are configurable through an sbt setting.

Basically it's as powerful as it needs to be, already. The only thing is it needs a proper test suite, rather than a `main` method dumping stuff.

**Comment by andreaTP** [comment]
@sjrd thanks! I will try an integration and get back to you!

**Comment by sjrd** [comment]
I polished my PoC into an actual sbt plugin and published it. See https://github.com/sjrd/scalajs-reflect

So now you don't even need to "integrate" it. You can just depend on it, and you don't have to maintain it.

**Comment by sjrd** [comment]
In [`AkkaLikeReflection.scala`](https://github.com/sjrd/scalajs-reflect/blob/master/src/test/scala/be/doeraene/sjsreflect/AkkaLikeReflection.scala) you can see how to implement `DynamicDispatch`'s methods on top of that API.

For `findConstructor` and `instantiate`, you can build them on top of `getDeclaredConstructors`, with virtually the same code as the JVM one in [`Reflect.scala`](https://github.com/akka/akka/blob/f008a932c381013f6060ee00a731862bafed2be7/akka-actor/src/main/scala/akka/util/Reflect.scala)

**Comment by andreaTP** [comment]
That's great! Thanks a lot @sjrd 
I'm working now on a demo of Akka.js, as soon as I have time to get back to core development I will integrate this!

**Comment by jvican** [comment]
This is very sweet. Thanks @sjrd, we'll also need this to make the function-passing model work on scalajs (which is in our feature list).

**Comment by gzm0** [comment]
@sjrd @andreaTP do we still need this to be open, or is scalajs-reflect / linker plugins the way to go?

**Comment by andreaTP** [comment]
I still need to find a slot to test it, sorry :-S
Hope before Scala days Berlin, but not yet sure...

**Comment by gzm0** [comment]
Ah, this is still so new. Fair enough, we can leave this open. Was just scraping through all our issues :)

**Comment by gzm0** [comment]
@sjrd @andreaTP do we still need this to be open, or is scalajs-reflect / linker plugins the way to go?

**Comment by sjrd** [comment]
scalajs-reflect / linker plugin is the way to go, indeed.
