### ISSUE TITLE
Lazy loading for modules

### ISSUE THREAD

**Issue by mdedetrich** [scala-js/scala-js#1751]
I suppose this is a general discussion/feature request in regards to having the ability to lazy load modules (and how we would approach this)

In `javascript` browser land, a lot of frameworks and frontend programmers are moving towards lazy loading parts of the website, and in many cases this includes `javascript` code. This is most apparent in `SPA`'s (Single Page Application), particularly on mobile devices.

In a `SPA`, the entire `Javascript` code tends to be one one static page, and even when minified its not uncommon to have that JS > 1MB. Lazy loading means that a javascript module is only loaded when it gets accessed for the first time (equivalent to scalas 'lazy val'). 

Is this something that `Scala.js` should look into/try to implement. There are many ways to go about this, and it would require changes both to the code committed by the compiler, and the SBT plugin for `Scala.js`. A lot of this also relies on https://github.com/scala-js/scala-js/issues/1703, in order for lazy loading to work you have to split up the various dependencies that your project uses into separate .js files (which is what gets loaded lazy)

Anyone have any ideas?

**Comment by jducoeur** [comment]
How much is needed *other* than #1703?  Lazy loading is one of the two primary use cases motivating that enhancement, and it seems like that's the only core-powertrain part that's needed.

More precisely: doing true lazy loading within a single tightly-defined SJS program seems very unlikely because of how the compiler works.  The primary point of lazy loading is to allow the various parts of the application to evolve at different speeds, so that an update to section A doesn't require the user to download B, C and D as well.  But that's totally incompatible with the way the compiler optimizes the code.

So the way to think of it is instead to define your SPA in terms of multiple projects, with a common framework and well-defined APIs.  (Which is probably the right way to do lazy loading anyway, so you can have decent decoupling.)  So long as those APIs are defined by JSExport (which is probably necessary), then we have pretty much all the *core* elements already.  There's no compiler changes needed, just a lot of framework-building.

Mind, I think it's a lovely idea (Querki is one of the biggest SJS SPAs currently in production), but I think it's a community project rather than a compiler one.  The main issue is that somebody has to build a framework that works this way for folks to use, and we need a solution to #1703 to reduce the boilerplate.

**Comment by mdedetrich** [comment]
The question actually falls down to how you want to treat lazy loading.

If its on a framework level, then you are write in that you only need facade's. You will also probably need some hooking/annotation/reflection system where you can specify which code is loaded asynchronously.

If you wanted to do it on the package level, i.e. using a '%%%' on a JS package (or a `webjar`) will mean that its loaded asynchronously with some extra flag in your `SBT` dependencies. In this case, everything is handled by `SBT` automatically.

The former allows much more fine grained control, but its framework dependent and has a real high chance of being very finicky. I am not sure if we want to emulate the situation that we have in Javascript in Scala.js, in regards to every JS framework out there having to make its own module and dependency injection framework.

The latter is more automatic and a lot less painful in principle, but may lead to complications where you are forced to split out projects into a sub projects or make project wrappers to control how much code is lazy loaded (although it may be possible for `SBT` to provide helpers for this area`. The compiler can actually do automatic lazy loading with this version, because its not out of the question for `Scala.js` to adopt an ABI for javascript packages

I guess its a question of where we want to head to

**Comment by jducoeur** [comment]
Well, there's also the question of the definition of "we".  The facade-based approach is conceptually easy, and doesn't require any particular knowledge of the internals of the existing tools.  The automatic approach, OTOH, at *least* requires expertise in the sbt package, and I suspect requires compiler complicity, and that expertise is much thinner on the ground.

In other words, saying "we" should do something more automatic is fine in principle -- indeed, I agree that it would be lovely -- but may be unrealistic.  I'm suggesting less-fancy approach mostly on the grounds that it seems more plausible that it will actually happen.  Do remember that the official SJS team is small and fairly loaded, so we should keep in mind that this is likely a community project...

**Comment by mdedetrich** [comment]
Sorry I should clarify, when I say "we" I am just talking about the `Scala.js

**Comment by mdedetrich** [comment]
Sorry I should clarify, when I say "we" I am just talking about the `Scala.js` in general (also note that this is my opinion!)

> The facade-based approach is conceptually easy, and doesn't require any particular knowledge of the internals of the existing tools.

I think I should clarify, its easy for dynamic languages. A lot of dynamic languages just inject the JS lazily and modify some global state. In a static language, its not so conceptually easy (in fact, I am not really sure of any static -> js language that has proper support for lazy loading, they all seem to generate single binary blobs, which is what we do). Even in the current frameworks, its not something that is easy. With the current AngularJS as an example (which is what I use), its just kind of a hack which isn't properly supported.

> In other words, saying "we" should do something more automatic is fine in principle -- indeed, I agree that it would be lovely -- but may be unrealistic. I'm suggesting less-fancy approach mostly on the grounds that it seems more plausible that it will actually happen. Do remember that the official SJS team is small and fairly loaded, so we should keep in mind that this is likely a community project...

I don't think we should make an assumption that one approach is easier than the other, they are both just as difficult to implement. Implement lazy loading for a framework for a dynamic language where people still work with treating modules as files and specifying which files to load is *much* easier than for something like `Scala.js`, whether its at a framework level or an SBT level

**Comment by jducoeur** [comment]
Oh, I entirely agree that it should be in sbt, but as a separately-defined plugin rather than as part of scala-js per se.  There's nothing especially controversial about that -- we're used to having additional sbt plugins for additional functionality.  (For example, I am one of many people using the @vmunier Play/Scala.js package, and half the community is using the React adaptor.)

Possibly I'm not understanding what you are proposing, based on you saying that they are similarly easy.  How would you define the APIs between modules?  How would those be defined stably enough to work?  I honestly don't see anything *other* than my proposal in #1703 that doesn't require major surgery to the compiler, but possibly you've thought of something I haven't.  (Or possibly we're actually talking about the same thing in different words...)

**Comment by mdedetrich** [comment]
I think the proposal in #1703 is required regardless if you want lazy or not, but having an ABI for the lazy modules is only half the story, the other half, is well actually loading them (and not only just loading them, but also controlling how much you want to load, when you want to load, how to load)

I mean it opens up a lot of things including

- How are your JS files going to be generated
- How do you control the granularity for how much of the modules are going to be lazy loaded
- What are your modules, are they literally going to be just your .jar dependencies, or are we going to have a separate module type specifically just for lazy loading
- Are we going to instead go into the Dendency Injection route (i.e. we put the stuff we want to lazy load into a class, and use DI to instantiate that object i.e. something like `lazy val object = LazyLoader.load[SomeObject]), or maybe with an annotation?

I think these are the type of questions we need to ask if we wan't to get anywhere with lazy loading. My position is that I want to push as much stuff as possible into `SBT` and out of `frameworks`, mainly because from experience its just created a colossal mess in `Javascript` land with every JS framework creating different incompatible definitions of `modules`. In `Javascript` land, they are actually moving away from every framework implementing lazy loading, and instead they are trying to create a module standard with EMCA. However, as we see with whats happened with `common.js`, once frameworks start implementing their own version of something, it gets really hard to do a standard way of doing things

Like what you (and I) said before, we don't have the luxury of having as many `Scala` developers as there are `Javascript` developers

So my position in TL/DR form is that I want to put as much of lazy loading (as possible) into `SBT` rather than in some framework (whether it be play or something else). This is due to the limited amount of resources we have, and the fact that its better to establish some standard

**Comment by jducoeur** [comment]
I think you've got a false dichotomy here.  I mean, sbt is just a build tool -- it has nothing to do with Scala.js per se except that we all happen to use one specific sbt plugin.  I also think we may be getting hung up on a semantic quibble.  I'm using "framework" in the older and more general sense of "a system that you fill code into", not implying anything about Play or any other client/server tech.

sbt doesn't save us from having to define a framework -- it's just the way you happen to *invoke* the framework.  And I'm going to press here: how *do* you think the JS files are going to be generated?  What do you think the APIs look like?  And yes, how do we deal with dependencies, and is that hard-coded?  (I should note, I actually intensely dislike the idea of having one mandatory DI framework, because I have my own, very mature and very well-developed framework that I prefer.  There is no single best answer to this problem.)

These are the actual hard questions; IMO, the rest is mostly distraction.  I don't think we're disagreeing all that much -- I just think sbt is near-irrelevant to the conversation, because most of the interesting questions don't have much to do with it.  We *have* to define a framework; that framework *has* to have an sbt plugin if people are going to actually use it.  The hard question is what that framework *is*.

Let me turn the discussion around in a more productive direction.  In an ideal world, what would you like to be able to *write* to define these modules and how they are loaded?  Even vaguely -- I have my own *very* hazy ideas here, but I'm curious what you have in mind.  Not everything is possible, but it's often best to start with an idealized end-goal and work backwards to the plausible from there, fleshing in the details as we go...

**Comment by mdedetrich** [comment]
> sbt is just a build tool

Its not a false dichotomy, because you can argue (either way) whether lazy loading is part of the build process, or not. This distinction is pretty much non existing in dynamic languages, but in static languages one can argue either way.

There are good arguments for having lazy loading as part of the build process (in this case SBT), since such a tool can verify that modules/dependencies are loaded correctly, or one can argue about whether it should sit entirely as part of the code.

My personal opinion is that as much of the lazy loading should be handled by SBT as possible, but it is a question of whether lazy loading of modules (versus static loading of modules, which is what SBT does right now, when you compile a program, it loads of the modules, i.e. whats in your classpath, statically) should be part of SBT or not

> Let me turn the discussion around in a more productive direction. 
Completely agreed, and I think this is what should be done from now on. I need to spend some more time making a more comprehensive list rather than hand waving, because honestly, lazy loading isn't something that even the dynamic world has gotten right, at least in an framework agnostic way.

On another note, an advantage of having lazy loading implemented (as much as is possible) in SBT, is that it can be reused for other backends, including JVM (or even any other backend that Scala might happen to support in the future). The basic premise behind lazy loading is the exact same as loading `.dll/so` files in the C/C++ compiled world, or loading `.jar` plugins which is familiar to people using swing

**Comment by jducoeur** [comment]
Hmm.  I'm still having trouble seeing what sbt per se has to do with it, since sbt isn't actually running at load time.  If you can some up with a sketch of what you're thinking architecturally -- what the pieces are and what each one does when -- it might help with the disconnect...

**Comment by sjrd** [comment]
The issues discussed here need a combination of two things to happen:

1. a way to generate several JS *modules* from a Scala.js codebase, and
2. something to lazily load those modules.

(1) can be addressed by either of two things:

* Either as #1703 on the basis of a "manual" per-project distinction of modules
* Or as #2681 on the basis of an "automatic" decomposition in modules taken care of by the compiling pipeline

(2) requires an external tool/system/library/whatever to actually lazily load the modules thus decomposed. But that should not be part of Scala.js core. Once separate JS modules are obtained from a Scala.js codebase, we can use any sort of JS lazy-loader (such as SystemJS?). Whether this is integrated in an sbt plugin or not is irrelevant; a third-party sbt plugin can be made (e.g., [scalajs-bundler](https://scalacenter.github.io/scalajs-bundler/) is proof that complementary integration with JS ecosystem tools can be done outside of core).
