### ISSUE TITLE
Building large modular JS / ScalaJS projects

### ISSUE THREAD

**Issue by slorber** [scala-js/scala-js#1787]
Hi,

I'm trying for some time to find a solution to this problem and nobody seems to find it either.

What I want is to be able to build a large app that has at least 30 modules with ScalaJsn.
The app already exists, and the modules have been published on a private NPM repository, and are aggregated into one or different JS client apps (connected user/visitor/mobile/cordova/clipper bookmarklet...) by using Browserify or Webpack.
If I were to use ScalaJS I would migrate the existing modules one by one.
I am concerned by the build time, but also the bundle size.

However, not like others I'm perfectly fine with a 10Mb production bundle, even after full optimization (this is already near what we get with plain JS for a medium sized SPA, and it loads fast enough with gzip compression... but we also have something like 20 libraries used...)

As the project is not so small and modularized, I think it would not make sens to put all modules in a single Scala project (or SBT submodules) as it would probably take a long compilation time (I may be wrong?).

So I was thinking of being able to publish each module on NPM independently (wether it is a migrated ScalaJS module, or a legacy plain JS module) and glue these modules together with a plain JS project with Browserify / Webpack.

The problem is that as far as I know there's at least 100k of scalajs runtime per module that would be published on NPM, and aggregating 30+ modules with that overhead will lead to a lot of overhead. Not to mention all my modules would be using `scalajs-react` so the overhead would probably be much greater than a plain old HelloWorld

So I am wondering if there is any solution to this problem?

I guess optimizing the final output after Browserifycation will not reduce that overhead as GCC / Uglify will not be able to deduplicate ScalaJS Runtime things (right?)

I was suggesteds here that there could be something to be done by using `.sjs` files directly but don't really know how it could solve the problem.

Some useful links:
https://github.com/rockymadden/scala-node/issues/3
https://github.com/scala-js/scala-js/issues/1477
http://underscore.io/blog/posts/2015/06/10/scalajs-scaladays.html

What I wonder is if it would be possible, when publishing a ScalaJS project to NPM, to use something like `dependency` or `peerDependency` so that the external code is excluded from the project but has to be provided by the module client. Somehow I think this means that the ScalaJS runtime needs to be modularized and published on NPM so that other ScalaJS modules can use require.
I mean if 2 modules use the Scala collections, instead of packaging the Scala collections into the ScalaJS runtime, maybe I can publish my 2 modules with a npm dependency on `scalajs-collections` instead. You see what I mean? Don't know if it's possible at all...

**Comment by mdedetrich** [comment]
This relates to https://github.com/scala-js/scala-js/issues/1703, and somewhat to https://github.com/scala-js/scala-js/issues/1751

Its currently being debated. I think pushing stuff to `npm` is out of question (mainly because we already have `webjars`. We are currently debating about how much of the `module` system should be done by SBT (as a plugin, or otherwise part of core) vs how much should be part of the framework, as well as defining what `modules` are in the first place (in the javascript sense)

I am still writing up what my own vision is, mainly so I have something concrete to discuss with @jducoeur, but for now, its still being discussed.

**Comment by slorber** [comment]
sorry @mdedetrich but I don't agree with you and wonder why using npm is out of question.

For me webjars is absolutly not what I'm looking for. We are building JS apps, that may integrate some ScalaJS components but the main language is still JS. I'm using Gulp / NPM with a quite complex build pipeline and won't do anything with ScalaJS if it forces me to use SBT or webjars. 

Webjars solves an unexisting problem for people that did not want to invest time in learning the JS ecosystem. There are already mature solutions for JS dependencies and build, why not use them, just because you are not used to use these tools? It's not at all complicated to use a `package.json` file and type `npm install` on the terminal, why would I need something else?

In addition I need to use tools like Browserify or Webpack because I need to bundle my app. I produce 3 separate fils (appPolyfills.js, appLibs.js and app.js, the first 2 trying to hit the cache the most they can). I'm not loading my app with plain old list of script tags on the top of an HTML file. And as far as I know Browserify is probably not compatible with Webjar as it requires the NPM node_modules folder to be available with the dependencies. It is out of question to assign libraries to the global scope.

As explained I have something like 30 components. So if I want to use ScalaJS for one of them I have to switch my whole pipeline to SBT? And then what if I want to test 3 different solutions that compile to JS, would it make sens to use the language specific build tool everytime, forcing me to maintain 3 different build setups?


To me, not using NPM is crazy. It is the well-accepted js solution for dependency management and thus is the common denominator for all projects that need to use JS libraries. 


Even if using a a Scala backend (like we do), you do not have to couple your frontend build to what you use on the frontend. We use Play2 backend, and our SPA is served by Play2, but still we use JS specific tools to build JS apps, instead of trying to reuse the existing SBT build.


I must admin I've already used SBT to do frontend stuff, like using webjars or compiling LESS files, minifying... The build is simpler since we use a single tool and it works great for simple usecases. but is absolutly not suitable for large frontend projects.

**Comment by mdedetrich** [comment]
> sorry @mdedetrich but I don't agree with you and wonder why using npm is out of question.

I don't think its out of the question, but its a lot of effort for something that
1. Segregates the ecosystem
2. Is something thats really hard to get "right", especially when we need to account for breaking API changes in Scala.js

To be clear, there is nothing stopping people from making an integration layer for `npm` in the form of a plugin if they want to, but I definitely wouldn't count on the core `Scala.js` team doing something like that.

> For me webjars is absolutly not what I'm looking for. We are building JS apps, that may integrate some ScalaJS components but the main language is still JS. I'm using Gulp / NPM with a quite complex build pipeline and won't do anything with ScalaJS if it forces me to use SBT or webjars.

We also use `npm`/`grunt` for out frontend management, but we are going to be moving away from it (thankfully we are at a stage were this is a manageable proposition). So in this regard, I perfectly understand where you guys are coming from, but I would rather that efforts (at least if we are talking about the `Scala.js` team, and the community in general) be taken in improving the SBT build tool so it does the tasks that we would typically do with `npm`/`grunt`.

The reason why `webjars` are mentioned, is that if you are *are* using `SBT`, that is essentially the `bower`/`npm`, for SBT. Its the repository where compiled JS/CSS/HTML assets are placed that interfaces with maven

> In addition I need to use tools like Browserify or Webpack because I need to bundle my app. I produce 3 separate fils (appPolyfills.js, appLibs.js and app.js, the first 2 trying to hit the cache the most they can). I'm not loading my app with plain old list of script tags on the top of an HTML file. And as far as I know Browserify is probably not compatible with Webjar as it requires the NPM node_modules folder to be available with the dependencies. It is out of question to assign libraries to the global scope.

Yup, and on my end, we are using `require.js` + other tasks to take care of the pipeline when it comes to asset management. So this leaves us with 2 directions
- Implement functionality as plugins/core into `SBT` so it does what Browserify/Webpack does.
*or*
- Implement grunt integration with `Scala.js`

The former is where I believe we should be putting (most) of our effort. I think realistically someone doing a light plugin for `SBT` that allows you to wrap `@JSExported` Scala code into an AMD module (and also wrapping the runtime) has merit as a stop gap solution (with grunt taking over the rest), but the former is definitely where we want to be.

> As explained I have something like 30 components. So if I want to use ScalaJS for one of them I have to switch my whole pipeline to SBT? And then what if I want to test 3 different solutions that compile to JS, would it make sens to use the language specific build tool everytime, forcing me to maintain 3 different build setups?

Thats twisting what my statement was. My proposition is that the core team shouldn't spend a non trivial amount of time trying to create a plugin layer for an entirely different build system that is outside of the ecosystem. I didn't say that people should be forced to move their entire build systems, that clearly isn't realistic. For example, internally in our company we use wrappers for `grunt` and `bower` to interface with SBT, i.e.
- https://github.com/mdedetrich/sbt-bower
- https://github.com/rossbayer/grunt-sbt

These plugins are like 100 lines of code (not a lot) and just wrap around the `npm`/`bower` commands.

> To me, not using NPM is crazy. It is the well-accepted js solution for dependency management and thus is the common denominator for all projects that need to use JS libraries.

Firstly lets be clear, NPM is the well accepted solution for `Javascript` **source** dependency management. SBT is the accepted solution for `Scala` **source** dependency management (which uses Maven behind the scenes). `npm` isn't a dependency management solution for `Java`/`C`/`C++`/(insert other language here), so expecting that `SBT` should inherently support a build tool for a completely different language is a bit farfetched. The fact that `Scala.js` generates `Javascript` means that it treats `Javascript` as a bytecode format, just like compiling `Scala` with `scalac` generates JVM ByteCode as a byteCode format. `Scala.js` definitely gives you more control over how things are outputted, because you actually need to run the `Javascript`, as well as integrate with other code, but claiming that `SBT` should support an package management system for an entire different language with an entire different ecosystem is a bit absurd

The other thing is, what you mentioned, isn't the *well-accepted js solution*, its one of them. `Javascript` in this sense is terrible, where they have competing module systems (AMD/Common.js/ new ECMA script modules), competing asset management systems (webpack, browserify, etc etc), competing DI systems (require.js vs frameworks providing their own), competing package management systems (`node.js`,`bower`), etc etc.

Within our company, we have used `grunt.js`, but I now regret it, however we didn't really have a choice. Stuff in `Javascript` land moves too fast in regards to how modules/DI/Lazy Loading + framework integration (and everything around it), moves. Our entire frontend build system, which uses `grunt`/`bower`/`npm` is already obsolete, doesn't compile with the latest version of node, and it would require as to rewrite our build system for it to get it to work with the latest version, and this all happened in just over a year.

I have been doing frontend development for 5 years now (along with backend development), and we definitely do not want to replicate what happens in JS land in this regard. What happened with JS is definitely understandable since they didn't establish a standard for modules, however its very chaotic in this regard, and I think we should avoid this if possible.

> Even if using a a Scala backend (like we do), you do not have to couple your frontend build to what you use on the frontend. We use Play2 backend, and our SPA is served by Play2, but still we use JS specific tools to build JS apps, instead of trying to reuse the existing SBT build.

No you don't, we havn't and I suspect most companies haven't. But we are now in this territory were we have `Scala` compiling to `Javascript`, and just like you would expect to use `Javascript` build tools to deal with `Javascript`, we would expect `Scala` build tools (which currently is `SBT`) to use build and manage `Scala` code

For right now, you would have to make an `SBT` plugin that tries to create NPM modules out of the scala runtime, and also from `@JSExport`ed code. This isn't something that is easy to do, but I am not sure what you would expect. You have competing build systems, and you are trying to integrate them in a **very** tightly, coupled way. Since `Scala.js` is in Scala, you **need** SBT to build your `Scala` code. You would have this exact same problem with any JS backend from any other language if you want to integrate it with `npm`/`grunt`. Thats not even taking into account that `npm` is package management for `node.js` backend (not even getting to other backends, like `vert.x` and `bower`). `Scala.js`, I believe, in its design, is meant to be `javascript` client agnostic, so using NPM is preferring one javascript backend over others.

> I must admin I've already used SBT to do frontend stuff, like using webjars or compiling LESS files, minifying... The build is simpler since we use a single tool and it works great for simple usecases. but is absolutly not suitable for large frontend projects.

Agreed, and many people (including you, and myself) are stock between a rock and a hard place in this regard, **but** I think claiming that `SBT` should provide support for `grunt`/`npm` just because it happens to be what `javascript` is drawing a really long bow. I would rather most of the effort go towards `SBT`/`SBT` plugins + frameworks to fix this.

Putting `npm` support in `SBT` is a really short sighted solution, which will cause a lot of pain in the long run.

**Comment by slorber** [comment]
@mdedetrich I diidn't say we should support NPM through SBT.
I'm perfectly fine to use ScalaJS tooling while still being in the ScalaJS world.


But my JS client side app is a composition of ScalaJS and plain old JS modules and libraries. 
For example my client side app could be:
- A main JS file entry point
- 3 Scala JS modules
- 20 NPM modules
- Gulp / Browserify to produce a single JS file file

I don't have any problem using SBT for the ScalaJS things. I don't want to use SBT to do things with npm or Gulp or Browserify. But at some point I have to package my JS app and Browserify is a good tool for that. 

So the idea is to use SBT to produce JS files, publish them on npm and then do like if they were regular JS modules. Once published, these modules won't ever have to be recompiled when my client side app changes.

The " big optimizations" of ScalaJS does not need to happen because optimizing is already in my JS pipeline when NODE_ENV=production. When fetched the node_modules are not optimized either and it's the choice of the client to perform the optimizations he wants to. (but maybe it's still required for ScalaJS as I wouldn't like to have modules of 20mb published on npm)


Doing all the stuff like Grunt in SBT. It is up to you. Wrapping your JS build in SBT does not solve at all the problem because at the end it's still the JS tooling that kicks in. I want to use Browserify or Webpack on a large project and being able to use advanced packaging configuration, hot code reloading and stuff like that.  These tools don't work with Webjars. 
I don't care about using NPM or bower or whatever, but these tool are used my many, and many libraries have setup a package.json to express dependencies. Whatever you do with SBT, if I can't use the dependency graph already setup in these libs, or have to contact the autors to create or maintain webjars it is a no go: you have to integrate with existing tools first before reinventing your wheel or nobody will adopt... 


NPM is no more source dependency management. Javascript is the browser VM so it's a very similar role comprared to Maven: you publish what everyone is able to understand, wether it is compiled Java or Scala for the JVM, or Javascript for the browser.

**Comment by jducoeur** [comment]
I don't know the JS tools like npm and Grunt terribly well, so I've mostly been keeping quiet in this discussion.  One note, though: the most crucial Scala.js optimization is dead code elimination, and you almost certainly do want that one in it -- otherwise, your application is apt to contain lots of code that is never being called.  And DCE has a lot of implications for the way the stack works: it's a primary reason why SJS thinks in terms of the application as a whole, why JSExports need to be stated, and so on...

**Comment by slorber** [comment]
@jducoeur isn't there a way to publish unoptimized code to NPM, and then do the Dead Code Elimitation at a later stage? Because clearly I want DCE to happen at the end of my mown packaging pipeline, but still I need it efficient...

**Comment by sjrd** [comment]
@slorber No, you cannot publish unoptimized code to npm, because there is no such thing as unoptimized code, or, to be more precise, Scala.js does not optimize js code. It optimizes its .sjsir files. So if you publish .js files to npm, you have already linked and optimized one project at a time, and you cannot re-link after that.

GCC is an implementation detail in Scala.js. It is not trivially applied on the output of fastOptJS. There are other stuff going on. It is virtually impossible to apply correctly (and even less so reliably) GCC to Scala.js code if you do it yourself, outside Scala.js' tools.

If you know you'll have more Scala.js projects that will form your application, you should publish them as .jars, and use the Scala.js linker and optimizer at the latest stage. .jars contain .sjsir files (not .js files), and are therefore the unoptimized form that is meant to be published. If you link everything together at the last stage, you won't have duplicate runtime.

> As the project is not so small and modularized, I think it would not make sens to put all modules in a single Scala project (or SBT submodules) as it would probably take a long compilation time (I may be wrong?).

You are mostly wrong. sbt uses incremental compilation, so that the modular separation between sbt subprojects matters little to the compilation time. Even so, you can separate in several sbt subprojects, that does not mean you can *link* everything together in one final subproject that depends on all the others. Scala.js' linker and optimizer is also incremental, so that the amount of code to be optimized in one pass does not matter much to the compilation time starting from the second run in one sbt session (although it does have an impact on the RAM used).

**Comment by mdedetrich** [comment]
> @jducoeur isn't there a way to publish unoptimized code to NPM, and then do the Dead Code Elimitation at a later stage? Because clearly I want DCE to happen at the end of my mown packaging pipeline, but still I need it efficient...

@sjrd explained it well, but more succinctly, `Scala.js` treats Javascript literally as a form of bytecode, which means only the final output (defined by `@JSExport`) is javascipt, before that is an intermediate formats (`.sjsir`)

There is a discussion which I linked earlier that is about creating facade's for code compiled with `Scala.js`, but thats only about splitting your emitted code in several parts so you can load them in stuff like CDN. Getting those parts to work with general JS code is a different ballgame.

Like mentioned earlier, its a **lot** of work, you would have to make a separate backend, and you would also have to adhere to an javascript compatible ABI. Although `Scala.js` has fantastic interoperability for `Javascript`, its not designed to be a transcompiler like `Coffeescript` or `Typescript`

**Comment by sjrd** [comment]
> @sjrd explained it well, but more succinctly, Scala.js treats Javascript literally as a form of bytecode, which means only the final output (defined by @JSExport) is javascipt, before that is an intermediate formats (.sjsir)

To be more precise, we treat javascript code as machine code, on which we can't do anything more, and can only feed to the "processor" (the js vm). Our bytecode is sjsir files.

**Comment by slorber** [comment]
Ok thanks I understand your point.

So if I understand correctly, the best way to produce a JS file is to have my modules as Scala jars, and compile them all at the same time and produce a single optimized output. Then I can still use this ScalaJS code as a library in another JS project. Thanks to incremental compilation, and the fast optimizer, I can still be productive in dev environment. Right?

So once I get that "machine code" I guess I can publish it to NPM (even if that does not bring me anything ^^)

Instead of having a single ScalaJS packaging pipeline for all modules, is it possible to have one pipeline per module, and publish the multiple "machine code" js files to NPM? I guess we can but it's not recommended as 2 ScalaJS modules will probably share a lot of scala js internals machine code and make my bundle big.



I'm asking all this because if we were to introduce ScalaJS to our project it would be very gradually. We have frontend developers with no prior experience with Scala and that are bored to death because of compilation time when they have to work with Play2 scala templates. So we need to be able to test ScalaJS without requiring these developers to have to recompile ScalaJS everytime they change their git branch or things like that, and using NPM seems the right solution to solve this problem.

**Comment by sjrd** [comment]
Yes, you can have one pipeline per module. And yes, some code will be duplicated in several modules.

**Comment by slorber** [comment]
Thanks, and what is the approximate amount of duplicated machine code if I have something like 10 independant ScalaJS modules? Would it be something like 10* 150k? Would repassing the code iin GCC / UglifyJS reduce that size? Or would Gzip compress that duplicated code efficiently?

**Comment by sjrd** [comment]
> what is the approximate amount of duplicated machine code if I have something like 10 independant ScalaJS modules? Would it be something like 10* 150k?

It will deep depend a lot on how much shared code is actually used by the different modules.

> Would repassing the code iin GCC / UglifyJS reduce that size?

No. 

> Or would Gzip compress that duplicated code efficiently?

No.

**Comment by slorber** [comment]
ok thanks @sjrd 
I ask asking for an estimate don't hesitate to give something that is very wrong :) I would use on each module reactjs-scala, immutable collections, tuples, case classes, options, map, flatmap, futures...

Just want to know if this is realistic to split for a production usecase or if I should rather go with a single ScalaJS compilation pipeline and only use jars.

**Comment by stuhood** [comment]
What would the feasibility be of a mode for the linker to receive N input modules and generate N+1 output JS files, while still doing dead code elimination?

The idea would be that if you have K javascript "binaries" (N>=K), the output would be one JS file containing all 3rdparty code, then one blob for each of your N modules with dead code elimination deciding what is eliminated from each module.

This would handle the case of incrementally loading portions of a javascript app that is split across multiple pages.

**Comment by easel** [comment]
@slorber I think you may find that if you consider compiling two JS blobs with two toolchains, most things will work themselves out. Use scala.js with sbt to compile all your modules, think of it as babel + webpack/browserify + uglify. Use npm et al for your js stuff. Then you just need to make sure that "shared libraries" like jquery et al are available to both.

Personally I'm using the -jsdeps file from scala.js for this since I am stuck with require on the .js side, but if you're using a full toolchain you should be able to construct an equivalent file using js tools quite easily.

**Comment by sjrd** [comment]
I believe the problems and solutions raised in this discussion are addressed by a combination of:

* [Emitting CommonJS modules](https://www.scala-js.org/doc/project/module.html) (see also #2175)
* [scalajs-bundler](https://scalacenter.github.io/scalajs-bundler/)
* Possibly #2681 if the output needs to be decomposed for lazy-loading reasons

**Comment by slorber** [comment]
great thanks :)
