### ISSUE TITLE
Double build time after upgrading to 0.6.4 from 0.6.3

### ISSUE THREAD

**Issue by ngbinh** [scala-js/scala-js#1788]
We had experienced almost double build time after upgrading to `0.6.4` from `0.6.3`. 

A simple `;clean; test; fastOptJS` took more than twice as long in `0.6.4`. It is especially bad right when the build switch from `jvm/test` to `js/test` where it seems to hang for a long time with 100% CPU. 

Below is the thread dump of `sbt` process at that moment: https://gist.github.com/ngbinh/cd26204caf7976db8433 . It looks like it's spinning on `OptimizerCore` mostly.

**Comment by sjrd** [comment]
Do you have a project I could experiment with?

**Comment by ngbinh** [comment]
I can probably try to use scala.js spa tutorial. The strange part is `fullOptJs` tends to run faster than `fastOptJs` for me on 0.6.4. So #1722 looks suspicious to me. My current work around is to separate the build into two commands(`./sbt js/test && ./sbt jvm/test`). One command to build anything scala.js and the other for jvm. The main reason I do so is because I saw the build process eat up all the memory it can (3GB) when `js/test` starts running. That's also the state captured in thread dump.

With that, the time is manageable but still higher than 0.6.3.

**Comment by sjrd** [comment]
#1722 cannot have anything to do about it. `fastOptJS` does not use Rhino.

**Comment by InTheNow** [comment]
+1 I have exactly the same issues in cats and spire, both in travis and in local builds. But here, the builds never finish - and its always in fastOptJS. Usually I can get my locally by using 4G+ of memory in sbt, obviously I cannot do that in Travis-CI. First came in https://github.com/non/cats/pull/427#issuecomment-127183687 , https://github.com/non/cats/issues/429#issuecomment-127254096, and https://github.com/non/spire/pull/485#issuecomment-127023876

See
- https://github.com/adelbertc/cats/blob/xor-recover/.travis.yml#L12
- https://github.com/adelbertc/cats/blob/xor-recover/build.sbt#L215
- https://github.com/non/spire/blob/master/build.sbt#L201

**Comment by ngbinh** [comment]
@InTheNow what I did was to separate `js/test` and `jvm/test` to two separate JVMs. Otherwise, `sbt` will hang for ages (~10 minutes in my case) on GCing and not doing anything else.

**Comment by InTheNow** [comment]
@ngbinh Thats what I did as well - see the two `.travis.yml` files. And yes, 10+ minutes delays are exactly what causes Travis-CI to crash as it has a 10 minute time out, and I would agree that it appears the issue is related to GC'ing in linking. Tavis-CI builds are limited in memory to ~4G including swap, so a combination of serialization/memory provides workarounds.

But the underlying cause is still there, no doubt waiting to pop up again at the most inconvenient moment. For Cats: 
- Cats is a new project
- Scala-js cross building is even newer
- Tests we upgraded to use scalatest 3.0.0-M7. These are mainly based on [Discipline Laws] (https://github.com/typelevel/discipline), that are in turn based on [scalacheck propeties](http://www.scalacheck.org/)
- Whilst deploying/testing all this, bintray and sbt hosting decided to go AWOL

Hence, the issues could have been down to a number of things - including me - so I have held off adding to this issue until there was a moderately stable build, with a repeatable "this works, this doesn't".

If any help is needed on this - examples, etc - please ask.

**Comment by InTheNow** [comment]
Looks like this could be a revival of https://github.com/scala-js/scala-js/issues/1525

**Comment by InTheNow** [comment]
Just one addition, using a [custom jvm options on traivs](https://github.com/propensive/rapture/blob/dev/.jvmopts) seems to help enormously, but the splitting of `fastOptJS` into a separate `sbt` process is still usually required (ratpture, for example, does not have cross-compiling tests).

Also, I have tried playing around with some of the scala-js optimisation settings, in particular turning of caching, but with no success. Perhaps I erred here. One thought in this respect might be a `CI-mode` or `non-interactive mode` that set a bunch of options automatically. Just a passing thought.

**Comment by sjrd** [comment]
Does this still happen in 0.6.6?

If it does, you might improve the situation by deactivating the incremental linker on your Travis builds with:

    scalaJSOptimizerOptions in theJSProject ~= { withBatchMode(false) }

You can for example set on the command-line with

    sbt 'set scalaJSOptimizerOptions in theJSProject ~= { withBatchMode(false) }' js/test

**Comment by ngbinh** [comment]
will check tomorrow at work.

**Comment by ngbinh** [comment]
`scalaJSOptimizerOptions in theJSProject ~= { _.withBatchMode(true) }`

helps quite a bit. Also, things look sane now. Thanks

**Comment by gzm0** [comment]
Note that in 0.6.6 onward, `withBatchMode` can significantly reduce memory footprint in a multi project build, because it releases the whole linker immediately after it has run. This is was not the case in pre 0.6.6.

**Comment by ngbinh** [comment]
so what's the problem for having it set to `true` by default? Would it causes problem with incremental dev build?

**Comment by sjrd** [comment]
Well yes: dev builds would not be incremental anymore (and you don't want that any more than you want to `clean` before each `compile`).

**Comment by ngbinh** [comment]
got it, thanks!
