### ISSUE TITLE
js.| union type

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1824]
Edit: the original proposal was to name it `\/`.

It would be worth thinking about a union type constructor for facade types. Similar to `js.UndefOr[+A]` in its construction, `js.|[+A, +B]`, or whatever it's called, would represent a value of type `A` or `B`. It would have zero API, though. The basic idea is the following:
```scala
@RawJSType // don't do this at home
sealed trait |[+A, +B]

object \/ {
  implicit def fromA[A](a: A): A | Nothing = a.asInstanceOf[A | Nothing]
  implicit def fromB[B](b: B): Nothing | B = b.asInstanceOf[Nothing | B]
}
```
Then of course we need ways to transitively convert an `A`, a `B`, or a `C` to an `A | B | C`. This probably needs a bit of recursive implicit magic. Even trickier: convert `A | B`, `A | C` and `B | C` to `A | B | C` ^^

**Comment by guersam** [comment]
+1, it would cover some tricky cases that can't be solved by overloading.

**Comment by sjrd** [comment]
So, I had this *almost* working implicit magic:
```scala
@scala.scalajs.js.annotation.RawJSType // Don't do this at home!
sealed trait \/[+A, +B]

object \/ {
  trait Evidence[-A, +B] {
    def apply(a: A): B
  }

  private object CastEvidence extends Evidence[Any, Any] {
    def apply(a: Any): Any = a
  }

  implicit def evBase[A]: Evidence[A, A] =
    CastEvidence.asInstanceOf[Evidence[A, A]]

  implicit def evA[A, A2](implicit ev: Evidence[A, A2]): Evidence[A, (A2 \/ Nothing)] =
    CastEvidence.asInstanceOf[Evidence[A, (A2 \/ Nothing)]]

  implicit def evB[B, B2](implicit ev: Evidence[B, B2]): Evidence[B, (Nothing \/ B2)] =
    CastEvidence.asInstanceOf[Evidence[B, (Nothing \/ B2)]]

  implicit def from[A, B <: _ \/ _](a: A)(implicit ev: Evidence[A, B]): B =
    ev(a)
}
```
which is basically able to resolve everything *if* `from` is called explicitly. For example, this works:
```scala
val x: Int \/ String \/ Boolean = from("hello")
```
but it cannot call `from` implicitly. So this does not work:
```scala
val x: Int \/ String \/ Boolean = "hello"
```
After investigation with Denys, it appears that the latter results in a *diverging implicit expansion*, which is caused by the heuristics that the compiler uses to detect infinite expansion. Although it's not infinite in this case, the compiler thinks so. This is because the implicit Evidence required by `from` (`Evidence[String, Int \/ String \/ Boolean]`) is "bigger" (or equal I guess) than the initial implicit conversion required (`String => Int \/ String \/ Boolean`).

Denys thinks that implementing `from` as macro that does *not* take any implicit evidence, but that asks for an implicit evidence itself, will work. Because then the "initial" implicit search is already the big Evidence.

**Comment by sjrd** [comment]
I nailed it, and without any macro! :D I had to abandon covariance of `\/`, though. But that's fine, because I can "restore" it using an additional implicit conversion ^^
```scala
@scala.scalajs.js.annotation.RawJSType // Don't do this at home!
sealed trait \/[A, B]

object \/ {
  /** Evidence that `A <: B`, taking top-level `\/`-types into account. */
  sealed trait Evidence[-A, +B]

  object Evidence {
    /** A unique (and typically dead-code-eliminated away) instance of
     *  `Evidence`.
     */
    private object ReusableEvidence extends Evidence[Any, Any]

    /** `A <: A`. */
    implicit def base[A]: Evidence[A, A] =
      ReusableEvidence.asInstanceOf[Evidence[A, A]]

    /** If `A <: B1`, then `A <: B1 \/ B2`. */
    implicit def left[A, B1, B2](implicit ev: Evidence[A, B1]): Evidence[A, B1 \/ B2] =
      ReusableEvidence.asInstanceOf[Evidence[A, B1 \/ B2]]

    /** If `A <: B2`, then `A <: B1 \/ B2`. */
    implicit def right[A, B1, B2](implicit ev: Evidence[A, B2]): Evidence[A, B1 \/ B2] =
      ReusableEvidence.asInstanceOf[Evidence[A, B1 \/ B2]]

    /** If `A1 <: B1` and `A2 <: B2`, then `A1 \/ A2 <: B1 \/ B2`.
     *  This basically encodes covariance.
     */
    implicit def upcast[A1, A2, B1, B2](implicit ev1: Evidence[A1, B1],
        ev2: Evidence[A2, B2]): Evidence[A1 \/ A2, B1 \/ B2] =
      ReusableEvidence.asInstanceOf[Evidence[A1 \/ A2, B1 \/ B2]]

    /** `Int <: Double`, because that's true in Scala.js. */
    implicit def intDouble: Evidence[Int, Double] =
      ReusableEvidence.asInstanceOf[Evidence[Int, Double]]
  }

  /** Upcast `A` to `B1 \/ B2`.
   *
   *  This needs evidence that `A <: B1 \/ B2`.
   */
  implicit def from[A, B1, B2](a: A)(implicit ev: Evidence[A, B1 \/ B2]): B1 \/ B2 =
    a.asInstanceOf[B1 \/ B2]
}
```

**Comment by gzm0** [comment]
Hmm... I guess abandoning covariance is fine, because the union type won't play well in variant positions inside generics anyways:

```scala
val s0 = Seq.empty[Int]
val s1: Seq[Int \/ String] = s0 // type error, needs a (noop) map
```

**Comment by sjrd** [comment]
Yes, that too.

**Comment by sjrd** [comment]
Oh, and for the record, a WiP implem is available at https://github.com/scala-js/scala-js/compare/master...sjrd:union-type
It includes positive test cases.

**Comment by sjrd** [comment]
I pushed the thing further, and now it supports arbitrary permutations of base types, as well as arbitrary subsetting of base types, and even partial "aggregation" of subsets of base types with upper bounds.

It's available on the same branch (see previous comment)

**Comment by godenji** [comment]
Really nice. 

Question:
`A \/ B`, ok, but why not the everyone-immediately-gets-it, `A Or B`?

Scala has a bad rep in the operator overloading department; don't see a reason to choose `\/` over `Or` in this case beyond it being known to Scalaz users. Certainly neither easier to type nor easier to read...

**Comment by gzm0** [comment]
I think that's a very valid point. I think this would also align nicer with `UndefOr`.

**Comment by sjrd** [comment]
True, it makes more sense wrt. `UndefOr` ...

**Comment by gzm0** [comment]
Note that having a `js.` prefix does not work with infix notation. So we might want to consider `jsOr`.

**Comment by benjaminjackman** [comment]
I did not have any aspirations to get this to type the input variables to functions for facades, the motivator being making the Typescript translator work. (To that end #1820 also helps a great deal, one remaining one would be to get the string literal.type stuff working).

I'd suggest using `|` rather than 'jsOr' or 'or' or '\/' for the name then the syntax will be identical to typescript. Unlike a lot of uses of symbolic operators this `|` is actually doing exactly what everyone would expect with regard to types and is similar to the syntax used in other languages.

Here was my type-checker friendly only (using it for facades) [version](https://github.com/benjaminjackman/mutaspace/blob/1d1757149010292b963c553c849ae7e96c7a9b80/mutaspace/src/main/scala/biz/jackman/facades/Union.scala)

Note that I add to keep adding higher arities of implicits to get it to work for higher levels of or's.

**Comment by benjaminjackman** [comment]
Here is the version I have been experimenting with:

```
object | {
  implicit def t1ToU2[T](x: T): T | Nothing = x.asInstanceOf[T | Nothing]
  implicit def t2ToU2[T](x: T): Nothing | T = x.asInstanceOf[Nothing | T]

  implicit def t1ToU3[T](x: T): T | Nothing | Nothing = x.asInstanceOf[T | Nothing | Nothing]
  implicit def t2ToU3[T](x: T): Nothing | T | Nothing = x.asInstanceOf[Nothing | T | Nothing]

  implicit def t1ToU4[T](x: T): T | Nothing | Nothing | Nothing = x.asInstanceOf[T | Nothing | Nothing | Nothing]
  implicit def t2ToU4[T](x: T): Nothing | T | Nothing | Nothing = x.asInstanceOf[Nothing | T | Nothing | Nothing]
}

trait |[+T1, +T2] extends js.Object

class A
class B
class C
class D

trait Foo extends js.Object {
  def ab(x: A | B): js.Any = js.native
  def abc(x: A | B | C): js.Any = js.native
  def abcd(x: A | B | C | D): js.Any = js.native
}

object Bar {

  val a = new A
  val b = new B
  val c = new C
  val d = new D

  val x: Foo = null

  x.ab(a) //Compiles
  x.ab(b) //This too

  //  x.stringOrInt(5.0) //Nope

  x.abc(a) //Ok
  x.abc(b) //Ok
  x.abc(c) //Ok

  x.abcd(a) //Ok
  x.abcd(b) //Ok
  x.abcd(c) //Ok
  x.abcd(d) //Ok
}
```

**Comment by sjrd** [comment]
@gzm0 `jsOr` is plain ugly. The idea for this type is to import it when you need it so that you use without prefix. If that happens to clash with another library library, well, that's what renaming imports are for. 

From other comments on gitter, it seems that
* Nobody likes `\/`
* Several people prefer `|` (same syntax as TypeScript and dotty)
* `Or` is so far the preference of @godenji only

**Comment by guersam** [comment]
+1 for `|`. Also, would it make sense to represent `UndefOr[A]` as `

**Comment by guersam** [comment]
+1 for |. Also, would it make sense to represent `UndefOr[A]` something like `A | Undefined` for consistency?

**Comment by gzm0** [comment]
I also thought about `|`. It will also make migration to Dotty more straightforward.

Renaming `UndefOr` should be doable, since the operations are pimped anyways... But not sure if what to do with `UndefOr` and whether having some "magic" operations on particular instantiations of a generic type is desirable (I'm assuming the ScalaDoc won't show them).

**Comment by sjrd** [comment]
`UndefOr` cannot change in 0.6.x for compatibility reasons. Besides, it provides an API, contrary to the union type. We *could* implicit pimp the API on union types involving `Unit` (which is the true type for `undefined`), but I am not sure that would make it clearer. `UndefOr` has its own very good analogy to `Option`.

**Comment by sjrd** [comment]
I guess ScalaDoc wouldn't show them, indeed. I don't see where it could show them.

**Comment by benjaminjackman** [comment]
I think UndefOr is a lot closer to the `?` from typescript, which still keeps it around despite having a union type. There might be some really pragmatic reasons they made that decision.

I do think that it would probably be desirable to add an implicit back and forth between them, or worst case an explicit cast method added via an implicit class.

**Comment by guersam** [comment]
I see, thanks for clarifying. Actually I don't spend that much time handling `UndefOr` manually, and the it's similarity with `Option` is easy to understand.

**Comment by sjrd** [comment]
Updated the title and description with `|`.

@benjaminjackman TypeScript's `?` is different from our `UndefOr`. It indicates *optionality*, which is different from being either `A` or `undefined`. For example, they can use `?` with methods, or with parameters. Also, a missing field is not exactly the same as a field whose value is `undefined`, even if, often, the difference is not meaningful.

**Comment by godenji** [comment]
> Or is so far the preference of godenji only

@sjrd I'm totally fine with `|`, `Or` was just a reaction to `\/` :smile:

**Comment by benjaminjackman** [comment]
Yes I understand, when I was messing around with making an `?` operator for the writing facades (which was supplanted by js.UndefOr)  I was porting that had lots of optional fields `?` was to overcome difficulty in expressing types similar to the ones from this [stack overflow post](http://stackoverflow.com/questions/17220114/how-to-declare-a-type-as-nullable-in-typescript/17220359#17220359)

e.g.:
```
interface Employee2 {
    name: string;
    salary?: number;
}
```

which in ScalaJS becomes

```
trait Employee2 extends js.Object {
    var name: String = js.native
    var salary: UndefOr[Double]  = js.native
}
```

so you can see, atleast in this example, `UndefOr` is filling the same role as `?`, and even with unions allowing for this:
```
trait Employee2 extends js.Object {
    var name: String = js.native
    var salary: Double | Undefined  = js.native
}
```

I think they are orthogonal concepts, `js.UndefOr` means the field might not even be there, whereas `Double | Undefined` means it will be there but it might be set to `Undefined`, However note that in the normal typescript type system all types A actually imply A | null.type | undefined.type, so writing something like String | Undefined simplifies just to String.

The other use of ? is for optional parameters to functions, now for functions in facades we use the whole `def name(x: String = ???)` method for marking arguments as being optional vs the  `name(x?: string)` used in typescript. After thinking about it for a bit just now, I actually prefer the ScalaJS way, with the caveat, rather than use ??? when making facades we include what native javascript is going use there for documentation purposes. So if `x` in `def name` defaults to `"anonymous"` we should attempt to include that in the facade i.e. `def name(x: String="anonymous")` I don't think that typescript offers a way to do this in there `.d.ts` facades but I might be mistaken.

**Comment by sjrd** [comment]
> `js.UndefOr` means the field might not even be there

No, `js.UndefOr[A]` means the value is undefined or `A`. We *abuse* that for fields that might not even be there, but that's not its initial meaning.

In theory we would need an `@js.optional` annotation for fields that might not be there at all.

**Comment by benjaminjackman** [comment]
Interesting, everyone who has been writing facades has been encoding them using `UndefOr` in this fashion. Personally I haven't found much of a use for the construct outside of that. It's why I had previously added my own versions I called alternatively `Optional` and `?` , which I have been replacing with `UndefOr` as I upgrade older codebases. I guess I was abusing the language and I didn't even know it.

Just curious what are some of the use cases you have seen in the wild where it is being used properly?

BTW: I don't like the @js.optional annotation, because I want the type system to guarantee that I check if the field is undefined. Having it be a type gives me all sort of nice sugar methods like .toOption that then let me bring the normal 'this may not be missing but check first' guns to bear, it also lets other people add even more of their extension when those fields pop up in facades via implicits.

All this aside, because it probably belong in a separate pull request about fixing all the abuse js.UndefOr has been subjected to by the community, did you have any thoughts on my implementations / comments wrt to the Union type?

**Comment by sjrd** [comment]
*If* we introduced `js.optional` (but that's an entirely different discussion), then it would only be applicable if the variable also has an `UndefOr` type. But anyway.

> Just curious what are some of the use cases you have seen in the wild where it is being used properly?

As the result type of a method that returns `undefined` in some cases, for example.
But don't get me wrong: it's perfectly normal to also use `UndefOr` for optional fields, because we don't have anything better. But in theory, TypeScript's `?` is better than `UndefOr` for that, because it's semantically correct, whereas `UndefOr` is "only" behaviorally correct.

> did you have any thoughts on my implementations / comments wrt to the Union type?

Hum, not necessarily. I mean it's OK. It's just not as complete as the implementation I propose in #1826. Here are a few examples of its limitations wrt. my implem:

* Arbitrary limit at 4 base types
* Cannot convert `A | B` to `B | A`
* Cannot convert `A | C` to `A | B | C`

What kind of comments were you expecting?

**Comment by benjaminjackman** [comment]
Ok that makes sense, the restriction that js.optional would be used in conjunction with UndefOr types wasn't obvious to me.

A | B != B | A is a deal breaker limitation but I think that can likely be worked around with another set of implicits. Eventually it's going to be a big pile of auto-generated implicits, which the method you propose avoids. However both implementations seems to lack exhaustiveness checking for match expressions.

BTW The limit to 4 was just because I stopped generating examples by hand, I think some thought should be given to seeing how badly the IDE's start performing if there is a lot of recursion going on, a lot of the typelevel stuff historically has made the IDE unresponsive for me when the types get too recursive. I'm really concerned about making sure that any solution plays well with the IDE's in terms of both performance and code completion especially when people have added potentially dozens of facade classes to their project.

Did you have any ideas on exhaustiveness in match checking?  It turns out to be really important that if you start using these things that this:

`def foo() : Int | String`

when used here:

```
foo() match {
  case x : Int =>
}
```

Gives a non-exhaustive match warning. I say this from quite a bit of experience in trying to use these things. The lack of match checks is the deal breaker that forces a fallback to the sealed trait pattern.

However, even If given an implentation without match-checking, this still has a lot of use for facades. Combing with  trait/classes/objects in objects that are js.Objects, I think I can get the scala-js-ts-converter 99% of the way there & If scala had [literal-based singleton types](http://docs.scala-lang.org/sips/pending/42.type.html) then I think I could get that to 100% of what I have seen in the wild in d.ts. files.

**Comment by sjrd** [comment]
> However both implementations seems to lack exhaustiveness checking for match expressions.

I think it's just impossible to get exhaustiveness checking given the current state of Scala's type system. Exhaustiveness checks is very much baked into the pattern matching typing logic, and bound to subtyping and sealed types. It just can't understand any implicit-based "encoding" of union types.

To get that, you need true union types in the type system.

The point of `js.|` is *not* to give a general purpose union type for general Scala code. It's there as something reasonably useful in the context of typing JS facades that take parameters of different types. In general Scala code, yes, you would use a `sealed trait` pattern. But in JS facades you just *can't* use that pattern, because you have to stick to unboxed types as required by JS.

> I think some thought should be given to seeing how badly the IDE's start performing if there is a lot of recursion going on, a lot of the typelevel stuff historically has made the IDE unresponsive for me when the types get too recursive.

While writing my test cases, Eclipse managed to typecheck pretty much on the fly as I wrote. So I'm not worried about that.

**Comment by benjaminjackman** [comment]
Ok that makes sense is what I was expecting to hear, I just want to make sure that the solution won't conflict fundamentally with one that does in the future if Scala gets one (which it really really really should) because if Scala does get one, exhaustiveness of match checking is the most important feature and biggest reason to add it to the language rather than as a library solution (another is avoiding the nightmare of conflicts if something like option was not in the standard library). 

In terms of ScalaJS I agree the top priority is the low hanging fruit that gets facades better able to model javascript. I just want to make sure we don't do anything silly that we will have to break in the future when Scala (hopefully) gets Union types.
