### ISSUE TITLE
quasiquotes ?

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-js/scala-js#1846]
Sometime, I just want to copy paste some javascript in my scala code. It would be helpfull to have something like this:

```scala
def someCode: Unit =  
  js"""couple
        lines
        of
        javascript"""
```

and maybe something like:

```scala
def twice(a: String): String = js"$a.repeat(2)"
```

Concrete example.

I was working on a PageDown hook, see https://code.google.com/p/pagedown/wiki/PageDown. I wanted to try the following function:

```javascript
   converter.hooks.chain("preBlockGamut", function (text, runBlockGamut) {
        return text.replace(/^ {0,3}``` *\n((?:.*?\n)+?) {0,3}``` *$/gm, function (whole, inner) {
            return "<blockquote>" + runBlockGamut(inner) + "</blockquote>\n";
        });
    });
```

It's not trivial to reimplement in scalajs. I would like to have something like:

```scala
trait MarkdownConverter extends js.Object {
  def makeHtml(value: String): String = js.native
  def addHook = js"""
   $this.hooks.chain("preBlockGamut", function (text, runBlockGamut) {
        return text.replace(/^ {0,3}``` *\n((?:.*?\n)+?) {0,3}``` *$/gm, function (whole, inner) {
            return "<blockquote>" + runBlockGamut(inner) + "</blockquote>\n";
        });
    });
  """
}
```
the compiler should not complain about `hooks` not been defined on MarkDownConverter but simply copy paste that javascript and replace the variable `$this` when translated to javascript.

Currently I have to do the following:
add the following code to a page
```javascript
function preBlockGamutHook(converter) {
  converter.hooks.chain("preBlockGamut", function (text, runBlockGamut) {
    return text.replace(/^ {0,3}``` *\n((?:.*?\n)+?) {0,3}``` *$/gm, function (whole, inner) {
        return "<blockquote>" + runBlockGamut(inner) + "</blockquote>\n";
    });
  });
}
```

add this wrapper:

```scala
object MarkdownHookHelper extends js.GlobalScope {
  def preBlockGamutHook(converter: MarkdownConverter): Unit = js.native
}
```

**Comment by sjrd** [comment]
We won't do this. In Scala.js, we deliberately refuse to do anything like that. This breaks all the abstractions that the compiler and the optimizer can use. Other languages compiling to JS offer such a "feature" because they lack enough *sane* interop features *not* to offer it as a workaround.

In Scala.js you can do this:
```scala
val converter: js.Dynamic = ???
converter.hooks.chain("preBlockGamut", { (text: js.Dynamic, runBlockGamut: js.Dynamic) =>
  text.replace(new js.RegExp(raw"""^ {0,3}``` *\n((?:.*?\n)+?) {0,3}``` *$""", "gm"), {
    (whole: js.Dynamic, inner: js.Dynamic) =>
      "<blockquote>" + runBlockGamut(inner) + "</blockquote>\n"
  })
})
```
I spent 2 minutes adapting the syntax (in place). And for this work I gained the benefits of sane scoping, direct interop with the surrounding Scala code, and when reading this code, I don't have to context-switch between Scala syntax and JS syntax.

Also see this StackOverflow question: [How to embed javascript code directly in scala.js?](http://stackoverflow.com/questions/28656170/how-to-embed-javascript-code-directly-in-scala-js)

**Comment by gzm0** [comment]
@sjrd I do not fully agree with you reasoning (but with your conclusion). It is absolutely feasible (but hard) to implement js quasiquotes using macros.

This of course goes far beyond just copy-pasting code together. The macro would need a fully-fledged JavaScript parser that could translate the code to Scala.js style code (this translation is easy, what is hard is the parsing).

Whether or not this is worth the effort (I doubt it), is one question. In any case, this should not be in the Scala.js core, since it is completely independent of it (and our dynamically typed interop is sufficiently stable to separate it out).

@MasseGuillaume hope that sheds some more light on this.

**Comment by lihaoyi** [comment]
Parsing Javascript isn't that hard. It's less than 10 lines of code:
```scala
libraryDependencies +=  "com.google.javascript" % "closure-compiler" % "v20140730"
```
```scala
import com.google.javascript.jscomp.SourceFile
import com.google.javascript.jscomp.parsing.{Config, ParserRunner}
import com.google.javascript.rhino.{SimpleErrorReporter, Token}
val res = ParserRunner.parse(
  new SourceFile(script.toString),
  fileContents,
  ParserRunner.createConfig(true, Config.LanguageMode.ECMASCRIPT6, true),
  new SimpleErrorReporter
)
```

I also don't see why we'd need to parse/translate the code at all; all we'd need to do is splat the Javascript in-line and make sure that interpolations are handled correctly, and maybe sanitize stuff to avoid collisions.

You could even implement Python/Ruby quasiquotes too using Jython/JRuby; that would be cool, and is something I have a use for, but overall this might be outside the scope of Scala.js.

**Comment by gzm0** [comment]
> Parsing Javascript isn't that hard.

Note that the parser will need to support holes for splicing.

> I also don't see why we'd need to parse/translate the code at all

I absolutely agree with @sjrd that we should not allow for a arbitrary JavaScript node in our trees. Quasiquotes like that should be sugar if anything. Also, parsing is probably necessary for reasonable splicing.

**Comment by sjrd** [comment]
> I also don't see why we'd need to parse/translate the code at all; all we'd need to do is splat the Javascript in-line and make sure that interpolations are handled correctly, and maybe sanitize stuff to avoid collisions.

But you *can't* sanitize stuff if you don't parse and do some sort of binding analysis. Your JS code is likely to access global variables which are free in the JS code. But the compiler could use the same names for its internal, which would therefore short-circuit the references to global variables. So depending on how the compiler translates stuff, your code will behave differently. This is the worst possible ever way to compile anything.

> The macro would need a fully-fledged JavaScript parser that could translate the code to Scala.js style code (this translation is easy, what is hard is the parsing).

The translation is not easy. There are even stuff that we *cannot* translate faithfully (e.g., `for-in`, `==`, `with`).

If anything, one could define some simple sugar over `js.Function(...).apply(...)`:
```scala
def injectEval(captures: (String, Any)*)(body: String): Any = {
  val (captureNames, captureValues) = captures.unzip
  val f = js.Function(captureNames :+ body: _*)
  f.asInstanceOf[js.Dynamic].apply(captureValues.asInstanceOf[Seq[js.Any]]: _*)
}
```
and then you can do this:
```scala
injectEval("converter" -> converter)("""
  converter.hooks.chain("preBlockGamut", function (text, runBlockGamut) {
    return text.replace(/^ {0,3}``` *\n((?:.*?\n)+?) {0,3}``` *$/gm, function (whole, inner) {
      return "<blockquote>" + runBlockGamut(inner) + "</blockquote>\n";
    });
  });
""")
```
Note that this will necessarily be executed in the context of the *global scope*, so the JS code cannot refer to variables declared lexically around the call to `injectEval`. That's why there is an explicit list of captures.

A string interpolator could infer the captures from the interpolated expressions, by generating UUID names for the local names of the captures. It doesn't even need to be a macro, I think.

All of this can be done in user space. There's no need for the compiler to do anything. So it doesn't need to be in core. And I think this is extremely bad style for Scala.js, so it shouldn't be in core.
