### ISSUE TITLE
fastOptJS isn't fast

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1860]
When working on my main project, I often run `~fastOptJS` with my webserver running and want to see my changes in browser ASAP. `fastOptJS` is the fastest available option but takes around 15sec in my case. My PC is fast but the module is 18k LoC excluding 3rd-party libraries, output JS size is 14.3MB. Oh and all the SBT target dirs write to `/tmp` = RAM.

Waiting 15-20 sec per change is annoying. I understand we in the community with large ScalaJS are probably the minority. Maybe I can investigate and contribute some patches to speed things up?

Before I even start looking, can you please inform me better. How much work has been done in this area? Do you think there'd be value in me profiling `fastOptJS` and naively looking for hotspots? Any suggestions?

**Comment by sjrd** [comment]
The first thing to look at its what big step is slow. You can see that with `last`.

If it's the Optimizer part, you could disable the optimizer entirely for `fastOptJS` with
```scala
scalaJSOptimizerOptions in fastOptJS ~= { _.withDisableOptimizer(true) }

scalaJSOptimizerOptions in fullOptJS ~= { _.withDisableOptimizer(false) }
```
If it's the linker, there is a major improvement coming in 0.6.5 already https://github.com/scala-js/scala-js/pull/1835

Otherwise, there is no immediate fix, and we need to start profiling and see what we can do about it.

**Comment by japgolly** [comment]
That's helpful, thanks.

* The inc optimiser time is tiny (30ms) but disabling it also disables Refiner which makes more of a difference. 
* The fix in #1835 is welcome, it's by far the largest at around 3 full sec.
* `Emitter (write output)` is suspiciously slow seeing as it's writing to RAM or at SSD-backed swap - between 1 and 3 full sec. That time halves if I disable source maps.

Over the next week I'll see if I can get some time in to profile and play. Will report back here with any findings.

**Comment by ngbinh** [comment]
Looks like https://github.com/scala-js/scala-js/issues/1788

**Comment by sjrd** [comment]
@ngbinh I don't think so. In #1788 the OptimizerCore takes a lot of time, but @japgolly says the optimizer part is fast in this issue.

**Comment by japgolly** [comment]
Gave 0.6.5-SNAPSHOT a try. It's definitely fast but I must confess I was hoping for more of a reduction to `Linker: Assemble LinkedClasses`.

Here's a "clean" `fastOptJS` (specifically `rm fastopt.js`, `sbt`, `fastOptJS`)
```
```

**Comment by japgolly** [comment]
Gave 0.6.5-SNAPSHOT a try. It's definitely fast but I must confess I was hoping for more of a reduction to `Linker: Assemble LinkedClasses`.

Here's a "clean" `fastOptJS` (specifically `rm fastopt.js`, `sbt`, `fastOptJS`)
```
0.6.4 (clean)

[debug] Linker: Read info: 581682 us
[debug] Linker: Compute reachability: 1384101 us
[debug] Linker: Assemble LinkedClasses: 3188923 us
[debug] Linker: cache stats: reused: 0 -- invalidated: 16436 -- trees read: 4602
[debug] Linker: 5171614 us
[debug] Inc. optimizer: Batch mode: true
[debug] Inc. optimizer: Incremental part: 357836 us
[debug] Inc. optimizer: Optimizing 28915 methods.
[debug] Inc. optimizer: Optimizer part: 8703602 us
[debug] Inc. optimizer: 9109152 us
[debug] Refiner: Compute reachability: 877746 us
[debug] Refiner: Assemble LinkedClasses: 46440 us
[debug] Refiner: 925496 us
[debug] Emitter: Class tree cache stats: reused: 0 -- invalidated: 3848
[debug] Emitter: Method tree cache stats: resued: 0 -- invalidated: 19218
[debug] Emitter (write output): 3136375 us

0.6.5-SNAPSHOT (clean)

[debug] Linker: Read info: 531299 us
[debug] Linker: Compute reachability: 1210282 us
[debug] Linker: Assemble LinkedClasses: 1263524 us
[debug] Linker: cache stats: reused: 0 -- invalidated: 16489 -- trees read: 4602
[debug] Linker: 3023186 us
[debug] Inc. optimizer: Batch mode: true
[debug] Inc. optimizer: Incremental part: 410475 us
[debug] Inc. optimizer: Optimizing 28930 methods.
[debug] Inc. optimizer: Optimizer part: 9286452 us
[debug] Inc. optimizer: 9740633 us
[debug] Refiner: Compute reachability: 534482 us
[debug] Refiner: Assemble LinkedClasses: 44087 us
[debug] Refiner: 579604 us
[debug] Emitter: Class tree cache stats: reused: 0 -- invalidated: 3848
[debug] Emitter: Method tree cache stats: resued: 0 -- invalidated: 19226
[debug] Emitter (write output): 2856600 us
```

And here's the result of changing a string literal in code and hitting `fastOptJS` again in the same SBT session.
```
0.6.4 (after Literal(Constant(String)) change)

[debug] Linker: Read info: 34322 us
[debug] Linker: Compute reachability: 1020146 us
[debug] Linker: Assemble LinkedClasses: 1730751 us
[debug] Linker: cache stats: reused: 16418 -- invalidated: 18 -- trees read: 8
[debug] Linker: 2793049 us
[debug] Inc. optimizer: Batch mode: false
[debug] Inc. optimizer: Incremental part: 107875 us
[debug] Inc. optimizer: Optimizing 1 methods.
[debug] Inc. optimizer: Optimizer part: 23790 us
[debug] Inc. optimizer: 146591 us
[debug] Refiner: Compute reachability: 678761 us
[debug] Refiner: Assemble LinkedClasses: 20470 us
[debug] Refiner: 699365 us
[debug] Emitter: Class tree cache stats: reused: 3840 -- invalidated: 8
[debug] Emitter: Method tree cache stats: resued: 19217 -- invalidated: 1
[debug] Emitter (write output): 772447 us

0.6.5-SNAPSHOT (after Literal(Constant(String)) change)

[debug] Linker: Read info: 66331 us
[debug] Linker: Compute reachability: 824158 us
[debug] Linker: Assemble LinkedClasses: 214325 us
[debug] Linker: cache stats: reused: 16471 -- invalidated: 18 -- trees read: 8
[debug] Linker: 1113410 us
[debug] Inc. optimizer: Batch mode: false
[debug] Inc. optimizer: Incremental part: 117874 us
[debug] Inc. optimizer: Optimizing 1 methods.
[debug] Inc. optimizer: Optimizer part: 17945 us
[debug] Inc. optimizer: 157594 us
[debug] Refiner: Compute reachability: 594897 us
[debug] Refiner: Assemble LinkedClasses: 27323 us
[debug] Refiner: 622367 us
[debug] Emitter: Class tree cache stats: reused: 3840 -- invalidated: 8
[debug] Emitter: Method tree cache stats: resued: 19225 -- invalidated: 1
[debug] Emitter (write output): 709143 us
```

I also profiled, tried some optimisation to Analyzer and managed to consistently slow it down. :S

**Comment by sjrd** [comment]
When clean, it doesn't surprise me that Assemble would take more time, because it then has to read the full trees (i.e., the full .sjsir files) of all the classes that are needed. Read info only reads a tiny portion in the beginning of each .sjsir file, which contains just the information necessary for Compute reachability. So in clean you should compare Assemble vs (Read info + Compute reachability), because Assemble also contains its I/O part, where as the I/O part of Reachability is actually Read info.

In general, we're not very good on clean times, and don't really strive to improve that either. We mostly try to improve incremental timings.

Compute reachability, i.e., `Analyzer`, is one big aspect for which we don't have any incremental behavior, so it does that part from scratch every time, and the clean and incremental scenarios behave similarly. I don't think it can really be improved; I hope to be able to incrementalize it at some point.

Another part is Emitter (write output), which has to do everything from scratch every time. Note that this is not only writing to disk, but also *printing* the `js.Trees` to JavaScript source code, i.e., the code in [`javascript.Printers`](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/javascript/Printers.scala). That code was not written for performance. Maybe there is something to gained over there.

**Comment by japgolly** [comment]
Cool, thanks for that info. Shall I close this or would you like to keep it around?

**Comment by sjrd** [comment]
I'll keep it around to remind me of the Emitter, for now.

**Comment by sjrd** [comment]
> I'll keep it around to remind me of the Emitter, for now.

I moved that bit to #1866.

**Comment by japgolly** [comment]
:+1:
