### ISSUE TITLE
document.querySelector doesn't work in tests (using RuntimeDOM)

### ISSUE THREAD

**Issue by bandrzejczak** [scala-js/scala-js#1873]
`document.querySelector(...)` works absolutely fine in scala-js when you run it in the browser, unfortunately it fails miserably in tests. Here is a code example triggering the error:

```scala
dom.document.querySelector("body")
```

And here is the error itself:

```
TypeError: Cannot find function querySelector in object [object HTMLDocument].
```

**Comment by sjrd** [comment]
If it's not supported by env.js, there's nothing we can do. You should switch to using PhantomJS (with `scalaJSStage in Global := FastOptStage`) for your testing.

**Comment by bandrzejczak** [comment]
Switching to PhantomJS actually works, but I'll have to make it a prerequisite for application testing, which isn't a desired behaviour.

Either way, should I open this issue in some other project? I though, that adding RuntimeDOM to the dependencies automatically makes tests run in PhantomJS. If it's not so, what does the test run in? Regular node.js? In which project does env.js lay?

**Comment by sjrd** [comment]
By default Scala.js uses Rhino, with [env.js](https://github.com/thatcher/env-js). The project appears to be dead, but it's still the best option to sort of run DOM within Rhino.

For any serious work, though, people use Node.js when they don't need DOM, and PhantomJS otherwise. Those are used by default with `scalaJSStage in Global := FastOptStage`.

[More info in the docs](http://www.scala-js.org/doc/sbt/js-envs.html)

**Comment by bandrzejczak** [comment]
I'm closing the issue, as there's nothing to do in scala-js.

Thank you for the clarification.
