### ISSUE TITLE
 js.constructor - support for dynamic types/classes 

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#1894]
> sjrd :  No you have to call js.constructorOf where you know the class statically. It does not work through java.lang.Class (that would be reflection).

**Comment by sjrd** [comment]
So, first I need to explain why it does not work now. The problem is that `js.constructorOf[C]` needs to generate a *static* reference to `C`, so that the linker knows that `C` can be instantiated. Otherwise, the linker would be allowed to dead-code-eliminate away `C`, which is not good.

Now, to get access to the `js.constructorOf[C]` out of a `Class[C]`, we need the `Class[C]` to store a reference to that constructor, which then means that the linker must retain `C` as soon as there *might* be a `Class[C]` in the program.

Fortunately, the linker has a reasonably good tracking of what `Class[C]`'s can exist in the program. Of course, as soon as you have `classOf[C]` (or `classTag[C]` for that matter), then `Class[C]` can exist. For Scala classes, it is annoying to declare reachable any class for which a `Class[C]` exists. But for JS classes, it might be OK.

It's even more OK if we condition this to the existence of a call to whatever primitive method we make available, let's say:
```scala
def constructorOf(clazz: Class[_ <: js.Any]): js.Dynamic
```
If that method is never called in the program, we don't need to make `C` instantiable only because `ClassOf[C]` is reachable.

Of course, unlike `js.constructorOf[C]`, which does not compile if `C` is not a *class*, that alternative would throw at runtime.

I think this would be doable and reasonable.

**Comment by gzm0** [comment]
This is essentially allowing to call `newInstance` on any instance of `Class[T]` where `T` is a SJS defined class. Shouldn't we protect this by the same reflection mechanisms as for normal classes?

**Comment by sjrd** [comment]
It has the same consequences on reachability. But it's not the same; it is strictly superior, since you can also get the constructor precisely *without* calling it (just like `js.constructorOf[C]` itself is strictly superior than `new C(...)`.

That said, it is similar to runtime reflection, yes. I have not made my mind up yet.
I actually thought that maybe @chandu0101's use case can be fulfilled with an implicit macro instead. That macro would basically materialize a `js.constructorOf[C]`. The signature would be something like:
```scala
class JSConstructor[C <: js.Any](val ctor: js.Dynamic) extends AnyVal

object JSConstructor {
  implicit def materialize[C <: js.Any : WeakTypeTag]: JSConstructor[C] = macro ...
}
```
to be used as
```scala
def somethingRequiringAJSConstructor[C <: js.Any]()(implicit ctor: JSConstructor[C]) = ...
```
@chandu0101 WDYT?

**Comment by chandu0101** [comment]
that will work fine i think , to make sure i understand fully ,  my use case will be written as ...

```scala
def getFactory[C <: JSClass[T])()(implicit jctor : JSConstructor[C]) = createFactory(jctor.ctor).asInstanceOf[FactoryDynamic[T]]

getFactory[SJSClass] // end user call
```

right ?

**Comment by sjrd** [comment]
It would be something like that, yes.

**Comment by sjrd** [comment]
> ok i am confused here in above case end user must pass type T :( 

That is a different problem, which has nothing to do with using reflection vs using a compile-time macro. It's a type inference problem. You'll have to play with the arrangements of type parameters and abstract type members until you get what you cant.

**Comment by chandu0101** [comment]
apologies for not being clear on type T

u r solution work here too 

```scala
def getFactory[C <: JSClass[T],T)(clz : Class[_ <: JSClass[T])(implicit jctor : JSConstructor[C]) = createFactory(jctor.ctor).asInstanceOf[FactoryDynamic[T]]

```

end user call 

```scala
getFactory[SJSClass](classOf[SJSClass]) 
```
enduser call for my current implementation is 

```scala
getFactory(js.Constructor[SJSClass], classOf[SJSClass])
```

new enduser call  doesn't look nice for my use case ( we're passing same class two times) .

**Comment by sjrd** [comment]
This typechecks and requires only `getFactory[SJSClass]`:
http://www.scala-js-fiddle.com/gist/be82be9a446c403dedd2

Going in that direction, I would even recommend this, where `ResultType` is *only* a type member (and not a parameter):
http://www.scala-js-fiddle.com/gist/f4311de7932adfbe457c

**Comment by chandu0101** [comment]
excellent thank you :)

**Comment by sjrd** [comment]
OK my proposal is to have a `js.ConstructorTag[C <: js.Any]` in the std lib, in the same spirit as `scala.reflect.ClassTag[C]`:
```scala
@implicitNotFound(msg = "No ConstructorTag available for ${C}")
final class ConstructorTag[C <: js.Any] private (
    val constructor: js.Dynamic) extends AnyVal {

  @inline
  def newInstance(args: Any*): C =
    js.Dynamic.newInstance(constructor)(args.asInstanceOf[Seq[js.Any]]: _*).asInstanceOf[C]
}

object ConstructorTag {
  implicit def materialize[C <: js.Any]: ConstructorTag[C] = macro ...
}

package object js {
  def constructorTag[C <: js.Any : ConstructorTag]: ConstructorTag[C] =
    implicitly[ConstructorTag[C]]
}
```
Since the constructor is private, it is impossible to create a `ConstructorTag[C]` that does not actually return a `C` (without casts, of course), so `newInstance` can safely return a `C`, which is an added value compared to directly using the inner `constructor`.
