### ISSUE TITLE
Some members of new js.Object {...} are not visible from JavaScript

### ISSUE THREAD

**Issue by bbarker** [scala-js/scala-js#1899]
See the following change to the example project to reproduce the bug https://github.com/bbarker/scala-js-example-app/commit/23abe08739188a7cb99d18c5d183fa2bce008e10

In particular, note the difference in behavior depending on which `def getObj():...` is commented out.

**Comment by sjrd** [comment]
Oh ow ... That looks like a very strange behavior from scalac that I would qualify as a bug. The scalac typechecker gives the following code for your `new js.Object` (can be printed by adding `scalacOptions += "-Xprint:typer"` in build.sbt):
```scala
    @scala.scalajs.js.annotation.JSExport def getObj(): scala.scalajs.js.Object = {
      final class $anon extends scala.scalajs.js.Object {
        def <init>(): <$anon: scala.scalajs.js.Object> = {
          $anon.super.<init>();
          ()
        };
        private[this] val square: scala.scalajs.js.Function1[Int,Int] = ScalaJSExample.this.squareJS;
        <stable> <accessor> private def square: scala.scalajs.js.Function1[Int,Int] = $anon.this.square
      };
      new $anon()
    }
```
in which we can see that the `def square` accessor method is *private*, for some reason! Logically, Scala.js then hides it from JS.

The funny thing is, if we hide the expected type from the typechecker, for example with
```scala
  @JSExport
  def getObj(): js.Object = {
    val o = new js.Object{val square = squareJS}
    o
  }
```
or even
```scala
  @JSExport
  def getObj(): js.Object = {
    new js.Object{val square = squareJS}.asInstanceOf[js.Object]
  }
```
then we get
```scala
    @scala.scalajs.js.annotation.JSExport def getObj(): scala.scalajs.js.Object = {
      val o: scala.scalajs.js.Object{val square: scala.scalajs.js.Function1[Int,Int]} = {
        final class $anon extends scala.scalajs.js.Object {
          def <init>(): <$anon: scala.scalajs.js.Object> = {
            $anon.super.<init>();
            ()
          };
          private[this] val square: scala.scalajs.js.Function1[Int,Int] = ScalaJSExample.this.squareJS;
          <stable> <accessor> def square: scala.scalajs.js.Function1[Int,Int] = $anon.this.square
        };
        new $anon()
      };
      o
    }
```
in which `def square` is public, and therefore everything works well.

Definitely looks like a scalac typer bug to me. I don't think we can do anything about it.

Workarounds:
* Hide the expected type as I showed above (clunky), or
* Define a `@ScalaJSDefined trait Foobar extends js.Object` declaring the interface you want to expose to JS, and use `new Foobar {}` instead of `new js.Object {}` (better, IMO)

**Comment by gzm0** [comment]
Hahahaha, this is one of the more epic fails of scalac I have seen... And I have seen quite some :P

**Comment by bbarker** [comment]
Thanks for the suggestions! I think I'll just use `lit` if I'm tempted to use the first suggestion, or use the `@ScalaJSDefined trait` for larger or more pervasive objects. 

Just curious, is there an issue for the scalac bug?

**Comment by sjrd** [comment]
I haven't searched for a potential existing issue in scalac yet.

**Comment by nicolasstucki** [comment]
Created a new issue for scala. https://issues.scala-lang.org/browse/SI-9487

**Comment by nicolasstucki** [comment]
Who should I assign to the issue?

**Comment by sjrd** [comment]
It appears to be completely impossible to disambiguate genuine private members from bugged private members after `typer`.

We *could*, in theory, have a pre-typer phase that would add a dedicated annotation on public members so that we can recover them later. However, being pre-typer, we would have to do that to *all* members of *all* anonymous classes, which is a huge impact on the trees.

Instead, we propose the following:
* Fix the scalac bug for 2.12, if at all possible
* In PrepJSInterop, expose *all* `private` members of anonymous classes extending `js.Any` (but not `private[this]` nor `private[Scope]` members).
* Document that, due to a scalac bug in 2.10/2.11 (or all versions if we can't fix the scalac bug), `private` members of anonymous classes extending `js.Any` will become public. Document the workaround which is to use `private[this]` instead.

**Comment by nicolasstucki** [comment]
It seems that in this specific context we can't have `private[Scope]` members because they are not final:
`Qualified private members in Scala.js-defined JS classes must be final.`

**Comment by sjrd** [comment]
And can't we have a `final private[Scope]`?

**Comment by gzm0** [comment]
> However, being pre-typer, we would have to do that to all members of all anonymous classes, which is a huge impact on the trees.

How big is this impact really? Could we try and measure the scalalib compilation times with it just to get a ballpark estimate?

I'm really scared of having different behavior for 2.11 / 2.12... Also I think before we decide anything, we need to assess whether the scalac side is actually fixable.

**Comment by sjrd** [comment]
> I'm really scared of having different behavior for 2.11 / 2.12...

We already have *plenty* of different behavior on different Scala versions, although so far there has been no behavior difference dictated by an explicit *test*. The best example is how lambdas are transformed and compiled: it's done completely differently between 2.10/2.11 without -Xexperimental versus 2.11 with it/2.12. It'll also be crazier still when 2.12 starts emitting default methods. This is all part of the game.

We also already have workarounds that are only relevant to earlier versions of Scala, e.g., the `x` field of `js.Dynamic` and the magic to recreate `applyDynamic` for them.

It doesn't seem like this instance would be any worse than things we've done before, would it?

**Comment by gzm0** [comment]
Well, different behavior in terms of implementation details is fine. But not in terms of user visible behavior.

Loosely phrased: If you don't do anything "crazy", changing the Scala version should not change anything (especially in terms of JS interop). People just don't expect it.

For example, if you rely on a specific translation of a Scala construct, you are in unspecified behavior land anyways, so even between minor Scala.js versions this could change. But if you rely on a field being present on a Scala.js defined class you are doing something very reasonable and very common. This is in itself not a problem yet. But if -- for example -- you iterate over the fields of an object in JS, you are still doing something pretty reasonable and more importantly something common. Now if that changes behavior depending on whether you compile with 2.11 or 2.12, you really are going to hate the tool you are using (irrespective of whether it is written in some release notes that this actually happens).

Hope that makes sense...

**Comment by sjrd** [comment]
Yes, that makes perfect sense.

But so behave *all* compiler bugs. There is *already* a bug in scalac, and the one that exists right now is greatly annoying because

1. Fields that you expect to be there are actually not there
2. Explaining *when* this bug happens is impossible without talking about *expected types* in scalac, a concept few people understand
3. The workaround for the bug is very obscure (hiding the expected type)

The idea, here, is to *transform* this very obscure bug into a clearly understandable bug with less bad behavior:

1. Fields that you expect *not* to be there are actually there (only a problem if you iterate; which is common, but less common than using the fields, which is all the time)
2. Explaining *when* it happens is very easy: `private` member in anonymous class extending `js.Any`
3. The workaround is extremely clear: make it `private[this]`

We're transforming a very bad bug into a slightly bad bug, basically. Of course, on a version of Scala that does not have the bug in the first place, we don't want to introduce a bug for nothing.

That's my rationale. Hope that makes sense ... ^^

**Comment by gzm0** [comment]
Ok. I can agree with that, as long we treat it as a bug. But I still think it'd be a good idea if someone had a look at the performance impact of a pre-typer plugin. And we definitely need to see whether the bug is fixable in 2.12 (especially whether the change of semantics will even get accepted!).
