### ISSUE TITLE
Add -Xfatal-warnings even for scaladoc generation

### ISSUE THREAD

**Issue by oleastre** [scala-js/scala-js#1917]
For some sub-projects, scaladoc generation emit warnings and since #1912 fails.

As a temporary solution #1916 disables fatal warnings for doc compilation.

**Comment by gzm0** [comment]
The main problem here is links to external docs / java doc. They seem to be hard to generate.

Should we:

1. Not have links to JavaDoc (use backquotes instead of `[abc]` for links)
2. Try really hard and maybe get it to work

Opinions?

**Comment by sjrd** [comment]
We should try to make them work. Supposedly there's a semi automatic way to do that, assuming we can get the right sbt config.

**Comment by SethTisue** [comment]
gory details at https://issues.scala-lang.org/browse/SI-9311

**Comment by gzm0** [comment]
Thanks @SethTisue for the pointer. I will drop issues I encounter in here as I go.

**Comment by gzm0** [comment]
First two issues:

### Linking to other Scala.js libraries
External documentation (via `-doc-external-doc` switch or sbt's `apiMapping` builtin) seems to be only linkable if the dependency is in a JAR (specifying a classpath does not work).

Therefore, `exportJars` needs to be set to true.

This is an annoyance but definitely not a complete show stopper.

### Linking to external nested classes

The tools link to the member `ir.Types.ClassType`. The reference to it can be successfully resolved. However, the generated link is wrong: `#org.scalajs.core.ir.Types$.ClassType` instead of `#org.scalajs.core.ir.Types$$ClassType`.

This is probably nothing some relatively sophisticated regex processing can't solve, but it's cumbersome and hard to notice if it fails.

**Comment by gzm0** [comment]
### Linking to some parts of the Scala Library
Cannot link to the following types:
- `scala.Null`
- `scala.util.Left`
- `scala.util.Right`
- `scala.Some` (`scala.None` works, note that it's not a type like all the others)

### Linking to some parts of the Java library
Some low-level stuff seems to not work:

- `java.lang.Runtime.exit`
- `java.lang.String.copyValueOf` (not needed, just for testing)

**Comment by gzm0** [comment]
Filed the linking issues under: #1969
