### ISSUE TITLE
Long division returns incorrect result for Long.MinValue

### ISSUE THREAD

**Issue by ummels** [scala-js/scala-js#1918]
When `Long.MinValue` is divided by a negative number, the result is wrong. For instance, when dividing by `-2`, the result is `4611686018427387903` instead of `4611686018427387904`. Also dividing by `-1` returns `Long.MaxValue` instead of `Long.MinValue`. The following code demonstrates the bug:

```scala
object TestApp extends JSApp {
  def main(): Unit = {
    val x = -2
    val y = Long.MinValue / x
    // Prints wrong result
    println(y)
    // Prints correct result, probably due to compiler optimization
    println(Long.MinValue / -2)
  }
}
```

**Comment by sjrd** [comment]
Thanks for the report. We'll fix that for the next release.

**Comment by sjrd** [comment]
After some investigation, this happens only for *negative powers of 2* (including -1, indeed).

I think that [this line](https://github.com/scala-js/scala-js/blob/v0.6.5/library/src/main/scala/scala/scalajs/runtime/RuntimeLong.scala#L437) should use `absY.powerOfTwo` instead of `y.powerOfTwo`. It looks like the code in the then branch takes `yNegative` into account, so it has probably be written with the case that `y` is actually a negative power of 2.

The `divModHelper` receives `x = MaxValue` instead of `-MinValue`, and that "approximation" (with [the fix by `1` of the remainder at the end](https://github.com/scala-js/scala-js/blob/v0.6.5/library/src/main/scala/scala/scalajs/runtime/RuntimeLong.scala#L514)) is only valid when `y` is not a power of two.

I still have to think more to convince myself that `absY.powerOfTwo` will not break something else, but it's late now, so it'll be for later ^^
