### ISSUE TITLE
.toInt fails, asInstanceOf[String].toInt works

### ISSUE THREAD

**Issue by MikaelMayer** [scala-js/scala-js#1957]
When dealing with JQuery, I have:

    $("select option").value().toInt

which always returns `undefined`
whereas

    $("select option").value()

returns `"2"` (a string).

I figured out that casting to `String` makes the trick, since the output of value() is considered as a js.Dynamic.
Is this unexpected behavior of `.toInt` supposed to be expected?

**Comment by sjrd** [comment]
Yes, it is expected that calling `.toInt` on something typed as `js.Dynamic` won't be any good, since that would mean trying to select a field named `toInt` on the string, which does not exist. You indeed need to cast the `js.Dynamic` to `String` to then be able to call the *Scala* method `.toInt`, which exists and converts a string to an integer.
