### ISSUE TITLE
Dev / Production mode

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1998]
Do we have a means to produce different JS (use different Scala trees) according to configurable compile-time settings? Maybe some args passed through SBT?

Some context:  In Babel there's an optimisation available which they only switch on when making a release: http://babeljs.io/blog/2015/03/31/5.0.0/#inline-elements

I'd like to support it in scalajs-react but I don't have a means of letting users specify dev/prod mode at compile-time. Up until now I've been using `-Xelide-below` and tricks with `@elidable` which work well enough, but I don't think I should use that to support something larger like an optimisation setting.

Any ideas?

**Comment by sjrd** [comment]
It sounds like what you want is to inject custom optimizations in the linker pipeline. We've been thinking about how we could introduce a plugin infrastructure to the linker. With that, you could add a custom phase that would rewrite parts of the IR trees to perform the optimizations you want.

**Comment by gzm0** [comment]
I am working on a refactoring of the linker API. The new one will probably not allow you to do this, but it will be designed with linker plugins in mind.

**Comment by japgolly** [comment]
That sounds a bit more complicated that I was thinking. I was thinking along the lines of something like this:

* Need a way to specify a macro that returns a Literal that is informed from something in SBT. For example, something like `def isDevMode = Expr(Literal(true))`
* In code, use it like a normal condition: `if (isDevMode) treeDev else treeProd`
* The compiler or optimiser will change `if (true) treeDev else treeProd` into just `treeDev` right?

The above would work right? Just need a way to inform the macro. Maybe just reading env vars through scalac. Also not knowing how smart the optimiser is, are there other scenarios that it can optimise and apply DCE to effectively that would help in this situation?

**Comment by gzm0** [comment]
@sjrd we could make this available through linking info... the constant folder would do the rest

**Comment by sjrd** [comment]
It can't be a macro, because a macro happens at *compile* time, but the decision to produce dev mode or prod mode happens at *link* time, which is much later.

The rewriting from true to false (or vice versa) must therefore happen at link time. It could simply be a `def isDevMode: Boolean = true` in your codebase, and the linker plugin would replace that one method by `def isDevMode: Boolean = false` if in prod mode. Then, normal inlining, constant-folding, and DCE inside the optimizer would replace code like `if (isDevMode) treeDev else treeProd` by the appropriate branch.

We have a similar mechanism (but builtin hard-coded for our purpose) for the *semantics* levels. There is code like [`SemanticsUtils`](https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/runtime/SemanticsUtils.scala) that reads `linkingInfo.semantics.asInstanceOfs`, and that thing is constant-folded into 0, 1, or 2 by the optimizer. Then it uses that to constant-fold and dce-away the content of `genericCheck`.

**Comment by japgolly** [comment]
Ah yes, of course a macro wouldn't work in a library. Well, anything you could expose so that users could do a similar thing at link-time would be much appreciated.

**Comment by japgolly** [comment]
Awesome, thank you! :bow:
