### ISSUE TITLE
Tests for OutputStreamWriter fail on JVM when asserting flushed after close.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2050]
Tests were filtered out with `!executingInJVM` when cross-compiling in #2047.

**Comment by sjrd** [comment]
The failing tests are slightly too restrictive. They assert that the `flush()` method of the underlying `ByteArrayOutputStream` has been called, but that is not explicitly necessary. It is possible that its `close()` method has been closed instead, which ought to have flushed it anyway. Our `MockByteArrayOutputStream` is just too stringent about it (so that we can better test other stuff).

Instead, we should test that the bytes have been flushed *in practice*, by inspecting the output buffer, not its `flushed` flag.

**Comment by gzm0** [comment]
Fixed in c8c86a9f32a1074fdab724a6b3b74fff60e67ef7
