### ISSUE TITLE
IE8 Support: scalajsenv should use polyfill for Object.freeze

### ISSUE THREAD

**Issue by spaced** [scala-js/scala-js#2051]
`scalajsenv.js` and `scalajsstrongmodeenv.js` are the only places where `Object.freeze` is called and is not supported by IE8 (http://caniuse.com/#search=freeze) 

> Scala.js assumes ES 5.1, yes. However, the requirement on Object.freeze is not completely necessary. >We could polyfill it as a no-op if it's blocking you from using SJS because you need IE 8 support. Please file an issue. 
> sjrd gitter

Not really a blocker for me, but if this is the only usage we should fix it. (script debugger of my old xp vm was complaining only there)

**Comment by mseddon** [comment]
Certainly doesn't affect me either (I don't really target below IE10 at the moment).  It turns out my previous comment on gitter was wrong- IE8 *does* handle cyclic references (it was IE7 and below did not), but I can still think of some gotchas off the top of my head:

* `Node.textContent` do not work in IE8, it uses the non-standard `Node.innerText`
* `JSON` is unsupported without a polyfill.
* It is *terribly* slow (several orders of magnitude slower than a modern browser)

Dart doesn't target IE8 (and [Google] (http://www.computerworld.com/article/2492571/web-apps/google-to-drop-support-for-ie8-on-nov--15.html) have not supported it for several year or so, either).  Microsoft will end support for IE8 on [January 12, 2016](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=internet%20explorer), less than two months.

My feeling is if this is all that is required to make IE8 work, then sure, why not, it'll only add 20 or so bytes to the runtime but I would be *very* wary of stating official support for a 6 year old browser that only barely conformed to standards when it was released :)

**Comment by sjrd** [comment]
OK let's put this issue as dormant until someone really asks for it. Apparently IE8 supported virtually nothing from ES5.

**Comment by spaced** [comment]
A workaround: use a es5 shim:
```
<!--[if lt IE 9]>
<script src='META-INF/resources/webjars/es5-shim/4.1.14/es5-shim.min.js'>
</script><script src='META-INF/resources/webjars/es5-shim/4.1.14/es5-sham.min.js'></script>
<![endif]-->
```

**Comment by gzm0** [comment]
Just as a note: If we polyfill this, we should also polyfill `isSealed`.

**Comment by gzm0** [comment]
@sjrd, I think we can close this, given no one complained. WDYT?

**Comment by sjrd** [comment]
Agreed.
