### ISSUE TITLE
java.util.concurrent.CopyOnWriteArrayList.subList missing a ConcurrentModificationException.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2064]
java.util.concurrent.CopyOnWriteArrayList.subList is throwing a ConcurrentModificationException in one of the test cases while running on the JVM.

**Comment by sjrd** [comment]
[The Javadoc of `CopyOnWriteArrayList.subList`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html#subList(int,%20int)) say that

> The semantics of the list returned by this method become undefined if the backing list (i.e., this list) is modified in any way other than via the returned list.

Now, this is precisely what happens in [the test that fails](https://github.com/scala-js/scala-js/blob/e74bb0aff8bb3522f0d5954e44ac1ebf8ab80242/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/ListTest.scala#L349-L364), because the backing list of `al0` is modified through `al1`, not through `al0`.

Our implementation happens to survive this, whereas the JVM implementation throws. Both behaviors are correct since it is undefined behavior.

This specific test needs to be excluded for `CopyOnWriteArrayList`s, not for the JVM.

**Comment by gzm0** [comment]
Fixed in 521e28adf80382387ac4fa19702a55e05fd03b07
