### ISSUE TITLE
Better implicits for combinations of js.| and js.UndefOr?

### ISSUE THREAD

**Issue by elacin** [scala-js/scala-js#2067]
while writing javascript facades im frequently coming across things that have types like this:
```scala
value: js.UndefOr[String | js.Array[String]]
```
Scala only applies one level of implicit conversions, so if you pass a plain `String`, you need to hold the compiler in the hand and cast it to `String | js.Array` manually.

Would you be interested in shipping a few implicits for these combinations? i could certainly try to code them up myself, just figured i would ask if you think it's a good idea first

**Comment by chandu0101** [comment]
recently  @xsistens raised same issue in scala.js gitter channel.

***Start of Conversation***

@sjrd is there are way to make Union types working with js.UndefOr types? Since both are implicits and scala only uses one conversion at the time something like this wont work at the moment:
def f(param: |[js.UndefOr[A] | B]): Unit = ???
val a: A = ???
f(a)
you always have to wrap the a when you pass it or define a like this:
val a: js.UndefOr[A] = ???

ochrons Nov 26 20:28
why not js.UndefOr[A | B]?

xsistens Nov 26 20:29
i'm pretty sure it's not working ether
and its semantically not the same as the one above or am I wrong?

sjrd Nov 26 20:31
I would encourage js.UndefOr[A | B], but indeed it probably does not "work" either.
One way to "make it work" would be to use A | B | js.UndefOr[Nothing] (I think)
Otherwise, come up with more implicit magic to make js.UndefOr and | behave better with each other.

xsistens Nov 26 20:33
ok, i give it a shot  just wanted to check if there is already something i was not aware of.

sjrd Nov 26 20:36
Maybe:
implicit def indirectA2undefOrA[A, B](v: B)(implicit ev: B => A): js.UndefOr[A] =
  js.UndefOr.any2undefOrA[A](ev(v))
That might work for js.UndefOr[A | B]

xsistens Nov 26 20:39
implicit def fromWithAllUndefOr[A, B1, B2](a: A)(implicit ev: Evidence[A, B1 | B2]): js.UndefOr[B1 | B2] =
    js.UndefOr.any2undefOrA(a.asInstanceOf[B1 | B2])
this will work for js.UndefOr[A | B]

sjrd Nov 26 20:41
Cool  PR welcome 

xsistens Nov 26 20:42
yours also works for it
what version do you prefer? Yours is more generic and will match more cases i think. My version will only apply to the Union case.

sjrd Nov 26 20:45
Good question. I don't know.
I guess file an issue for now anyway, with the two solutions, and I'll think about it.

xsistens Nov 26 20:46
I always try to be as specific as possible with the implicits so that i dont end up with conflicts between them.
Ok i write an issue for it.

xsistens Nov 26 21:13
@sjrd this solves both cases, js.UndefOr[A | B] as well as [js.UndefOr[A] | B]. Should i make a PR with these two functions and some tests or rather have a discussion in an issue?
implicit def fromWithAllUndefOr[A, B1, B2](a: A)(implicit ev: Evidence[A, B1 | B2]): js.UndefOr[B1 | B2] =
      js.UndefOr.any2undefOrA(a.asInstanceOf[B1 | B2])
implicit def fromWithOneUndefOr[A, B1, B2](a: A)(implicit ev: Evidence[js.UndefOr[A], B1 | B2]): B1 | B2 =
      a.asInstanceOf[B1 | B2]

sjrd Nov 26 21:21
There should be an issue anyway so we can track it for the release notes, at least.

***End of Conversation***

looks like it should be fixed in scala.js core itself! , do you want to send a PR there ? or we'll have them in SJRC for now and eventually move there ...

**Comment by chandu0101** [comment]
recently @xsistens raised same issue in scala.js gitter channel.

***Start of Conversation***
@sjrd is there are way to make Union types working with js.UndefOr types? Since both are implicits and scala only uses one conversion at the time something like this wont work at the moment:
def f(param: |[js.UndefOr[A] | B]): Unit = ???
val a: A = ???
f(a)
you always have to wrap the a when you pass it or define a like this:
val a: js.UndefOr[A] = ???

ochrons Nov 26 20:28
why not js.UndefOr[A | B]?

xsistens Nov 26 20:29
i'm pretty sure it's not working ether
and its semantically not the same as the one above or am I wrong?

sjrd Nov 26 20:31
I would encourage js.UndefOr[A | B], but indeed it probably does not "work" either.
One way to "make it work" would be to use A | B | js.UndefOr[Nothing] (I think)
Otherwise, come up with more implicit magic to make js.UndefOr and | behave better with each other.

xsistens Nov 26 20:33
ok, i give it a shot  just wanted to check if there is already something i was not aware of.

sjrd Nov 26 20:36
Maybe:
implicit def indirectA2undefOrA[A, B](v: B)(implicit ev: B => A): js.UndefOr[A] =
  js.UndefOr.any2undefOrA[A](ev(v))
That might work for js.UndefOr[A | B]

xsistens Nov 26 20:39
implicit def fromWithAllUndefOr[A, B1, B2](a: A)(implicit ev: Evidence[A, B1 | B2]): js.UndefOr[B1 | B2] =
    js.UndefOr.any2undefOrA(a.asInstanceOf[B1 | B2])
this will work for js.UndefOr[A | B]

sjrd Nov 26 20:41
Cool  PR welcome 

xsistens Nov 26 20:42
yours also works for it
what version do you prefer? Yours is more generic and will match more cases i think. My version will only apply to the Union case.

sjrd Nov 26 20:45
Good question. I don't know.
I guess file an issue for now anyway, with the two solutions, and I'll think about it.

xsistens Nov 26 20:46
I always try to be as specific as possible with the implicits so that i dont end up with conflicts between them.
Ok i write an issue for it.

xsistens Nov 26 21:13
@sjrd this solves both cases, js.UndefOr[A | B] as well as [js.UndefOr[A] | B]. Should i make a PR with these two functions and some tests or rather have a discussion in an issue?
implicit def fromWithAllUndefOr[A, B1, B2](a: A)(implicit ev: Evidence[A, B1 | B2]): js.UndefOr[B1 | B2] =
      js.UndefOr.any2undefOrA(a.asInstanceOf[B1 | B2])
implicit def fromWithOneUndefOr[A, B1, B2](a: A)(implicit ev: Evidence[js.UndefOr[A], B1 | B2]): B1 | B2 =
      a.asInstanceOf[B1 | B2]

sjrd Nov 26 21:21
There should be an issue anyway so we can track it for the release notes, at least.

***End of Conversation***
