### ISSUE TITLE
Deprecate JSExecutionContext.runNow

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2102]
This `ExecutionContext` misleads people into writing tests that are not, in fact, asynchronous.

Besides, I think it does not actually respect the contract of `ExecutionContext`. I seem to recall having read somewhere that an EC *had to* run things asynchronously, although I do not find a reference anymore :s

**Comment by gzm0** [comment]
@sjrd why did you remove this from v0.6.6? It is trivial to do and the earlier we deprecate things the better.

**Comment by japgolly** [comment]
I just discovered this deprecation in 0.6.6.

> This ExecutionContext misleads people into writing tests that are not, in fact, asynchronous.

Why would anyone think that `runNow` = asynchronous? It's got the word "now" in it. Isn't that like saying 'we removed integer multiplication because someone confused it with addition'? :laughing: 

If `runNow` confused someone in some situation then maybe we should rename it to something clearer. As of 0.6.6 it has been deprecated with no replacement. I know @sjrd citied that ECs *might* need to be async - if that's the reason, could we confirm it? If nothing else, I'm curious as to what could go wrong with the current `runNow` implementation.

**Comment by sjrd** [comment]
The main problem is that many people use it in tests because, you know, you can't wait, so let's just make it synchronous. But then tests mean nothing, because ECs are supposed to be asynchronous.

There is no replacement because `runNow` does not follow the specs of EC. If you want really, really need it, you're free to copy-paste the old implementation in your code. But you really shouldn't.

`runNow` made it into the codebase at a time when testing frameworks simply could not support asynchronous tests (returning `Future`s), and so `runNow` was the only way you could test *anything* using Futures. Now this time is over; all testing frameworks support asynchronous tests, and that is what you should use.

**Comment by japgolly** [comment]
You talk a lot of its implication in testing. In my case, there was only
one place where I hit this deprecation and it's because stdlib's Future
needs an EC when you call .map(). In such a case I didn't see the point in
calling setTimer for each .map() invocation. Would you say that runNow as
invalid for such a use case?

**Comment by japgolly** [comment]
> You talk a lot of its implication in testing

↑ Sounds weird on a re-read, even confrontational. I don't mean it that
way. Words = hard.
​

**Comment by sjrd** [comment]
> Would you say that runNow as invalid for such a use case?

The problem is ... nobody really knows. It might not be a problem in the current implementation, but since it's outside of EC's spec, another (valid) implementation might break it.

Note that Promises in JS also guarantee that each call to `then` will be executed in a different queue event, even if the promise happens to be already completed at the time `then` is called. This is important to prevent weird race conditions.

Using `runNow` is erring on the unsafe side of things, where things "work", but might break without notice.

**Comment by schmitch** [comment]
@sjrd it's really bad to deprecated runNow.
Why?
Currently If you have angularjs and run something inside setTimeout the scope won't know when to update so the digest cycle is really really slow.

http://jimhoskins.com/2012/12/17/angularjs-and-apply.html,
Could you at least give a alternative without a setTimeout call?

**Comment by sjrd** [comment]
What does JS code using Promises do? It would be in the same situation.

**Comment by sjrd** [comment]
Worse comes to worst, note that `ExecutionContext` is a public API that you can implement yourself, if you're not happy with the default ones.

**Comment by japgolly** [comment]
To add to the noise, here's another example of legitimate value in `runNow`:
https://github.com/japgolly/scalajs-react/blob/master/test/src/test/scala/japgolly/scalajs/react/CallbackTest.scala

I don't want to have to copy-and-paste the same benign code into all of my projects.

I think the decision to deprecate this should be reconsidered. Maybe we can just rename it to `synchronousStackUnsafe` or `runNowIfYoureDangerousAndCrazy`, etc so that the potential dangers are made obvious.

**Comment by sjrd** [comment]
@japgolly That is *precisely* the use case for which it is *not* legit. Using `runNow` in your tests can hide bugs that will show up with a really asynchronous execution context. 

You should use the asynchronous testing feature of uTest: have your tests return a `Future[R]`, performing the `assert`s in `map`s on your `Future`s.

**Comment by japgolly** [comment]
@sjrd Yes I'm doing that in some tests in a different project but I thought `runNow` was fine in the above example. Maybe I don't fully understand the problem here then. :-/ Are you able to point me to an example that demonstrates how this can hide bugs?

**Comment by schmitch** [comment]
@sjrd why does a setTimeout(0) call make a future more safe?!

**Comment by sjrd** [comment]
@schmitch Because it enqueues the callbacks to the global event queue--therefore executing them asynchronously--rather than executing them right away synchronously.

@japgolly `runNow` can hide the inability of your code to deal with `Future`s that have not been completed. This may not happen to you or other people well versed into the workings of JavaScript event queues, but it happens to other people.

Real-world example:

1. [cats introduced an instance of the `Equality` typeclass for `Future`s](https://github.com/typelevel/cats/pull/536), which "awaits" it (but throws if it's not already completed)
2. This was [against my urging them not to do it](https://github.com/typelevel/cats/issues/458#issuecomment-131920447)
3. Their tests pass by accident because they use `runNow`
4. [It breaks people's code](https://gitter.im/scala-js/scala-js?at=56a79942dc33b33c7547f8d8)

**Comment by japgolly** [comment]
@sjrd Right, right, right... I get it now! Thanks for pointing that out. Well, I'd better go and update my tests...
