### ISSUE TITLE
js.Any implementation for enumerated JavaScript values

### ISSUE THREAD

**Issue by rparree** [scala-js/scala-js#2113]
I am disappointed every time i have to use `String` or `js.Any`  for a JavaScript façade attribute/field. Many javascript APIs use enumerated String values and i have to use `String` for the type.

I would like to work on a proper solution using annotations and some macros for reading/writing these values.  For example something like:

```scala
@js.EnumValues  
sealed trait LayoutMode {

  @js.EnumValue  
  def value : String  
}

case object FitRows extends LayoutMode { val value = "fitRows" }
case object Masonry extends LayoutMode { val value = "masonry" }
case object Vertical extends LayoutMode { val value = "vertical" }
case object Packery extends LayoutMode { val value = "packery" }
...
```

There are two possibilities: Using Scala `Enumeration` or using a sealed trait with case classes. I foresee using two annotations: one on the type and one of the field representing the value.

Is there interest in this? And if so what would be a preferred way of defining the enum values?

**Comment by sjrd** [comment]
The recommended way to define string-like enumerations in Scala.js is like this: https://github.com/scala-js/scala-js-dom/blob/87ab4d70649078f5cf9a4c0e0e22c189de86a198/src/main/scala/org/scalajs/dom/crypto/Crypto.scala#L872-L887

This only relies on the current specification, and is type-safe, even if it is not particularly nice at definition site, it can then be used easily at call site. One could come up with a nicer syntax for that model based on macro annotations, but we won't go there in the core because macro annotations are non standard.

A priori, there is no interest in specifying and implementing this at the language level.
