### ISSUE TITLE
Store the Analysis in LinkingUnit?

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2306]
Would be useful for https://github.com/lionelfleury/scala-js-call-graph

**Comment by gzm0** [comment]
Not sure about this one. This will force us to re-run an analysis step after every change to the LinkingUnit (or it is outdated). We do not necessarily want that.

Or would you want to make it optional?

It is true that any sort of linker plugin might benefit from it. OTOH, it does not have back-indexing to the actual classes...

**Comment by sjrd** [comment]
> We do not necessarily want that.
> Or would you want to make it optional?

Hum, true. I guess we could make it optional. Or lazy?

> OTOH, it does not have back-indexing to the actual classes...

Hum, why? Through their `encodedName`, they have links, haven't they?

**Comment by gzm0** [comment]
> Hum, why? Through their encodedName, they have links, haven't they?

Yes, they do. I meant in-memory indexing that doesn't need lookups anymore. But from what I see, most stuff is indexed already (only the actual `ClassDefs` are not, and that seems ok).

> Hum, true. I guess we could make it optional. Or lazy?

Piggy-backing the analysis only seems useful for phases that analyze themselves. If a phase changes anything, the analysis is invalid an has to be redone. So it might as well be done inside the next phase.

I think just adding an `Option[Analysis]` is sufficient. I prefer this over having a lazy val, since a lazy val might not make it explicit that it is a costly operation (and one that might be made incremental at some point in time).

If necessary, we can add tooling later to calculate the analysis (in a way that supports incremental analysis) from a linking unit. That tooling can then just bypass the calculation if it is not necessary.

By the way, I don't really see how this would benefit the call graph plugin. The interaction with the tools API seems to be extremely lightweight (it even uses caching).

**Comment by sjrd** [comment]
It seems this was not really useful after all, and given the concerns, let's drop it.
