### ISSUE TITLE
Infinite loop in BigDecimal.isValidLong

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2314]
The following causes an infinite loop in SJS:
```scala
BigDecimal("9.223372E+285625056").isValidLong
```

On JVM, it correctly returns `false`:
```
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_77).
Type in expressions for evaluation. Or try :help.

scala> BigDecimal("9.223372E+285625056").isValidLong
res0: Boolean = false
```

**Comment by nicolasstucki** [comment]
The loop is in fact not infinite. It is just EXTREMELY slow. `isValidLong` uses `longValueExact` which uses `valueExact`. The [last one](https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/math/BigDecimal.scala#L1730) computes the normilized version of the `BigDecimal` using `toBigIntegerExact`. It looks like the computation in `toBigIntegerExact` is slow due to the size of the `BigInteger`s involved in the computation.

A simple solution would be to test some bounds in `valueExact` before computing the `toBigIntegerExact` and fail faster for large numbers.

**Comment by japgolly** [comment]
Erm this is still a problem in 0.6.9.

```scala
BigDecimal("9.223372E-2147483642").isValidLong
```

**Comment by japgolly** [comment]
Btw, large numbers (eg. `9.223372036854776E+79031823`) are now fast, just not slow ones by the look of it.

**Comment by nicolasstucki** [comment]
Oh, we had some issues with the implementation of that fix and ended up removing the part that was supposed to take care of those cases rather than fixing it. This should be simple to fix.

THe issue with the small one is that it is relying on `BigInteger` arithmetic, which is a "bit" slow. The used only the scale and precision of the `BigDecimal` to determine if there is no way that the number will fit in a `long`. If you really need the performance we could explore the possibility of implementing [`valueExact`](https://github.com/scala-js/scala-js/blob/98ff304f3d1162788daf889692bf4160bb8ee143/javalib/src/main/scala/java/math/BigDecimal.scala#L1729) without using `BigInteger`, but that would be for another issue.

**Comment by sjrd** [comment]
> ended up removing the part that was supposed to take care of those cases rather than fixing it

Not really. It was supposed to be handled by `toBigIntegerExact()`, which should fail fast if the number is not integer. The problem likely lies around there, then.

**Comment by japgolly** [comment]
> If you really need the performance

To clarify, I'm not sure if you're seeing the same results as me but on my machine, I've let the call run for about 3, 4 minutes before I killed it.

**Comment by nicolasstucki** [comment]
@japgolly if I run your example I get on JVM, Rhino, Node (fastOpt/fullOpt) the result is always an exception on the creation creation of the number. 
```scala
scala> BigDecimal("9.223372E-2147483642")
java.lang.NumberFormatException: Scale out of range.
  at java.math.BigDecimal.adjustScale(BigDecimal.java:609)
  at java.math.BigDecimal.<init>(BigDecimal.java:562)
  at java.math.BigDecimal.<init>(BigDecimal.java:383)
  at java.math.BigDecimal.<init>(BigDecimal.java:806)
  at scala.math.BigDecimal$.exact(BigDecimal.scala:125)
  at scala.math.BigDecimal$.apply(BigDecimal.scala:283)
  ... 33 elided
```

**Comment by nicolasstucki** [comment]
@japgolly did you found other cases that end up in an infinite (or extremely long) loop?

**Comment by japgolly** [comment]
It's a test in Monocle that comes up with these cases. I locally put in a few hacks to print out what it's doing and what the numbers are and then run the test and see where it hangs.

This is the test:
https://github.com/julien-truffaut/Monocle/blob/master/test/jvm/src/test/scala/monocle/std/BigDecimalSpec.scala

And this is the little local hack I used to print useful stuff:
```diff
diff --git a/core/shared/src/main/scala/monocle/std/BigDecimal.scala b/core/shared/src/main/scala/monocle/std/BigDecimal.scala
index 0a4132d..379f787 100644
--- a/core/shared/src/main/scala/monocle/std/BigDecimal.scala
+++ b/core/shared/src/main/scala/monocle/std/BigDecimal.scala
@@ -6,9 +6,41 @@ import monocle._
 
 object bigdecimal extends BigDecimalOptics
 
+object Ahhh {
+  def time[A](name: String)(a: => A): A = {
+  printf("[%s] Starting...\n", name)
+  val start  = __start
+  val result = a
+  __stop(name, start)
+  result
+}
+
+import System.{nanoTime => clock}
+
+private type Clock = Long
+
+private def __start: Clock =
+  clock()
+
+private def __stop(name: String, start: Clock): Unit = {
+  val end = clock()
+  val timeInMs = (end - start).toDouble / 1000000
+  printf("[%s] Completed in %.3f ms.\n", name, timeInMs)
+}
+
+}
+import Ahhh._
+
 trait BigDecimalOptics {
   val bigDecimalToLong: Prism[BigDecimal, Long]  =
-    Prism[BigDecimal, Long](bi => if(bi.isValidLong) Some(bi.toLongExact) else None)(BigDecimal(_))
+    Prism[BigDecimal, Long]{bi =>
+      if( time(s"$bi.isValidLong")(bi.isValidLong) )
+        Some( time(s"$bi.toLongExact")(bi.toLongExact) )
+      else
+        None
+      }{ l =>
+        time(s"BigDecimal($l)")(BigDecimal(l))
+      }
 
   val bigDecimalToInt: Prism[BigDecimal, Int] = bigDecimalToLong composePrism long.longToInt
 
```

**Comment by nicolasstucki** [comment]
Thanks for that code. I found that the value that we used to compute the fast path was overflowing. The fix is simple and I tested it on `Monocle`.

**Comment by japgolly** [comment]
Very nice, thanks @nicolasstucki. With this fix, Monocle's entire test suite will pass in Scala.JS. :+1:
