### ISSUE TITLE
Implement Double and Float conversion methods to long and int. 

### ISSUE THREAD

**Issue by thesamet** [scala-js/scala-js#2327]
ScalaJS is currently missing the following methods:

```
Double.doubleToRawLongBits
Double.longBitsToDouble
Float.floatToRawIntBits
Float.intBitsToFloat
```

Context: TrueAccord/ScalaPB#99

**Comment by sjrd** [comment]
We already have `Double.doubleToLongBits`, `Double.longBitsToDouble`, `Float.floatToIntBits` and `Float.intBitsToFloat`.

And the raw versions *cannot* be implemented, because JavaScript only has one canonical `NaN`.

You should evaluate whether the non raw versions are OK for your use case, and use those of possible. If not, you're or of luck.

**Comment by sjrd** [comment]
I think that for [your use case](https://github.com/trueaccord/protobuf-scala-runtime/blob/master/src/main/scala/com/google/protobuf/CodedOutputStream.scala#L347) it would be fine to use the non raw version. Especially if you compile that code only with Scala.js.

**Comment by thesamet** [comment]
It should be possible for the ScalaJS parser to decode messages produced by
native serializers (which would use the raw version), and vice versa.

On Mon, Apr 11, 2016 at 11:30 PM, Sébastien Doeraene <
notifications@github.com> wrote:

> I think that for your use case
> <https://github.com/trueaccord/protobuf-scala-runtime/blob/master/src/main/scala/com/google/protobuf/CodedOutputStream.scala#L347>
> it would be fine to use the non raw version. Especially if you compile that
> code only with Scala.js.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scala-js/scala-js/issues/2327#issuecomment-208729245>
>



-- 
-Nadav

**Comment by sjrd** [comment]
That would work. The raw versions differ from the non raw versions only for non canonical `NaN`s. All bit patterns of `NaN`s are mapped to the canonical `NaN`.

In your case, the difference would only be observable if, starting from the JVM, you serialize a non-canonical `NaN` (which is hard to obtain), deserialize it on JS, re-serialize it, deserialize that on the JVM and finally rely somehow on the particular `NaN` that you expected (even harder).

**Comment by Sciss** [comment]
Having trouble because of missing `floatToRawIntBits` and `doubleToRawLongBits` when cross-compiling. Why can't they be implemented in SJS identically to `floatToIntBits` and `doubleToLongBits`, that would make cross-compilation easier.

**Comment by sjrd** [comment]
Because it would be incorrect, and code relying on them would break without warning.

If you're not relying on the precise bit pattern of `NaN`, use `doubleToLongBits` instead, which is supported.

If you are relying on the specific bit patterns of `NaN`, for example because you're essentially storing a `Long` in a `Double` (instead of the other way around), then using `doubleToLongBits` would be completely incorrect, and therefore if we offered you `doubleToRawLongBits` as a copy of `doubleToLongBits, you would still be stuck.

The policy of Scala.js core for deciding whether we can implement a JDK method is: if it links, it is correct. If we cannot implement a method correctly, we don't implement it.
