### ISSUE TITLE
Suggesting `NullOr` similar to `UndefOr` for JS-structures

### ISSUE THREAD

**Issue by lastsys** [scala-js/scala-js#2344]
When handling JSON-objects some fields can contain `null` values. It would be nice to have such values parsed automatically to `Option` where `null` represents `None`.

Example:

``` json
{
  "name": null
}
```

could be defined as

``` scala
trait MyObj extends js.Object {
  val name: js.NullOr[String]
}
```

which means that when accessed we get

``` scala
val name: Option[String] = myObj.name.toOption
```

Not sure what to write if, for some reason, a field can be either `undefined`, `null` or `String`.

**Comment by sjrd** [comment]
That does not really make sense. `String` is *already* nullable, because that's how it works in Scala.

With a nullable type such as string, you'd do `Option(myObj.name)` instead of `myObj.name.toOption` to turn `null` into `None`.

The absence of null-safety in Scala is unfortunate, but it's there anyway. I don't think this would significantly improve the situation. If you really want such a thing, you can define it yourself with something like:
```scala
@js.native
sealed trait OrNull[+A] extends js.Any

object OrNull {
  implicit class OrNullOps[+A](val self: OrNull[A]) extends AnyVal {
    def toOption: Option[A] = Option(self).asInstanceOf[Option[A]]
  }
}
```

**Comment by lastsys** [comment]
Yes, `String` is nullable, and that is the problem. `null` introduces a lot of problems throughout the code and being able to eliminate `null` directly from the source would reduce the risk for errors.

I agree that this is not _necessary_ functionality, but it is nice to have. I would suggest some part of the standard lib with utilities for writing facades to enforce best practices.

**Comment by sjrd** [comment]
What about using `A | Null`, e.g., `String | Null`. You can even get a pretty good API with a user-defined implicit pimp:
```scala
package helloworld

import scala.scalajs.js
import scala.scalajs.js.|

object NullOrImplicits {
  implicit class NullOrOps[A](val self: A | Null) extends AnyVal {
    @inline def isDefined: Boolean = self != null

    @inline private def forceGet: A = self.asInstanceOf[A]

    @inline def get: A =
      if (isDefined) forceGet
      else throw new NoSuchElementException("null")

    @inline def fold[B](ifEmpty: => B)(f: A => B): B =
      if (isDefined) f(forceGet)
      else ifEmpty

    @inline def map[B](f: A => B): B | Null =
      fold[B | Null](null)(f(_))

    @inline def getOrElse[B >: A](ifEmpty: => B): B =
      fold[B](ifEmpty)(identity)
  }
}

object HelloWorld extends js.JSApp {
  def main() {
    test("hello")
    test(null)
  }

  def test(x: String | Null): Unit = {
    import NullOrImplicits._

    println(x.isDefined)
    try println(x.get)
    catch {
      case th: Exception => println(th)
    }

    println(x.fold(-1)(_.length))
    println(x.map(_.length))
    println(x.map(_.length).getOrElse(-1))
    println()
  }
}
```

**Comment by lastsys** [comment]
Nice approach. Would that work for `UndefOr` as well?
The first `NullOr` approach has been working very well for me and I have even added an `EmptyObjectOr` which maps to `jQuery.isEmptyObject()`.

Many people would argue that these things belong in a serialization library, however, when you need to work with raw JS-objects when writing bindings for existing libraries it is helpful to have some kind of low level "serialization".

I suggest that SJS gets an official facade tool library where best practices for handling cases like this are collected. You are right that these thing doesn't belong in the core language.

**Comment by sjrd** [comment]
Yes it would also work for `js.UndefOr`. We can't change now, though, as it wouldn't be binary compatible, and probably not 100% source compatible either. But I would like to reconsider that for 1.0.

Also for `js.UndefOr` it's going to be a bit weird because the type of `undefined` is in fact `Unit`. But we can keep `js.UndefOr[A]` as an alias for `A | Unit` for clarity.

**Comment by lastsys** [comment]
Would it be possible to easily write something similar `A | Null | Undefined` for a bad behaving backend?

I am thinking about if the "expression problem" becomes a serious problem with all different combinations. (http://eli.thegreenplace.net/2016/the-expression-problem-and-its-solutions/)

**Comment by sjrd** [comment]
You certainly can write `A | Null | Unit`. You'll need two getOrElse's or a `flatten` to collapse both "empty" values, though.

**Comment by lastsys** [comment]
How would this affect the definition of `js.undefined` if `Unit` should be used to indicate that something is undefined?
Reading about `Nothing` and `Unit` here: http://stackoverflow.com/questions/13539822/whats-the-difference-between-unit-and-nothing

The definition of `js.undefined` seems to be:
```scala
@inline
def undefined: js.UndefOr[Nothing]
```

**Comment by sjrd** [comment]
`js.undefined` would be typed as `Unit` in that case. It would be a simple alias of `()`, only useful to make the intent clearer.

**Comment by sjrd** [comment]
Since Scala.js 1.0.0-M1, `js.UndefOr[A]` is an alias for `A | Unit`. A hypothetical `js.NullOr[A]` could be defined as `A | Null`, as I suggested above. However, in dotty, and assuming dotty does not become null-safe, an `A | Null` would be broken, because dotty would collapse it to `A`, destroying the implicit pimps.

Therefore, we cannot give any guarantee on (long-term) future support of `NullOr`, and that means we should not add it to the core. A motivated user could publish it as a separate library if they want.
