### ISSUE TITLE
Support sbt's cross target build

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#2422]
At the moment Scala.js's sbt plugin provides a crossProject method.

I wonder if we can support the native sbt cross target mechanism like what https://github.com/TiarkRompf/scala-virtualized did.

I think this approach will be easier to share sbt settings between JVM targets and Scala.js targets, and may encourage more libraries porting to Scala.js.

**Comment by sjrd** [comment]
That wouldn't work. sbt's cross target mechanism is only able to deal with a change in `scalaVersion`/`scalaBinaryVersion`. Scala.js does not change `scalaVersion`, but changes *many* other things. sbt's mechanism is not flexible enough for Scala.js' cross compilation.

Besides, sbt's mechanism is not able to deal with a "shared" crossProject depended on by two platform-dependent projects, which is the very common client/server setup. So that doesn't work either.

For those reasons, I'm going to close this.
