### ISSUE TITLE
it is hard to track println statements

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js#2451]
When I look at debug console to read printlns then I see a reference to "System.scala:352" and the following piece of code:
```scala
  private def doWriteLine(line: String): Unit = {
    import js.DynamicImplicits.truthValue

    // We've got to use selectDynamic explicitly not to crash Scala 2.10
    if (global.selectDynamic("console")) {
      if (isErr && global.console.selectDynamic("error"))
        global.console.error(line)
      else
        global.console.log(line)
    }
  }
```

It would be nice (if possible) to see the exact place in my code where println was called from, instead of this System.scala internals.

**Comment by sjrd** [comment]
I don't think that's possible. It's a magical feature of `console.log` in browsers, which cannot be reproduced by any other function. Note that such a feature is not supported in Node.js, nor on the JVM. The specification of `println` is such that we cannot simply magically "replace" it by `console.log`s at call sites, so that's not an option either. It has to honor `Console.set/withOut`, `System.setOut`, non-whole line printing and buffering, and a bunch of other stuff.

If you do want the magic `console.log` behavior, use `js.Dynamic.global.console.log` yourself (or write a macro that desugars to that on JS, and to `println` on the JVM). It is not planned to offer such a feature in core, however.

So I'm afraid I have to close this as Won't fix, even though I agree it would have been nice to have.
