### ISSUE TITLE
The BufferedReader implementation does not close its underlying Reader

### ISSUE THREAD

**Issue by alexandru** [scala-js/scala-js#2471]
The [implementation of close()](https://github.com/scala-js/scala-js/blob/165ac953ae34d6d79cbfe6c8f7966cfadbfd62c4/javalib/src/main/scala/java/io/BufferedReader.scala#L20) on the `java.io.BufferedReader` port is violating its contract.

On `close()` the `BufferedReader` implementation  should also close the underlying reader.

**Comment by sjrd** [comment]
The [JavaDoc of `BufferedReader.close()`](https://docs.oracle.com/javase/7/docs/api/java/io/BufferedReader.html#close()) is actually not very clear about this point. But experimentation suggests that it indeed closes the underlying reader:
```scala
Welcome to Scala version 2.11.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions to have them evaluated.
Type :help for more information.

scala> class MyReader(s: String) extends java.io.StringReader(s) {
     |   override def close(): Unit = {
     |     println("closing")
     |     super.close()
     |   }
     | }
defined class MyReader

scala> val bf = new java.io.BufferedReader(new MyReader("hello\nthere\n"))
bf: java.io.BufferedReader = java.io.BufferedReader@6692b6c6

scala> bf.readLine()
res0: String = hello

scala> bf.close()
closing

scala> bf.close()

scala>
```

**Comment by alexandru** [comment]
@sjrd sorry for not providing a test yet, have been busy.

The thing is, no matter what the JavaDoc says or doesn't say, it does not make sense for `Reader` implementations that wrap other readers, such as `BufferedReader` to not close their resources. Because we have subtyping and people are accustomed to do stuff like ...

```scala
new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF-8"))
```

And then work with the resulting reference, passing it around, relying on it to chain the close all the way up to the `FileInputStream`. These classes would be horrible if they wouldn't close the used resources.

**Comment by sjrd** [comment]
It doesn't matter what the JavaDoc says ... almost, I agree.

But also your reasoning does not really matter either. You might *want* for some good reason that a Java API does this or that, but if it doesn't on the JVM, we're not going to do it in Scala.js.

The only thing that truly matters is *what the JVM does in practice*, which, as my snippet above demonstrates, is indeed to close the underlying resource in this case.

So *yes*, our current implementation is a bug and we must fix it. But not because the new behavior is desirable; simply because that's what the JVM does.

It has happened in the past that we specifically did *not* do the desirable behavior of some API, because experimentation on the JVM showed that the JVM also did not do the "right" thing.
