### ISSUE TITLE
Treat Byte as a Uint8Array[1] for platforms that support TypedArrays

### ISSUE THREAD

**Issue by mdedetrich** [scala-js/scala-js#2556]
Currently Byte appears to be an alias for a number type in Scala.js (see https://www.scala-js.org/doc/interoperability/types.html). Unfortunately this means that doing the typical operations that you would on a byte would have much lower performance since its treated as an IEEE 754 number rather than a bye (or unsigned int).

Note that I haven't confirmed this is the case since I haven't done benchmarks to confirm this, but I would suspect a single element byte array (i.e. `new Uint8Array(1)`) would be faster

**Comment by gzm0** [comment]
I think we really would like to see some benchmarks on this.

There are a couple of arguments why keeping them the way they are might be faster:

- The JIT might be able to optimize (just like for ints)
- It might be faster to do int (word) operations on the platform anyways.
- Typedarrays are less optimized (because newer). This means they might need heap allocation (!).
- In any case we'd need a fallback (at least in ES5 mode) since typed arrays are not ECMAScript 5.1. The additional branches introduced by the dynamic checking would probably kill performance anyways.

However, I'm happy to leave this open if you are willing to do benchmarks and post them here. Are you encountering performance issues?

**Comment by mdedetrich** [comment]
I am not having performance issues right now, its actually something that came up in my head when making this issue https://github.com/cb372/scalacache/issues/110.

I agree that benchmarks need to be made before any decision is done, the allocation of `Uint8Array` might kill any other performance improvements that it provides

**Comment by sjrd** [comment]
I'm betting 100 to 1 that encoding with a typed array will be at least 10 times slower. VMs make the distinction between integers and doubles, so a byte is really an integer, which is well optimized. Moreover, it is never boxed, unlike a typed array (at least if it escapes).

I'll go a step further than @gzm0 and close this. It can be reopened if benchmarks prove I'm wrong.
