### ISSUE TITLE
split("") is not identical to JVM split

### ISSUE THREAD

**Issue by ankitson** [scala-js/scala-js#2573]
This assert fails in JS but passes in JVM:

```scala
val line = "123"
val splits = line.split("").toList
assert (splits == List("1","2","3")) //JS returns List("", "1", "2", "3")
```

I think this ignores the rule from the javadoc that "A zero-width match at the beginning never produces an empty leading substring". 

Similarly `line.split("a?").toList` has an empty leading substring.

**Comment by sjrd** [comment]
Thanks for the report.

**Comment by lihaoyi** [comment]
FWIW `"abc".split("", -1)`'s behavior also differs:

- JS: `Seq("", "a", "b", "c", "")
- JVM: `Seq("a", "b", "c", "")

This is on 0.6.11

**Comment by sjrd** [comment]
So we had in fact identified this as a JDK7/8 discrepancy when we last fixed `split()`: https://github.com/scala-js/scala-js/pull/1198#discussion-diff-19446807
At the time, it was unclear whether the change was intentional or a bug. Since then (only 2 months afterwards, actually), it has been confirmed as an intended change. So now we should update our implementation to follow the behavior of JDK8.

**Comment by sjrd** [comment]
Documentation of `Pattern.split()` from JDK 8, where the spec is now more precise: http://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#split-java.lang.CharSequence-int-
