### ISSUE TITLE
Adapt to new rules for super calls

### ISSUE THREAD

**Issue by adriaanm** [scala-js/scala-js#2580]
It may be a bug on our end (/cc @lrytz for verification), but the following patch was needed to build scala-js on what will be 2.12.0-RC1: https://github.com/adriaanm/scala-js/commit/6337f7d2a002650920983b4dd2c2c1edce2c564d

**Comment by adriaanm** [comment]
I'll also co-opt this ticket as a reminder to drop scala-junit-mixin-plugin (https://github.com/adriaanm/scala-js/commit/ac5f2bb47eaaa115864009d1f1b6d2571d82153f)

**Comment by sjrd** [comment]
Looks like a bug to me. `Error` is the direct parent class of `UndefinedBehaviorError`. There's no reason I shouldn't be able to call `Error`'s version of the method.

(Calling `NoStackTrace`'s version would understandably be disallowed, though.)

**Comment by lrytz** [comment]
The idea was the following. Example:

```
class A { def f = 1 }
class B extends A
class C extends B { def t = super[B].f }
```

(Side-note: `super[A].f` is ruled out in the typer, "error: A does not name a parent class of class C")

Now assume an override of `f` is added to `B` and only that class is re-compiled (separate compilation), then method `C.t` would resolve `f` differently, the result would change.

You could also do the example the other way around: first have an override of `f` in `B`, then remove it.

My thinking was to adhere to the following part of the spec:

  > `super[T].m` is a static super reference. The reference is to the method `m` in the parent trait of `C` whose simple name is `T`.

This sounds like there should not be any dynamic lookup in this case.

(Side-note: not sure if the wording in the spec "the parent trait" is intentional, i.e., if `super[T]` should only be allowed if `T` is a trait, not a class).

But maybe I was overly restrictive. I think the spec does not say what happens under separate compilation. It could be interpreted as "method `f` in `B`", no matter if `B` is defining `f` or inheriting it from a superclass.

However, if we allow it, note that the behavior would be different if `A` was a trait:

```
trait A { def f = 1 }
class B extends A
class C extends B { def t = super[B].f } // invokestatic A.f$
```

If we add an override of `f` to `B` and recompile only `B`, the result of `C.t` stays the same. Maybe this case should be ruled out? Or maybe, again, this is fine because we don't specify what happens under separate compilation?

cc @retronym

**Comment by lrytz** [comment]
I should add, when I wrote the patch I didn't realize that it would rule out some code patterns that cannot be written otherwise; I thought that one could always write `super.m` instead of `super[T].m` in such cases. But the example here shows it's not the case: writing `super.fillInStackTrace()` would resolve to the method defined in `NoStackTrace`.

**Comment by sjrd** [comment]
> You could also do the example the other way around: first have an override of f in B, then remove it.

By that argument, `super[B].f` can *never* be allowed when `B` is a class.

The spec never really works in the presence of separate compilation. It is the job of an incremental compiler to recompile the necessary parts so that separate compilation achieves the same result as batch compilation. That the behavior of separate compilation under insufficient incremental recompilation produces different results for classes than for traits is a non-issue IMO. Just let the incremental compiler decide when it is necessary to recompile what.

Therefore, I think the current error is too restrictive. This use case should be allowed, IMO.

**Comment by lrytz** [comment]
> By that argument, super[B].f can never be allowed when B is a class.

Indeed, good point :) So yes, we should probably relax it again.

> It is the job of an incremental compiler

I was thinking of separate compilation in the sense of evolution of libraries, not incremental compilation within a project.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/5377

**Comment by sjrd** [comment]
Does that mean we can close this issue here?

**Comment by lrytz** [comment]
yes - @adriaanm can you make sure to exclude https://github.com/adriaanm/scala-js/commit/6337f7d2a002650920983b4dd2c2c1edce2c564d when running the next community build?

**Comment by adriaanm** [comment]
Yep, already dropped that commit from the master branch of my fork
