### ISSUE TITLE
Compiler plugin advice

### ISSUE THREAD

**Issue by AugustNagro** [scala-js/scala-js#2594]
When using typescript decorators for libraries like angular, a class like 

```
@Component({
    selector: 'my-app',
    template: '<h1>Angular 2 App</h1>'
})
export class AppComponent { }
```

Is transpiled to 

```
var AppComponent = (function () {
    function AppComponent() {
    }
    AppComponent = __decorate([
        core_1.Component({
            selector: 'my-app',
            template: '<h1>My First Angular 2 App</h1>'
        }), 
        __metadata('design:paramtypes', [])
    ], AppComponent);
    return AppComponent;
}());
```

whereas `__decorate` and `__metadata` call `Reflect.decorate` and `Reflect.metadata` of the reflect-metadata library.

It's ideal to use macros for Scala-JS facades of these libraries, but to my best knowledge actually attaching the annotations requires either the generation of a new .js file file that adds the annots, or a compiler plugin.

I've briefly looked at [http://www.scala-lang.org/old/node/140](http://www.scala-lang.org/old/node/140) and the source of a few other plugins, but wanted to ask for opinions/recommendations before going any further. 

Thanks for your time :)

**Comment by sjrd** [comment]
Here is not the best venue for this kind of discussion. We use this issue tracker for issues and enhancement requests; not for usage questions.

Since your question probably needs *discussion*, I guess Stack Overflow is not appropriate either. I would suggest [the scala-js mailing list](https://groups.google.com/forum/#!forum/scala-js), or [the Gitter channel](https://gitter.im/scala-js/scala-js).

**Comment by AugustNagro** [comment]
Sure. I'll move to the gitter
