### ISSUE TITLE
Trivial module accessors not elided in 2.12

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2626]
Consider:

``` scala
js.Dynamic.console.log(1)
```

in 2.12.0-RC1, this yields the following code:

``` javascript
$g.console.log(($m_sjs_js_Any$(), 1))
```

Pre 2.12, `js.Any` (needed for implicit conversion) was elided.

**Comment by sjrd** [comment]
That happens because, starting from 2.12.0 (-RC1, I think), the `$init$` method of traits is a default method rather than a static method. The constructor of `js.Any$` has therefore changed to:
```scala
  def init___() {
    this.O::init___();
    mod:sjs_js_Any$<-this;
    this.sjs_js_LowPrioAnyImplicits::$$init$__V()
  }
```
which has call to default method, rather than a static method. And the optimizer doesn't look for default method call as candidates to be pure, which means it decides that `js.Any$()` is not safe to elide.
