### ISSUE TITLE
TimeoutException when running PhantomJS with macOS Sierra

### ISSUE THREAD

**Issue by jxm262** [scala-js/scala-js#2640]
After upgrading my Mac OS to Sierra , I can't seem to get phantomjs to work with my tests.  It keeps giving an error -  `Futures timed out after [4841340619 nanoseconds]`  (TimeoutException).  Full stack trace is here - https://gist.github.com/jxm262/8d508e7a98611a69d423640119cee109  
  
I've put up a sample repo here to demonstrate - https://github.com/jxm262/scala-js-phantomjs

It runs the tests fine, they all execute, but I think the runner is never able to exit because of the timeout.  After tracing down through a bunch of the code in the testadapter, I was able to get it to exit properly by setting the `VMTermTimeout` to 15 seconds.  If I understand the code correctly, it's loading phantom as a separate thread and for some reason it takes longer than 5 seconds now to complete, where as in the previous OS it must have been less.

//I changed from 5  to 15 seconds and the test suite exits correctly
https://github.com/scala-js/scala-js/blob/7640e858efbf8dbf52c99ca8a82cfb2350836e02/test-adapter/src/main/scala/org/scalajs/sbttestadapter/package.scala

Any ideas on what could be causing this?  I can submit a PR to increase the VMTermTimeout , but wanted to know a little bit more on why the timeout was hard set to 5 seconds in the first place.

**Comment by gzm0** [comment]
This seems to be happening in the shutdown sequence of the test. So all that is supposed to happen in these 5 seconds is:

1. Send a "stopSlave" websocket message to each slave.
2. Slave terminates itself.
3. Wait for slaves to stop.

The timeout is set to 5 seconds because "it seemed enough" and we needed a timeout. It is not settable in the plugin, because the wiring of this setting is complicated and it doesn't seem like something one would usually want to set.

I'm happy to take any of the following changes:

- Increase the timeout up to 1 minute.
- Creates a good way to set the timeout (wiring it in via `ScalaJSFramework` is probably not a good idea). It might make sense to give `JSEnv` a "default timeout", but I'm not sure.

**Comment by jxm262** [comment]
Thanks for the response.  Referencing this PR so others can follow along - https://github.com/scala-js/scala-js/pull/1460

I'll submit a PR for the first option tomorrow unless someone else takes it.  I Would love to start getting more involved in this project  :)
