### ISSUE TITLE
Scala.js's sbt plugin improperly ignored jsDependencies for Runtime configuration

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#2682]
``` sbt
// jQuery dependency will be packaged for both test and compile configuration, which is good
jsDependencies += "org.webjars.bower" % "jquery" % "3.1.1" % Compile / "dist/jquery.js" minified "dist/jquery.min.js"
```

``` sbt
// jQuery dependency will be packaged for only test configuration, which is good
jsDependencies += "org.webjars.bower" % "jquery" % "3.1.1" % Test / "dist/jquery.js" minified "dist/jquery.min.js"
```

``` sbt
// jQuery dependency should be packaged for only compile configuration
// However, sbt simply ignored this setting
jsDependencies += "org.webjars.bower" % "jquery" % "3.1.1"  % Runtime / "dist/jquery.js" minified "dist/jquery.min.js"
```

**Comment by sjrd** [comment]
That's intentional. There is no notion of `Runtime` configuration in Scala.js. The file produced by `(compile:)fastOptJS` is for the `Compile` configuration.

What would be the rationale for it to behave like that?

**Comment by Atry** [comment]
@sjrd Is there any approach to create jsDependencies for `Compile` configuration but not for `Test` configuration, like `Runtime` for JVM's libraryDependencies.

**Comment by sjrd** [comment]
No, there isn't, because it does not make sense. `Test` depends on `Compile`, so anything that `Compile` depends on, `Test` must also transitively depend on it. This is the same for `libraryDependencies`.

The `Runtime` config of sbt does not give you a dependency only in `Compile`. It gives it to you specifically and only in the `run` task. Note that it does not emit any kind of file or product for that. It's only a manipulation of the classpath. In Scala.js, for `-jsdeps.js` generation, which an actual product, that does not make sense.

It's unclear to me why would you want a dependency in `Compile` but not in `Test` anyway? That sounds a bit fishy. Maybe there is a better solution.

**Comment by sjrd** [comment]
Closing as "as-designed", unless and until someone can point me to some authoritative source that would motivate this.
