### ISSUE TITLE
fastOptJS code not working in JavaScriptCore(JSC)!

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#2708]
I am updating my code base to use new `@JSImport..` , all of sudden my mobile app(react-native) not working in `fastOptJS` mode .

<img width="369" alt="screen shot 2017-01-04 at 3 43 47 pm" src="https://cloud.githubusercontent.com/assets/2179670/21642738/6b580608-d2aa-11e6-8895-f6ce089e2ce7.png">

Environment  : 

Scalajs 0.16.14 

[JSC - No JIT](http://trac.webkit.org/wiki/JavaScriptCore)

>When using React Native, you're going to be running your JavaScript code in two environments:
On iOS simulators and devices, Android emulators and devices React Native uses JavaScriptCore which is the JavaScript engine that powers Safari. On iOS JSC doesn't use JIT due to the absence of writable executable memory in iOS apps.

**Comment by sjrd** [comment]
Thanks for the report. I'm not sure exactly why `this` is undefined at this point. IMO the most straightforward fix would be to blindly remove [this line](https://github.com/scala-js/scala-js/blob/v0.6.14/tools/scalajsenv.js#L714) when emitting a CommonJS module. It shouldn't be needed anyway because we attach `$e = exports`.
