### ISSUE TITLE
Why different bound checks in ThreadLocalRandom next*(min, max) methods

### ISSUE THREAD

**Issue by fhalde** [scala-js/scala-js#2727]
In https://github.com/scala-js/scala-s/blob/master/javalib/src/main/scala/java/util/concurrent/ThreadLocalRandom.scala

for `nextInt(min, max)`, we do

`if (difference > 0)`

but for `nextLong(min, max)`, we do

`if (different >= 0)`

Am I missing a corner case ? Or is this how it should be ?

**Comment by sjrd** [comment]
It doesn't matter. The difference cannot be 0 because we check before that `max > min`.

Please refrain from using GitHub issues to ask questions. They are reserved for issues and feature requests. Use the Gitter channel or, in this case, you could simply have mentioned me in https://github.com/scala/scala/pull/5611

**Comment by fhalde** [comment]
I remember drafting this. Not sure when I posted this!
