### ISSUE TITLE
Running "sbt test" does not run tests with ScalaTest

### ISSUE THREAD

**Issue by davesmith00000** [scala-js/scala-js#2735]
Hi,

Apologies if this is a duplicate, I have a look around but couldn't see anything.

I'm trying to run unit tests using ScalaTest with a completely standard Scala project layout and minimal build sbt file (just the usual basic stuff + scalajs). If I run them through Intellij they work fine, if I run `sbt test` on the command line it actually does a `fastOptJS`.

Am I doing something wrong or is this a know issue?

Thanks,

Dave

**Comment by sjrd** [comment]
`fastOptJS` (or rather `test:fastOptJS`) is a step of running `sbt test`, as expected. The typical mistake is to depend on ScalaTest with `%%` instead of `%%%`, as should be the case for virtually all dependencies in a Scala.js project.

PS: questions are best asked on Stack Overflow or in the Gitter channel. We reserve GitHub issues for bug reports and feature requests.

**Comment by davesmith00000** [comment]
Ah! `%%%` has indeed resolved the issue, thank you.

Noted: In future I'll head over to StackOverflow or Gitter first, in my defence I thought it might be a bug when I submitted the issue. ;-)
