### ISSUE TITLE
Opt-In js.Any reflective call support

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#274]
We could support reflective calls on subtypes of `js.Any` if we are "allowed" to leak prototype members of the objects in question.

To some projects this could be acceptable. Should we add opt-in support for this? (Note that this will require us to generate code for RawJS types).

**Comment by Atry** [comment]
This feature can improve the interoperability with TypeScript, because TypeScript's interfaces are structural types. 

Currently we convert a TypeScript `interface` to a Scala.js `trait` that extends `js.Object`. As a result, compatible TypeScript types will not be able to convert to each other in Scala.js.

**Comment by sjrd** [comment]
You really wouldn't want to declare every single `interface` coming from TypeScript as a structural type. Structural types in Scala are a second-class citizen to begin with. For example, they cannot be recursive. They have no support in the compiler to cache recurring subtyping checks, so each check has to go through the whole member list, increasing compile times. They cannot declare concrete members, so the `= js.undefined` optional members of JS traits wouldn't be an option. Etc.

**Comment by Atry** [comment]
You are right. Scala's type system is almost a superset of Java's, while TypeScript's type system is more natural for JavaScript.
