### ISSUE TITLE
Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by strelec** [scala-js/scala-js#2746]
This works:
```
dom.document.documentElement.asInstanceOf[js.Dynamic].webkitRequestFullScreen()
````

while this does not:
```
val a = dom.document.documentElement.asInstanceOf[js.Dynamic].webkitRequestFullScreen
a()
```

This behavior is not consistent.

**Comment by sjrd** [comment]
I do not have a WebKit-powered browser to do the test, but I am convinced that the behavior you observe is consistent with what JavaScript does. In JavaScript, doing
```js
var f = x.m;
f();
```
is not the same as
```js
x.m();
```
Since you are using `js.Dynamic`, you are deliberately opting for JS semantics. The behavior is therefore as-designed.

You can get a correct behavior like this:
```scala
val a = () => dom.document.documentElement.asInstanceOf[js.Dynamic].webkitRequestFullScreen()
a()
```

**Comment by strelec** [comment]
This makes sense, it really is a JavaScipt thing. I have soved it by choosing to pass the original method parent back into the call method, like this. I hope that this helps someone else.

`a.call(dom.document.documentElement)`

Thank you.
