### ISSUE TITLE
Test passed when using `testHtmlFastOpt`, but not `test`.

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js#2759]
I have started a project using Scala.js, the project uses `esprima` JS parser. My first test is passed when I generate `testHtmlFastOpt` and run it from the browser, but not when I run `test` from SBT. My main app html works fine as well.

The error is  `TypeError: Cannot read property '
tokenize' of undefined` and it seems the test framework somehow did not load the dependency needed for the test. The dependency is defined using:

    jsDependencies += "org.webjars.npm" % "esprima" % "2.7.2" / "esprima.js"

The project is available at https://github.com/OndrejSpanel/ScalaFromJS, the issue can be seen in branch `testFailedUndefined`.

**Comment by sjrd** [comment]
That's normal. `test` runs your tests in a Node.js environment, and some (most) JavaScript libraries are distributed so that they try to be clever, and be "nice" to the environment they are run in.

In particular, in a browser environment, they will put things in the global scope. But in Node.js, they will *export* from the module instead.

To reconcile the two, you have to use the `commonJSName` option of `jsDependencies`, like this:
```scala
jsDependencies += "org.webjars.npm" % "esprima" % "2.7.2" / "esprima.js" commonJSName "esprima"
```
[See the documentation on dependencies](https://www.scala-js.org/doc/project/dependencies.html) for more information.
