### ISSUE TITLE
Debugging problems

### ISSUE THREAD

**Issue by Gralfim** [scala-js/scala-js#2795]
Even with a very basic source, we can clearly see problems with debugging (mapping lines in Scala sources):
1. during the function tracing, the cursor is switching to the beginning of the function
2. _Step Over_ often moves the cursor into the called function

This behavior makes tracing of complicated functions very difficult.

**Repro:**
In the following source, set the breakpoint to the first line of function DebugSample,main, launch it and try to use _Step Over_ to trace the function. See where the cursor will appear.

```
import scala.scalajs.js.JSApp
import scala.util.Random

object DebugSample extends JSApp {
  def main(): Unit = {
    val angle = Random.nextDouble() * 90.0
    val rad = angle.toRadians
    println(s"Random angle $rad radians")

    val angle2 = Random.nextDouble() * 45.0
    val rad2 = angle2.toRadians
    println(s"Random angle $rad2 radians")
  }
}

```

**Comment by sjrd** [comment]
When using step-by-step execution of Scala.js, it is recommended to disable the optimizer with:
```scala
scalaJSOptimizerOptions ~= { _.withDisableOptimizer(true) }
```

**Comment by OndrejSpanel** [comment]
I have tried this option. While it prevents stepping into the functions, still there is the issue of the current execution point jumping between real current location and the beginning of the `main` function on almost each step.

![image](https://cloud.githubusercontent.com/assets/6927223/23673857/1b779946-0374-11e7-9f64-25a6865a12a2.png)
![image](https://cloud.githubusercontent.com/assets/6927223/23673873/284ba130-0374-11e7-9634-58ee4ad63220.png)
![image](https://cloud.githubusercontent.com/assets/6927223/23673883/3154829c-0374-11e7-864c-5dc2a50790ad.png)

The screenshots are with IntelliJ IDE, when debugging with the Chrome Dev tools the results are even worse, it is not possible even to place breakpoints on most lines and stepping through is very erratic.

Are there any tools for inspecting or visualizing or otherwise debugging source maps? The behaviour seems surprisingly annoying for such small code sample.
