### ISSUE TITLE
Scala.js compiler doesn't pass through UTF-8 correctly for dependencies

### ISSUE THREAD

**Issue by svenwiegand** [scala-js/scala-js#2845]
Trying to use [speakingurl](https://github.com/pid/speakingurl) doesn't work correctly when specifying it as a `jsDependency` to Scala.js.

To reproduce download [speakingurl's distribution JS](https://github.com/pid/speakingurl/blob/master/lib/speakingurl.js) and include it via

```scala
jsDependencies ++= Seq(ProvidedJS / "speakingurl.js")
```

In the generated `client-jsdeps.js` several of the special UTF-8 characters from the sources in `speakingurl.js` aren't encoded correctly. This even makes the Internet Explorer to prevent loading the JavaScript at all, because it claims duplicate definitions in the `speakingurl.js`-part of `client-jsdeps.js`.

If you include `speakingurl.js` on its own in your HTML's header, everything works fine.

**Comment by ochrons** [comment]
If you are on Windows, this may help https://github.com/scalameta/scalafmt/issues/694

In short, it's a problem of default file encoding assumption by the JVM.

**Comment by gzm0** [comment]
Ah, ah nice. So of course a fix is to change the platform encoding. But it doesn't solve a more fundamental problem: What happens if we pull multiple JS libraries with different encodings? It essentially means that:

- We need a way to specify the encoding of a library or auto-detect it.
- We need to transcode when we write (that's not a big deal).

Of course the other option is that we regard JS files as binary files, but as a result we might have a file with multiple encodings in the same file. Pretty sure browsers don't like this :)

**Comment by sjrd** [comment]
If we do fix something, I would just hard-code UTF-8. Distributing a library under any other encoding than UTF-8 (or ASCII, which is a subset thereof) is suicidal anyway.

**Comment by ochrons** [comment]
Fixing it to UTF-8 should be just fine. It's what everyone is using anyway.

**Comment by ochrons** [comment]
For example webpack only allows UTF-8 input and produces UTF-8 output. There's a separate webpack-plugin for changing the output encoding, though.
