### ISSUE TITLE
Regression in optimiser

### ISSUE THREAD

**Issue by tindzk** [scala-js/scala-js#2943]
I believe there is a regression in the optimiser of Scala.js v0.6.16. When upgrading to this version and running my test cases, I encountered an OOM on Travis-CI: https://travis-ci.org/sparsetech/pine/jobs/230421157

Locally, it does not compile the test cases, getting stuck at "Fast optimizing". It doesn't finish even after a couple of minutes. `publishLocal` works fine and I did not notice any regressions in the artifact's functionality.

I investigated this issue as per @ochrons' suggestion by looking at the activity in JVisualVM. Here are the results:

![jvisualvm](https://cloud.githubusercontent.com/assets/196819/25863213/39010c56-34eb-11e7-8216-f11274c56527.png)

Please let me know how I can further assist in tracking down this issue!

**Comment by sjrd** [comment]
Also, what version are you upgrading from? The optimizer literally wasn't touched between 0.6.15 and 0.6.16.

**Comment by tindzk** [comment]
Sure. You can find it here: https://github.com/sparsetech/pine. `pineJS/test` fails.

Indeed, the last working version was 0.6.14.

**Comment by sjrd** [comment]
Thanks. I'll eventually have a look at it, but I can't promise anything better than "within 2 weeks", at the moment.

**Comment by tindzk** [comment]
No problem. I'm not in a rush. Thanks for taking the time!

**Comment by sjrd** [comment]
Starting to tinker with this. Apparently it's not taking *forever*. I let it run while I was doing something else, and it completed in 20 minutes :P

Moreover, reverting e0eeb70d79753a8d9c621ba34abb496d7406783d solves the issue. So something went wrong in that commit.

**Comment by sjrd** [comment]
The problematic method is https://github.com/sparsetech/pine/blob/1e186897234ac4d4e52cf175bd119c92b087cfd9/shared/src/main/scala/pine/HtmlEntities.scala
It is problematic because it is a giant varargs array of tuples. Now that we try to virtualize varargs, the optimizer will try (and succeed!) to virtualize every single one of those 1,200+ tuples. (At the end of the day, it has to cancel all that to give it to `Map.apply`, but that's not really the issue.) That's a lot of code to "interpret" as part of the optimization procedure.

However, the optimization itself is not really that slow. But this large piece of code to process yields an expansion of the number of local, synthetic variables that need to be generated with fresh names. And now that method breaks some invisible barrier, and exposes quadratic behavior in two places:

* The fresh name allocator: calling `freshName("foo")` is O(1) the first time, but becomes O(n) where n is the number of times `freshName("foo")` has been called. Therefore the cumulative effect of calling `freshName("foo")` n times is O(n²).
* The backups of `statesInUse`: O(n) where n is the number of states in use. If there are m nested `tryOrRollbacks` (in the successful branches), the cumulative cost of the backups is O(n*m).

So far I managed to easily fix the first problem, bringing the 20 minutes down to 3 minutes. Fixing the `statesInUse` issue is much harder.

Note that the problem already existed before e0eeb70d79753a8d9c621ba34abb496d7406783d. I'm pretty sure we can make the optimizer of 0.6.14 similarly crawl by defining an explicit `val` for each those tuples. That commit simply make the problem apparent on that specific piece of code.

**Comment by tindzk** [comment]
Thanks a lot for the in-depth analysis and fixes! When generating this file, I already had my concerns about its efficiency. Are there better ways to express large `Map`s in Scala.js?

**Comment by sjrd** [comment]
No, there is no better way. That's the right thing to do. It's just the Scala.js optimizer should be less stupid.

That said, I realize you could actually work around the issue right now using a `js.Dynamic.literal`. Something like:
```scala
  val entities: Map[String, String] = js.Dynamic.literal(
    "Aacute" -> "\u00C1",
    "aacute" -> "\u00E1",
    "Abreve" -> "\u0102",
    "abreve" -> "\u0103",
    ...
  ).asInstanceOf[js.Dictionary[String]].toMap
```
At least that would make your build green again.
