### ISSUE TITLE
PhantomJSEnv.Config: Expose customInitFiles

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#3057]
I just got a warning
```
[warn]  [1] /project/PhantomJS2Env.scala:5:
[warn]      constructor PhantomJSEnv in class PhantomJSEnv is deprecated: Use the overload with a PhantomJSEnv.Config.
[warn]      class PhantomJS2Env(jettyClassLoader: ClassLoader,
[warn]                         ^
[warn] 1 warning found.
```

My override is this:
```scala
// https://github.com/scala-js/scala-js/issues/1555
class PhantomJS2Env(jettyClassLoader: ClassLoader,
                    phantomjsPath: String = "phantomjs",
                    addArgs: Seq[String] = Seq("--debug=false"),
                    addEnv: Map[String, String] = Map.empty,
                    override val autoExit: Boolean = true)
    extends PhantomJSEnv(phantomjsPath, addArgs, addEnv, autoExit, jettyClassLoader) {

  override protected def vmName: String = "PhantomJS2"

  private val consoleNuker = new MemVirtualJSFile("consoleNuker.js")
    .withContent("console.error = console.log;")

  override protected def customInitFiles(): Seq[VirtualJSFile] =
    super.customInitFiles() :+ consoleNuker
}
```

In order for me to workaround #1555 using `PhantomJSEnv.Config` I'll need `customInitFiles` added to it.

**Comment by sjrd** [comment]
I don't see why. All you need to do is change your constructor to call the super constructor with a `PhantomJSEnv.Config` (and probably also *take* that `Config` as argument, which will overall be a simplification). You can keep your `override protected def customInitFiles()`. There's no more reason to put it in the `Config` than there was to put it as a constructor parameter before.

**Comment by japgolly** [comment]
That seems a bit strange to me. Why refactor only some of the config into a Config class and have people use a mixture of inheritance and composition? Wouldn't it make sense to the rest of the config into the Config class too?

**Comment by sjrd** [comment]
Because `customInitFiles()` is not part of the *configuration* of an JSEnv. It is part of the *implementation* of a JSEnv. By changing `customInitFiles()`, you are defining an entirely new JSEnv, whose implementation happens to leverage the JSEnv-internal API `customInitFiles()`. As a *user* of the environment, this is not an API you should see.

In fact, as a user of the environment, there is *already* an API to add JS files to be executed on startup. It's just calling `.loadLibs(...)` on the instance of the `JSEnv`. (that's 0.6.x, in 1.x it would be passing more elements in the `Seq[VirtualJSFile]` in the call to `comJSRunner`)

What you are doing there is really implementing an additional `JSEnv` to talk to PhantomJS 2. To do this you use internal APIs. It so happens that the implementation differs from `PhantomJSEnv` for v1.x only by overriding that method. But you're not *configuring* `PhantomJSEnv`.

**Comment by japgolly** [comment]
I understand your reasoning. Thanks :+1:
