### ISSUE TITLE
Add compiler error for using Await

### ISSUE THREAD

**Issue by tgiddings** [scala-js/scala-js#3127]
#1996 and #186 state that Scala.JS is unable to use `Await` by design. However, the fact that it is by design is very unapparent since it fails with a "referring to non-existent method" error pointing to a function in `scala.concurrent.impl.Promise` At a glance, this looks like a binary incompatibility between Scala.JS and Scala versions rather than a Scala.JS design decision. It would be much more clear if the compiler emitted an error such as "Await cannot be used since it has no JavaScript equivalent" or similar.

Also, does the lack of `Await` mean that there is no way to time-out a test if the test code takes too long (e.g. gets stuck in an infinite loop)? This is precisely the scenario where I find myself using `Await`.

**Comment by andreaTP** [comment]
You are free to implement your `Await` for a number of special and limited scope use cases.
 `referring to non-existent method` is a meaningful sentence to say that Await does not exists in Scala.js IMO

Moreover for your use case you have to bear in mind that you are executing on a single thread, so a jump out of a strictloop triggered by an external event is not ***directly*** possible if you do not use async calls or a custom circuit-breaker.

**Comment by sjrd** [comment]
I sympathize with wishing for a nice compile error when using `Await`. However, there is technically very little we can do about it, I'm afraid. When *compiling* a Scala.js library or application, references to the Scala standard library are looked up in the same way as when compiling for the JVM (this is only for the std lib), which means that `Await` is simply there.

One thing we could do is have our build throw away the definition of `Await` in the IR, so at least the non-existent linking error would directly refer to `Await` instead of `scala.concurrent.impl.Promise`.

**Comment by gzm0** [comment]
Couldn't we special case `Await` (just like we special case `Enumeration`) and simply complain? We probably want to think well about this (special casing stuff). But if many people run into it, it might improve developer experience significantly (and reduce "support load").

Imagine something like this:

```
[error]:xx:yy You may not use Await in Scala.js since JavaScript does not support blocking. See scala-js.org/errors/no-await for details.
    val x = Await.result(...)
            ^
```

**Comment by sjrd** [comment]
We could do that, indeed.

**Comment by andreaTP** [comment]
in case please go for a `warning` please ...

**Comment by sjrd** [comment]
Why a warning? It can never possibly work.

**Comment by gzm0** [comment]
If we emit a warning, we need a way to silence it. A warning implies any of the following:

a. it is sometimes OK to do this
b. the compiler cannot warn in all possible cases

This is would not be an occurrence of case (b), so it would need to be case (a). But case (a) implies that there needs to be a way to silence it (also, I don't think it is ever OK to do this, so not a case (a)).

**Comment by andreaTP** [comment]
what if I provide an implementation of `Await` that work in my context?
(i.e. at the moment I'm locally injecting a custom `Await` on a per-package basis https://github.com/akka-js/akka.js/blob/master/akka-js-actor-tests/js/src/test/scala/akka/actor/Await.scala but this modification can prevent me to refactor this code better ... )

**Comment by sjrd** [comment]
If you have your own `Await`, it's not `scala.concurrent.Await` (here it's `akka.actor.Await`). Obviously we wouldn't be blacklisting the *name* `Await`. That would be completely mental. It would only be the std lib's `scala.concurrent.Await`.

**Comment by andreaTP** [comment]
Exactly, this change will prevent me from providing a refactored code for `scala.concurrent.Await` later on....

**Comment by sjrd** [comment]
You could not do that in any sane way. You will depend on ordering properties of the classpath, which is bad. Moreover, if you did do it anyway, your  `Await` would leak to users of your library, which could then be even more confused by the specific restrictions that it has, and that might not meet their expectations.

Basically, don't do that.

**Comment by andreaTP** [comment]
I have several specific places where II can safely do it without leaking to my users (i.e. akka-actor-tests).
I'm not at all in favor of having a so specific compiler exception and if you really want to do that I kindly ask you if you could at least make it configurable (i.e. can be disabled by a compiler flag or something alike).

**Comment by sjrd** [comment]
If it doesn't leak to your users, then having your own `Await` instead of `scala.concurrent.Await` also does not leak to users. That means there is no good reason to want the std lib namespace instead of your namespace, and the latter is cleaner in any case.

What you are doing (or wishing to do) is a hack. A compiler is never obliged to keep "supporting" hacks. Stick to the clean solution you have now with your own namespaced `Await`, and everything will be fine.

**Comment by andreaTP** [comment]
I'm not asking any kind of support, I'm simply arguing that a special case like this doesn't sound to me to justify an Exception.
There are more and more upcoming features in Javascript itself that can potentially enable the implementation of 'Await' (i.e. https://webkit.org/blog/7846/concurrent-javascript-it-can-work/ ) in defined environments at least and I do not see any compelling reason to completely block it at a compiler level.
I encourage a more soft approach using a 'warning' or a user message that is not a blocker.

Btw this is not correct:

> You may not use Await in Scala.js since JavaScript does not support blocking.

Javascript perfectly support blocking code, at your own risk of course, but it is nicely executed :-)

**Comment by tgiddings** [comment]
@sjrd 
>  I sympathize with wishing for a nice compile error when using Await. However, there is technically very little we can do about it, I'm afraid. When compiling a Scala.js library or application, references to the Scala standard library are looked up in the same way as when compiling for the JVM (this is only for the std lib), which means that Await is simply there.
> 
> One` thing we could do is have our build throw away the definition of Await in the IR, so at least the non-existent linking error would directly refer to Await instead of scala.concurrent.impl.Promise.

Can you clarify why it is not possible for the linker error to point to `Await` or `Await.result` without tampering with the IR? From what you say, it sounds like the std lib is given special treatment, but the linker error still points too a method in the std lib?. If it does get special treatment, is it feasible to reduce its special treatment so that linker errors are the same as for when normal dependencies are used without Scala.JS versions? e.g.
```
[error] Referring to non-existent class java.time.Instant$
[error]   called from com.robocubs4205.cubscout.Main$.main()scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   com.robocubs4205.cubscout.Main$
[error] Referring to non-existent method java.time.Instant$.now()java.time.Instant
[error]   called from com.robocubs4205.cubscout.Main$.main()scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   com.robocubs4205.cubscout.Main$
```
(example of removing scalajs-java-time from the dependencies of one of my projects)

Even if `Await` isn't given a specialized error message (something I still advocate for), a linker error like the above is more likely to prompt someone to look for a library that provides `Await` (Even though they won't find one, they'll understand what the issue is) whereas the current one is more likely to prompt trying a handful of different combinations of versions of Scala and of the ScalaJS plugin to see if one fixes the incompatibility (that doesn't actually exist). A change that makes the linker output "normal" errors for missing Scala library objects would be useful for if Scala adds other features that can't be implemented in JavaScript or if there are other current library features that can't be used (I haven't seen any documentation to indicate that, but also none to indicate Await being unusable).

@andreaTP 
>There are more and more upcoming features in Javascript itself that can potentially enable the implementation of 'Await' (i.e. https://webkit.org/blog/7846/concurrent-javascript-it-can-work/ ) in defined environments at least and I do not see any compelling reason to completely block it at a compiler level.

An error for trying to do something impossible can always be removed if said thing becomes possible, but for know, it isn't possible, and the way the compiler currently fails (it will fail regardless) does not convey the reason for failure in an intuitive manner.

**Comment by sjrd** [comment]
> Can you clarify why it is not possible for the linker error to point to Await or Await.result without tampering with the IR? From what you say, it sounds like the std lib is given special treatment, but the linker error still points too a method in the std lib?. If it does get special treatment, is it feasible to reduce its special treatment so that linker errors are the same as for when normal dependencies are used without Scala.JS versions?

The *linker* does not special-case the std lib in any way. It is the compiler that "special-cases" all things coming from the JDK and the Scala standard library. It special-cases them in that it uses the .class files from the JVM to compile, whereas for normal Scala libraries it uses the ones that are specific to Scala.js.

Note that `java.time` receives *exactly* the same treatment as the std lib, since it contains things normally provided by the JDK. When you link against `java.time` without the appropriate `libraryDependencies`, your code still *compiles*, but fails to link. The only different wrt. `Await` is that, in that case, `Instant` *itself*, which you directly call from your code, is not available. `Await` itself, however, is always available, because its source is in the Scala std lib and its .sjsir file is shipped in `scalajs-library.jar`. It is one of the transitive dependencies of `Await` which is not available, and that is why that one shows up as a linking error. In other words, seeing a linking error about `impl.Promise` *is a perfectly normal error*. Showing an error for `Await` would be not normal, here.

What I am suggesting is to make `Await` itself not available, so that it shows up as the linking error, instead of its transitive dependency. It's not tampering with the IR; it's making it behave the same way as `Instant` if you don't have the proper `libraryDependencies`.

Note that this problem of "a transitive dependency shows up as linking error" is not limited to `Await`. If you use other parts of the Scala standard library that transitively depend on some Java thing which is not available, it is the latter that shows up as linking error. For example, try using a `scala.collection.mutable.WeakHashMap`, and you'll get linking errors related to `java.util.WeakHashMap`.

If we were to go all in with this idea, we should audit the entire Scala standard library to throw away the .sjsir of all the things that transitively depend on some will-never-be-supported parts of the JDK. Besides `Await` and `WeakHashMap`, things that come to my mind are `scala.sys` and `scala.io`, but those are slated to be extracted from the Scala std lib into separate libraries anyway (possibly in 2.13 or else in 2.14), so they are less of a problem. Even that would be sub-optimal, since we wouldn't be checking whether *other* Scala libraries publish artifacts that transitively depend on non-available JDK things.

This is why we have never done anything `Await`: it is not alone in its predicament. There is an unbounded number of other things that suffer from the same issue. I am willing to special-case `Await` only because it seems to be the one thing that confuses people the most in practice. From an "in-universe" perspective, it doesn't make any sense, and I would never do that.

**Comment by tgiddings** [comment]
I used the term "tampering with the IR" since you said
> One thing we could do is have our build throw away the definition of `Await` in the IR, so at least the non-existent linking error would directly refer to `Await` instead of `scala.concurrent.impl.Promise`.

Going into this, I thought ScalaJS reimplemented large parts of the Scala Standard library to avoid JVM native code in order to make it work with JavaScript. It looks now like the Scala standard library is compiled wholesale by ScalaJS instead, correct? If so, that makes this error make a lot more sense to me.
> This is why we have never done anything about Await: it is not alone in its predicament. There is an unbounded number of other things that suffer from the same issue.

Would a note in the docs to check if ScalaJS supports a feature when seeing this kind of error help? I don't see a place where such a  note clearly fits, though.

**Comment by sjrd** [comment]
> It looks now like the Scala standard library is compiled wholesale by ScalaJS instead, correct?

Yes, that's right.

> Would a note in the docs to check if ScalaJS supports a feature when seeing this kind of error help?

We should probably have a page explaining linking errors in general, and in what situations they can appear.

**Comment by sjrd** [comment]
I believe it would be best to leave this out of the core compiler plugin. It should be fairly straightforward for someone interested to implement it as a [scalafix](https://scalacenter.github.io/scalafix/) linting rule.
