### ISSUE TITLE
Enable GCC for OutputMode.ECMAScript2015

### ISSUE THREAD

**Issue by laughedelic** [scala-js/scala-js#3181]
Based on my [question](https://gitter.im/scala-js/scala-js?at=5a07b68f51915d962afbd867) on Gitter and @sjrd's [reply](https://gitter.im/scala-js/scala-js?at=5a07f5d186d308b755da315d):

> The ES2015 output still deactivates Closure, at the moment. For a long time Closure did not support ES2015 so we had deactivated it. **We need to revisit that one of these days.**

So the issue is for "revisiting" this topic 😄  Also if anybody can point me to some relevant documentation to read, please do.

**Comment by Atry** [comment]
That would help https://github.com/scala-js/scala-js/issues/2675

**Comment by sjrd** [comment]
The main issue is to manage to upgrade our dependency on GCC first, to a version that can handle ES 2015. I have a wip branch at https://github.com/scala-js/scala-js/compare/master...sjrd:upgrade-gcc. I don't remember why I go stuck. Feel free to pick it up.

Note that this targets `master` so Scala.js 1.x. Upgrading GCC in the 0.6.x branch is close to impossible due to the JDK 6 support constraint. In addition, fiddling with the code emitter is much easier in 1.x than in 0.6.x.

**Comment by ngbinh** [comment]
Thanks, will take a look
