### ISSUE TITLE
Concise literal object construction

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#3189]
1) some js libraries (vue, vuex, ) expect/enforce use of literal objects as parameters
and that makes `@ScalaJSDefined` classes unusable in such cases

2) currently type-safe literal construction is rather verbose:

option - A
https://www.scala-js.org/doc/interoperability/types.html
`Literal object construction using an Scala object interface`

option - B
https://www.scala-js.org/doc/interoperability/sjs-defined-js-classes.html
`Anonymous classes`

in both A and B cases one have to express the same idea twice:
```
  @ScalaJSDefined
  trait mutations extends js.Object {
    def increment(state: state) 
    def decrement(state: state) 
  }
  val mutations = new mutations {
    def increment(state: state) = state.count+=1
    def decrement(state: state) = state.count-=1
  }
```

3) instead, it would help to have perhaps a new annotation:
```
@ScalaJSLiteral
object mutations extends js.Object {
    def increment(state: state) = state.count+=1
    def decrement(state: state) = state.count-=1
}
```

which would de-sugar into the current "say twice" representation

**Comment by sjrd** [comment]
The `trait Mutations` + `val mutations = new Mutations { ... }` is the recommended *typesafe* thing to do. Note that it does *not* express the same thing twice. The trait is the type declaration, expressed once in a library. The second is at call site, and the typechecker will ensure that it conforms to the declared type in the library.

Your suggested option does not provide typechecking, unlike the above, since there is no existing library-defined type definition to check against. If you're not going to typecheck things against an interface, you might as well do:
```scala
val mutations = new js.Object {
  def increment(state: state): Unit = state.count += 1
  def decrement(state: state): Unit = state.count -= 1
}
```
which already works today, and is even shorter than your suggestion.

I see nothing that needs changing. You already have all the tools that you are asking for.

**Comment by Andrei-Pozolotin** [comment]
1) yes, makes sense, and works, verified, thank you.

2) related to the original "`@ScalaJSDefined` classes unusable as literal": 
what do you think about introduction of something similar to:
```
js.Object.toLiteral() // flatten, sanitize
```
to allow  re-use of `@ScalaJSDefined` instances, 
* for both "normal use" inside scala-js 
* and also for rendering as parameters for external js libs expecting literals

**Comment by sjrd** [comment]
I don't think that's a good idea. It would encourage a style which is neither JavaScript-ish (where literals would be used directly) nor Scala-ish (because it is inherently not type-safe).

If you really really want it for yourself, you can define it easily as:
```scala
def toLiteral(obj: js.Object): js.Object = {
  val objDyn = obj.asInstanceOf[js.Dynamic]
  val result = js.Dynamic.literal()
  for (prop <- js.Object.properties(obj))
    result.updateDynamic(prop)(objDyn.selectDynamic(prop))
  result
}
```

**Comment by Andrei-Pozolotin** [comment]
great, thank you.
