### ISSUE TITLE
Use a shaded copy of closure-compiler

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3193]
**Was: Put closure behind a private classloader?**

It seems that `closure-compiler` copies guava symbols which can lead to problems when newer versions of guava are required. Notably selenium suffers from this, see #3164.

The big hammer solution could be to put closure-compiler behind it's own class loader. However, I'm unsure whether we can do this without requiring an sbt plugin for the sbt plugin.

**Comment by schmitch** [comment]
actually I already stumbled upo that.
and I think it's way better to use shading than private classloaders.
I used scala-js and a new version of closure (long ago) (we dropped it in favor of angular2 as of know, until we have a path forward for sjs).

Here is how it could work:
https://github.com/envisia/sbt-closure/blob/master/build.sbt#L51

Instead of doing everything in one build, this can be also made in a seperate project (which will make stuff easier, publishLocal, etc..)
The good thing is, is that you can use a namespace which would never ever lead to any problems. And you do not need to deal with any shady class loading problems.

**Comment by sjrd** [comment]
Thanks for the suggestion. It might be an easier path forward, indeed.

**Comment by eatkins** [comment]
This issue potentially breaks any plugin that relies on a new version of guava, like [sbt-source-format](https://www.github.com/swoval/sbt-source-format). I worked around this by using a custom classloader: https://github.com/swoval/sbt-source-format/commit/8b285d22935e140dd18c777b5dda8e8c8394a6e8. While the workaround isn't that bad, it was quite a pain to figure it out since I don't know much about the sbt plugin ClassLoaders. I'm guessing that most other plugin authors would run into trouble debugging this as well.

**Comment by nafg** [comment]
I guess #3516 would solve this?
