### ISSUE TITLE
JSEnv OS environment variables handling

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#3273]
1) the following snippet, which affects `NodeJSEnv`, `JSDOMNodeJSEnv`

https://github.com/scala-js/scala-js/blob/master/nodejs-env/src/main/scala/org/scalajs/jsenv/nodejs/AbstractNodeJSEnv.scala#L137

```scala
    // Node.js specific (system) environment
    override protected def getVMEnv(): Map[String, String] = {
      val baseNodePath = Option(System.getenv("NODE_PATH")).filter(_.nonEmpty)
      val nodePath = libCache.cacheDir.getAbsolutePath +
          baseNodePath.fold("")(p => File.pathSeparator + p)

      System.getenv().asScala.toMap ++ Seq(
        "NODE_MODULE_CONTEXTS" -> "0",
        "NODE_PATH" -> nodePath
      ) ++ env
    }
  }
```

2) apparently has these implicit assumptions:
* there is only one global node.js installation
* there are some "magic" workarounds (NODE_MODULE_CONTEXTS, and can not remove them)
* Config.env provided variables are secondary, and must not interfere with NODE_PATH
* there is no way to override NODE_PATH without breaking libCache dependency

3) these assumptions contradict with different use cases, when:
* there are multiple local per-project node.js installations
* there is no single global NODE_PATH environment variable
* NODE_PATH is provided per-project via Config.env only
* "magic" workarounds should be explicitly set by user, not baked into code
* external OS environment System.getenv should NOT be injected in tests at all
* libCache dependency should not interfere with Config.env

then, here is our dilemma:
A) if you are happy with current approach, we have to re-write JSEnv, and do not want that
B) otherwise, can you please make NodeJSEnv environment variables handling more flexible?

so, which will it be?

**Comment by Andrei-Pozolotin** [comment]
additional request about logging: 

here:
https://github.com/scala-js/scala-js/blob/master/js-envs/src/main/scala/org/scalajs/jsenv/ExternalJSEnv.scala#L114

```scala
    protected def startVM(): Process = {
      val vmArgs = getVMArgs()
      val vmEnv  = getVMEnv()

      val allArgs = executable +: vmArgs
      val pBuilder = new ProcessBuilder(allArgs: _*)
      pBuilder.redirectErrorStream(true) // merge stderr into stdout

      pBuilder.environment().clear()
      for ((name, value) <- vmEnv)
        pBuilder.environment().put(name, value)

      logger.debug("Starting process: " + allArgs.mkString(" "))

      pBuilder.start()
    }
```

it would really help to log **both vmArgs and vmEnv**

**Comment by sjrd** [comment]
`AbstractNodeJSEnv`, `NodeJSEnv` and `JSDOMNodeJSEnv` have indeed some assumptions.

Some things can be configured trough the `Config`, for example a full path to the Node.js executable, which should address your concern about "there is only one global node.js installation".

Some other things are not supported by `Config`, because it's hard to cater for every single use case. When that happens, you can instead declare a subclass of `NodeJSEnv` that `override`s some of its public or protected methods. For example, both methods that you mention are protected non-final, so it should be easy to override them if you want to customize them to your specific needs.

If some specific additional configuration is required by many users, we can see whether we can add it to `Config`. But before that, try and address your use case with a subclass of `NodeJSEnv`.

There is also ongoing work (#3255) to significantly reorganize and simplify the `JSEnv`s in Scala.js 1.x, which should make it easier to implement custom `JSEnv`s for specific requirements.

**Comment by sjrd** [comment]
> B) otherwise, can you please make NodeJSEnv environment variables handling more flexible?

Basically, this is what we provide you with the many non-final protected methods, which you can override to suit your needs.

**Comment by Andrei-Pozolotin** [comment]
1. ok, got it, will re-implement JSEnv, please close this, thank you.

2. having just tried to re-implement JSEnv, got another question:
can you please drop/reduce use of path-dependent types in #3255: 
currently, where things could be re-used - you essentially force duplication

3. based on your conversations in #3255, it looks like we will have to
re-implement JSEnv, again, later. just curious: any time frame for when this is stable?
or should we go back to 0.6.x (if 1.X takes another year)? contradictions, contradictions! :-)

**Comment by sjrd** [comment]
Re 2: AFAICT, in #3255 there are no path-dependent types anymore.

Re 3: #3255 is supposed to be the last breaking change to the `JSEnv` API, which will be part of 1.0.0-M3. When migrating to 1.0.0-M3+, you will indeed have to adapt custom `JSEnv`s. In the meantime, it is recommended that you use 0.6.x if you want some stability. I was mentioning #3255 only to show that we were already in the process of addressing quite a lot of the concerns you raised. Unfortunately, doing so means introducing a non-negligible amount of breaking changes, which is why it is done in the 1.x branch.

**Comment by Andrei-Pozolotin** [comment]
ok, good, thank you.
