### ISSUE TITLE
junit-runtime - proper events notification

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#3276]
1) motivation: 
* need to propagate `junit-runtime` testing events to an external runner

2) problem:

I can not find a way for proper events notification, 
except by parsing log output for `started` / `finished` from
https://github.com/scala-js/scala-js/blob/master/junit-runtime/src/main/scala/org/scalajs/junit/JUnitExecuteTest.scala

3) reason being:
* by your design?
* by your omission?
* by me missing the obvious?

**Comment by sjrd** [comment]
Our JUnit mimics the original JUnit for the JVM. It doesn't do anything more by design.

Is our implementation behaving differently than the JVM one, regarding what you are trying to do? If yes, can you provide a reproduction?

**Comment by Andrei-Pozolotin** [comment]
1. yes your JUnit is close enough to JVM

2. the problem I have is when trying to make a custom runner
https://github.com/random-scalor/scala-js-junit-tools/blob/master/src/main/scala/com/carrotgarden/sjs/junit/ScalaJS_Suite.scala#L93

3. and this is what it takes to recover test/method `started/finished` events:
https://github.com/random-scalor/scala-js-junit-tools/blob/master/src/main/scala/com/carrotgarden/sjs/junit/Notificator.scala#L152

4. namely, by parsing logger output from
https://github.com/scala-js/scala-js/blob/master/junit-runtime/src/main/scala/org/scalajs/junit/JUnitExecuteTest.scala

**Comment by sjrd** [comment]
I'm afraid what you're doing is actually the "right" way to do it.

We are very tightly constrained by the API of the [sbt test interface](https://github.com/sbt/test-interface). We literally *cannot* extend it.

**Comment by Andrei-Pozolotin** [comment]
in this case can you please make these logger strings it into public api, i.e.
```
val regexTestRunStarted = "Test run started"
val regexTestRunFinished = "Test run finished"
val regexMethodRunStarted = "Test ???need-marker-here??? started"
val regexMethodRunFinished = "Test ???need-marker-here??? finished"
```

or at least annotate/document it so it stays constant

**Comment by Andrei-Pozolotin** [comment]
BTW, just noticed you back ported `TestAdapter` to 6.x - thank you so much,
`ScalaJSFramework` was a real pain

**Comment by Andrei-Pozolotin** [comment]
ok, then how about introducing a `magic logger` 
with marker interface extending `sbt.testing.Logger`, since SBT api takes logger array
```
task.execute( handler, loggerArray )
```
you can always add a logger with "special mission", then you are decoupled from both JUnit and SBT, 
and `magic logger` will produce the required events as strings

?

**Comment by sjrd** [comment]
I think you are missing the big picture, here: by design, we *only* offer what the original JUnit offers. Nothing more. The scope of our implementation of JUnit is limited to that, and will not be extended beyond that point.

The only purpose of us reimplementing JUnit is that people (and ourselves in particular) can *cross-compile* tests written in JUnit. Adding features wrt. JUnit/JVM does not serve that purpose.

There are other testing frameworks designed specifically for Scala and/or Scala.js, which can provide more features. But our JUnit strictly sticks to the original one.

From the other issues you have posted recently, I think you need to understand one thing: in general, the scope of the whole Scala.js project is pretty strictly limited. The scope is basically:

* We design a dialect of Scala, named Scala.js, which compiles Scala to JavaScript
* We develop the compiler for that language
* We interoperate with JavaScript by allowing everything that ECMAScript 2015 can do, but nothing more
* And we include everything that we need to transitively test every other thing that is in the repo, but nothing more

In particular,

* we do not add APIs to the standard library if they can be built on top of the existing ones ; that is a job for additional libraries
* we do not add language features if they can be built on top of the existing ones ; that is the job of macros and/or custom compiler plugins
* we do not add sbt plugin features if they can be built on top of the existing ones ; that is the job of separate sbt plugins in other repos
* we do not extend the APIs of the projects we *port* (i.e., the Scala standard library and JUnit) beyond what is strictly necessary to make them work in the context of Scala.js (e.g., `.toJSArray` on Scala collections)

When you have an idea, a problem, a perceived limitation, *ask on Gitter first*. There are hundreds of people lurking around who will be able to help you there, and discuss your idea/problem/limitation. This issue tracker is reserved for confirmed bugs, and enhancements that either clearly fall within the scope defined above (e.g., add types for the JavaScript `Map` type), or have been discussed on Gitter and either @gzm0 or myself have given a general approval like "this could be desirable". Even for bug reports, most Scala.js users, including experienced ones, first quickly ask on gitter to know whether it is indeed a bug, which is worth reporting, or whether it is the correct behavior.

If you post everything as an issue on this tracker, it is way too much overhead for me, personally. I am only one person. I cannot afford the time it takes to write lengthy arguments about why we won't add that or that feature, coming from tens of thousands of Scala.js users. That's why there is a community: so that the community can help each other achieving common stuff, and only escalate to the maintainers, *which are a very critical bottleneck*, for more complicate stuff that the community has agreed should be escalated.

I am sorry if this feels unfriendly. When basically 1 person is in charge of a 100,000+ LoC codebase used by tens of thousands of people, it is the only way for things to stay manageable.

**Comment by Andrei-Pozolotin** [comment]
1. I appreciate your efforts for this project, thank you
2. I got your point of view, thank you very much for elaborating
3. next time, please say "no" without any lengthy explanation
4. gitter or not - this issue is a "bug" for me, hence the post here
5. I understand you do not want to implement it, feel free to close, I will hack around, as usual

**Comment by Andrei-Pozolotin** [comment]
BTW:
this is a great explanation, probably your could place it into issue template
https://github.com/blog/2111-issue-and-pull-request-templates
