### ISSUE TITLE
fastOptJS should invalidate when relevant build.sbt settings change

### ISSUE THREAD

**Issue by ryan-williams** [scala-js/scala-js#3283]
cross-/re-posting https://github.com/scalacenter/scalajs-bundler/issues/206#issuecomment-360835179

1. run `fastOptJS`
1. change `scalaJSUseMainModuleInitializer`
1. `reload` in sbt console
1. re-run `fastOptJS`
1. observe that JS file is not modified
1. run sbt `clean`
1. re-run `fastOptJS`
1. new JS file reflects change from 2.

perhaps other settings have this issue as well?

**Comment by sjrd** [comment]
The relevant settings are in fact:
* `scalaJSModuleInitializers` (influenced by `scalaJSUSeMainModuleInitializer`)
* `scalaJSLinkerConfig`

**Comment by sjrd** [comment]
This might not be feasible in 0.6.x, because `scalaJSLinkerConfig` contains a Scala function somewhere inside, and therefore it cannot be serialized nor compare for equality. We fixed that in 1.x, specifically to be able to address this invalidation issue at some point.

**Comment by jarekratajski** [comment]
Slowly getting there:

https://github.com/scala-js/scala-js/compare/master...jarekratajski:fix3283

At the moment it is implemented only for scalaJSModuleInitializers.
1. I think there should be also same kind of  check for `scalaJSUseMainModuleInitializer`
2.  scalaJSLinkerConfig will be bigger problem as `previous` works only for `TaskKey`nd not `SetingsKey` and at the moment I have no clue how workaround this.

**Comment by sjrd** [comment]
1. `scalaJSUseMainModuleInitializer` shouldn't be a problem, since it feeds into `scalaJSModuleInitializers`. If the former changes, the latter will change too, and hence things will be invalidated.
2. That is indeed unfortunate. Maybe what we could do is define a separate `scalaJSLinkerConfigTask: TaskKey[LinkerConfig]`, which would always be equal to `scalaJSLinkerConfig` (in all scopes). I think this can be done with
  `Def.derive(scalaJSLinkerConfigTask := scalaJSLinkerConfig.value)`
  in the `globalSettings` of the plugin. It's ugly, but should work.

**Comment by gzm0** [comment]
Assigning this to post-v1 because:
- We cannot do this in 0.6.x
- We definitely should do this.
- We can do it in a backward compatible manner.
