### ISSUE TITLE
Get ' "my_method" is not a function ' under some circumstances 

### ISSUE THREAD

**Issue by umnick84** [scala-js/scala-js#3389]
Hello.

I faced the problem with exporting static methods from companion object. Imaging I have a code:
```
@JSExportTopLevel("MyClass")
class MyClass {
 //some other methods
}
object MyClass {
  @JSExportTopLevel("MyClass.myMethod")
  def someMethod(): Int = 1
}
```

then in JS I can call `MyClass.myMethod` just fine. But once class MyClass extends a trait, I can't call this method any more, I get an error `MyClass.myMethod is not a function`.

Is there something you can fix or find workaround for this?

**Comment by sjrd** [comment]
Hello,

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

(This is a generic message.)
