### ISSUE TITLE
When JSDOMNodeJSEnv fails due to a lack of jsdom, SBT reports success

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#3393]
I've got a unit test designed to fail with `55 should === 0`.
Ensure `jsdom` isn't installed or available.

`sbt test` with `jsEnv = JSDOMNodeJSEnv` reports success where as the default `jsEnv` does not.

Here is a reproduction repository:
https://github.com/japgolly/jsdom-bug

**Comment by sjrd** [comment]
Thanks for the report. After some analysis, I've the culprit is here:
https://github.com/scala-js/scala-js/blob/efc5b8652952f6c8446e10d8a451f259669332af/test-adapter/src/main/scala/org/scalajs/sbttestadapter/TestAdapter.scala#L56-L61

This `recoverWith` is supposed to deal with cases where the testing interface bridge is not present on the classpath, but it casts its net way too large. It will in fact swallow any top-level exception thrown before the Com bridge spawns.

**Comment by sjrd** [comment]
So in fact the code above was correct. The `runner.runner.future.map` was supposed to take non-zero exits into account. But it turned out that that future was not correctly completed as failed. The fix awaits in #3394.

**Comment by sjrd** [comment]
Fixed in 25d4057a1c8195b63fdd50c56bbe171615b834a2.

**Comment by japgolly** [comment]
Legendary! As always, thanks a lot!
