### ISSUE TITLE
format BigDecimal with `f` broken in 0.6.24

### ISSUE THREAD

**Issue by nafg** [scala-js/scala-js#3404]
```scala
  def formatDollar(amount: BigDecimal) = f"$$$amount%,.2f"
  formatDollar(15)
```
crashes in 0.6.24 with `java.util.IllegalFormatConversionException: f != java.math.BigDecimal`

**Comment by sjrd** [comment]
Did it work with previous versions!? Big numbers have never been supported by `String.format`.

**Comment by nafg** [comment]
Yes, it works fine in 0.6.23

**Comment by sjrd** [comment]
Ah, no, it never really worked. It was silently converting your `BigDecimal` into a `Double` before applying the formatting. That was a very bad bug, because it would silently drop precision. You can restore the exact same behavior as before by using `${amount.doubleValue}%...` instead of `$amount%...`.

Now at least it correctly tells you that it cannot deal with `BigDecimal`. This is a progression, actually.

**Comment by sjrd** [comment]
@nafg Can I close this issue?

**Comment by nafg** [comment]
I added .toDouble so it doesn't affect me anymore... and I don't want to
start a debate about definitions of brokenness...
Is there a ticket for implementing BigDecimal?

**Comment by sjrd** [comment]
I've created #3407 to record known limitations.
