### ISSUE TITLE
Move the remaining stubs in a separate repo

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3450]
Now that `TestUtils` is gone, `scalajs-stubs` is not necessary to the core repo anymore. I believe we should move it to a separate repo. It's tiny at this point; it only contains definitions for `@JSExport`, `@JSExportAll`, `@JSExportTopLevel` and `@EnableReflectiveInstantiation`.

I suggest to put it under `"org.portable-scala" %% "scalajs-stubs"`.

It's interesting to note that the Community Build already uses a couple hacks to treat scalajs-stubs as if it were from a different repo than scala-js/scala-js:
https://github.com/scala/community-builds/blob/f7cea0b957407c94291778578727ccd213832088/configs/community.dbuild#L208-L218

Does that make sense?

**Comment by gzm0** [comment]
Yes, it does make sense to split it into a separate repo, not sure if portable scala is the right location for it. I think this should live under Scala.js as it is specific to Scala.js. portable-scala should re-unite feature sets, not spread them the way I understand it.

**Comment by sjrd** [comment]
Yes, makes sense. So then it would be in a repo scala-js/scala-js-stubs, with an artifact name of `"org.scala-js" %% "scalajs-stubs"` (which is actually its current module ID, which is nice because it will be transparent for users).

**Comment by gzm0** [comment]
Hmmm... what happens with this, if two major Scala.js versions have source incompatible annotations?

**Comment by sjrd** [comment]
Then we'll have to publish a new version of scalajs-stubs, with equally source-incompatible annotations.

**Comment by gzm0** [comment]
The more I think about it, the less this makes sense to me, TBH. Who is going to benefit from this being moved to a separate repo (and versioned independently)? The way I see it:

- Worse for using, since they need to manage another version (i.e. stubs 1.2.3 is for SJS 1.7.3, etc.).
- Worse for releasing, since a separate versioning needs to be done.
- Worse for developing, since two projects need to be kept in sync (stubs should always be in sync with real annotations).

Why does the community build want it to "look" like it is coming from another repo?

**Comment by gzm0** [comment]
Ah, ok. That makes sense, yes.
