### ISSUE TITLE
`Class` does not have a method `getCanonicalName` 

### ISSUE THREAD

**Issue by Daxten** [scala-js/scala-js#3452]
see #741

**Comment by sjrd** [comment]
I don't think we want to support this. Use cases for `getCanonicalName` can typically be replaced by `getName`. Supporting `getCanonicalName` would mean more metadata in the final .js code, which means bigger .js output.

**Comment by andreaTP** [comment]
given the specification: https://docs.oracle.com/javase/specs/jls/se7/html/jls-6.html

the total definition of Canonical Name is the following:

> Every primitive type, named package, top level class, and top level interface has a canonical name:
- For every primitive type, named package, top level class, and top level interface, the canonical name is the same as the fully qualified name.
Each member class, member interface, and array type may have a canonical name:
- A member class or member interface M declared in another class C has a canonical name if and only if C has a canonical name.
In that case, the canonical name of M consists of the canonical name of C, followed by ".", followed by the simple name of M.
- An array type has a canonical name if and only if its component type has a canonical name.
 In that case, the canonical name of the array type consists of the canonical name of the component type of the array type followed by "[]".
A local class does not have a canonical name.

Given this the total amount of meta-information IIUC is a Bool value `isCanonical` computed at compile time (given where the definition happened).

**Comment by sjrd** [comment]
No, it's more complicated than that. Inner classes have periods instead of `$`s, for example:
```scala
scala> classOf[java.util.Map.Entry[_, _]]
res2: Class[java.util.Map.Entry[_, _]] = interface java.util.Map$Entry

scala> res2.getCanonicalName
res3: String = java.util.Map.Entry

scala> res2.getName
res4: String = java.util.Map$Entry
```
So a `Boolean` is not enough. In general, we need to duplicate the name strings.

**Comment by andreaTP** [comment]
from a brief search looks to be the only exception to the rule e.g. replace the mechanically inserted `$` with a `dot`.

e.g. the canonical name is the name that you will use in an `import` clause

**Comment by andreaTP** [comment]
understood, you will need a separate string to store it ... isn't it erased at compile time if it's not used at all?

**Comment by sjrd** [comment]
> isn't it erased at compile time if it's not used at all?

Not metadata, no. It would in theory be possible, but we don't have the infrastructure for it, and it would significantly complicate the linker.

**Comment by Daxten** [comment]
Would it be possible to create a special compile error, which indicates that something is on-purpose not supported?

**Comment by sjrd** [comment]
Not really. Because this is a linking error, and the linker is not supposed to know any of this. In fact, you could feed it a different library that *would* support some things that are not supported by the standard one, and it should be able to roll with it. I think @andreaTP does something like that `Await.result` in tests. There was some discussion at #3127.

**Comment by andreaTP** [comment]
@sjrd got it, thanks for explanation.

@Daxten you can eventually provide an implementation of the method. E.G. A typeclass on `Class` with the method should be feasable.

The method implementation itself can be provided as a macro, getting the CanonicalName straight from Java. Note that this approach has limitations.

Can you elaborate on the use case so that we can provide a better suggestion?

**Comment by sjrd** [comment]
I'm going to close this as a won't fix. It can be reopened if someone convinces me otherwise.
