### ISSUE TITLE
hitEnd does not behave correctly

### ISSUE THREAD

**Issue by jwstegemann** [scala-js/scala-js#3454]
The following code behaves differently in scala.js and on the JVM. I assume the JVM work correctly:

```
val regex = """\d\d\.?\d\d\.?\d\d\d\d""".r

def check(s: String) = {
  val m = regex.pattern.matcher(s)

  if (m.matches()) println("ok")
  else {
    m.reset(s) 
    if (m.hitEnd()) println(s"$s partially matches")
    else println(s"$s does not match")
  }
}

check("")
check("1")
check("17")
check("17.01")
check("17.01.2018")
check("1701")
check("17a")
check("a")
check(" ")
```

on the JVM:

```
partially matches
1 partially matches
17 partially matches
17.01 partially matches
ok
1701 partially matches
17a does not match
a does not match
  does not match
```

in scala.js:

```
does not match
1 does not match
17 does not match
17.01 does not match
ok
1701 does not match
17a does not match
a does not match
  does not match
```

**Comment by sjrd** [comment]
Thanks for the report.

It looks like [`hitEnd()` is not even trying to do the right thing](https://github.com/scala-js/scala-js/blob/0ff1fbe3f7a003482c3b785b6a374202f44f47c1/javalib/src/main/scala/java/util/regex/Matcher.scala#L205-L206). I believe we misunderstood the very contract of that method when we implemented it 5 years ago.

The problem is, JavaScript doesn't have any similar feature. So in fact the correct contract of that method simply cannot be implemented.

I'm afraid you'll have to look for a custom solution, for example [this one from StackOverflow](https://stackoverflow.com/a/41580048/1829647). It is not universal, though. Some regexes cannot be handled by this solution.

For Scala.js, what it means is that I think we should *wipe* that method altogether. Because it is currently completely wrong, and we have little hope to correctly implement it any time soon. Instead of doing the wrong thing at run-time, it should fail to link.
