### ISSUE TITLE
Type inference failure of Option#getOrElse into a union type

### ISSUE THREAD

**Issue by guersam** [scala-js/scala-js#3515]
scala.js version: 0.6.26
scala version: 2.12.8

Having trouble with `Option` and union type like below: 
https://scastie.scala-lang.org/ECfikjmsQaSLfXpR7E57lQ

```scala
import scala.scalajs.js
import scala.scalajs.js.|

def foo(x: String | Int): Unit = println(x)
def fooNoUnion(x: String): Unit = println(x)

foo("bar") // ok
foo(Option("bar").getOrElse("baz"): String) // ok
fooNoUnion(Option("bar").getOrElse("baz")) // ok

// type mismatch;
// found   : Object
// required: String | Int | Double | scala.scalajs.js.Array[Any]
foo(Option("bar").getOrElse("baz"))

// type mismatch;
// found   : Any
// required: String | Int | Double | scala.scalajs.js.Array[Any]
foo(Option(1).getOrElse(0))
```

**Comment by sjrd** [comment]
Hi @guersam,

Although I sympathize with the inconvenience of having to add `: String`, I don't think there is anything we can do about this. Type inference is done by the type checker of scalac, which is not in Scala.js' hands. The nature of Scala.js' `|` type is such that it is a second-class citizen for type inference, because it does not actually induce a *subtyping* relationship. I don't see anything that could be done either on Scala.js' side nor on Scala's side to improve this situation.

The only consolation is that Scala 3 (aka Dotty) has proper union types baked into the type system, and therefore will not suffer from this issue.

I'm going to close this issue as won't fix/upstream, since the only possible fix is in upstream Scala.

**Comment by guersam** [comment]
I hoped that there were some way to fix it by modifying the union type encoding, but it's fine as there are a workaround. Yes Scala 3 might be the rescue... Scala.js is so cool BTW, and thanks for such a detailed explanation!
