### ISSUE TITLE
Documentation: empty-parens needed for method exports

### ISSUE THREAD

**Issue by bbarker** [scala-js/scala-js#3522]
Adding a note and rationale to `Exporting methods` (I don't know the rationale) [here](https://www.scala-js.org/doc/interoperability/export-to-javascript.html) would be useful. See e.g. https://stackoverflow.com/questions/54030522/how-to-properly-use-jsexport-methods-in-a-jsexporttoplevel-object-in-scala-js-fr/54030523#54030523

**Comment by sjrd** [comment]
Issues for the documentation should go to https://github.com/scala-js/scala-js-website/issues, as they would be fixed in that repo.

Also note that http://www.scala-js.org/doc/interoperability/export-to-javascript.html already documents exporting getters as properties, which is what happens with methods that don't have any parentheses.
