### ISSUE TITLE
Adding comments header for compiled & optimized files

### ISSUE THREAD

**Issue by DirkToewe** [scala-js/scala-js#3563]
Adding a plain text to the header of a compiled and optimized `.js`-file may be useful for multiple reasons:
  * Adding metadata like version, compiler settings, date, ...
  * Adding execution information, e.g. `#!/usr/bin/env node`
  * Adding a License, Author, Support info, URL, ...

Such a plain text header could easily be added to a `.js` in a postprocessing step after compilation. However, if I am not mistaken, the Sourcemap would also have to be remapped. That seems to me like a quite involved chore.

This brings me to the following feature request: Would it be possible to add a "headerString" option to the SBT plugin, such that such a header can be added more easily?

**Comment by sjrd** [comment]
For context: we used to have something similar, called `scalaJSOutputWrapper`, which allowed to inject arbitrary code before and after the output of Scala.js. It was deprecated in https://github.com/scala-js/scala-js/pull/2775/commits/c8681b6b117f27947ced3802087817e0fafa9bee because it causes unsoundness: the code is injected in an unknown scope controlled by the compiler, and things can unexpectedly go wrong.

In general, we cannot allow injection of arbitrary code. We could consider the injection of comment-only code , though.

**Comment by DirkToewe** [comment]
Comments alone would already be very helpful to me. The `#!/usr/bin/env node` shebang may be useful to other but I don't have a use case for it.

**Comment by DirkToewe** [comment]
Yes that would still be a useful feature to me. Maybe the simplest way to implement this would be a config entry that adds a specified number of empty rows as headspace? That would make all the aforementioned use cases feasible using a postprocessor script (without the SourceMap headache).

**Comment by gzm0** [comment]
Hah, that's an interesting approach :) @sjrd what do you think about that? It would even allow for the shebang use case without sacrificing the guarantee that the generated code is correct.

**Comment by sjrd** [comment]
I would much rather insert actual JS comments (their grammar isn't that hard to check, to make sure that no one is inserting anything but comments). That way reasonable use cases are addressed at the core.

And if someone really wants the shebang thing, they can insert a one-line comment, then do the patching.
