### ISSUE TITLE
Re-evaluate JSEnv Input modeling

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3616]
Forcing every input to be of one type is a potential smell ([example](https://github.com/scala-js/jsdependencies/pull/23/files#diff-2946990a42be4eefbeb99cc3ca3f2a94R405)). We should think about this hard once again before we commit to it.

**Comment by sjrd** [comment]
I'm not sure what you mean. IIUC, you're saying that `Input` should allow cases like "load this script; then load this CommonJS module". I agree we should be able to do that, but I don't understand how that relates to the linked example: jsdependencies needs scripts for every file anyway, because it needs to assign the loaded modules to global variables.

**Comment by gzm0** [comment]
Oh, right. Yeah, I didn't realize that (for JSDependencies). So this is currently only theoretical.

**Comment by gzm0** [comment]
Also see: #3488 (comment)

**Comment by gzm0** [comment]
One thought I had today is that we currently fail to model the ability of being included as different type of module (i.e. inclusion autodetect or also just side effecting modules). Maybe we need a bitmap kind of thing insted.

**Comment by gzm0** [comment]
A couple of thoughts about this:

Assumption: `JSEnv` input can only be loaded for its side-effects.

Therefore:
- Order matters
- Globals matter
- Exports do *not matter*

Therefore, a `JSEnv` needs to know:
- Loading order
- Whether to evaluate in global scope.
- Required syntax / keywords inside code.

Order is trivially addressed by providing inputs in a `Seq`. As for loading, it seems we have two possibilities:
 
- Specify requirements (e.g. "NeedsGlobalScope", "NeedsExports", "NeedsES2015Export").
- Specify supported inclusions (e.g. "SupportsScript", "SupportsCommonJS", "SupportsES2015").

The "supporting" case makes it possible for inputs to declare that they support being included in multiple ways based on auto-detection.

This would allow us to:
- Have heterogeneous input (scripts and modules).
- Avoid awkward inclusion of `NonNativeJSTypeTestNatives.js`.

So my current idea is having a bit-map like `LoadModes` type with values:
- `Script`
- `CommonJSModule`
- `ESModule`

And:
```scala
final class Input(file: Path, allowedModes: LoadModes)
```

@sjrd WDYT?

**Comment by sjrd** [comment]
TBH the specification you propose seems overkill to me.

* I don't understand the need to give an input file that can be imported in several ways, only to let the JSEnv decide how to import it. Why not specify how to import it from the start? If the best way to import it depends on the JSEnv, that's a pretty special requirement that is best addressed in any given build. Actually I'm pretty sure most builds only run and test in one specific JSEnv; they don't test with different JSEnvs. Our build is rather special in that respect.
* I don't understand what "requirements" are good for. What is a JSEnv going to be if the requirements are not met? Currently the underlying engine will throw a `SyntaxError`, which seems like an appropriate response to me. If a JSEnv should proactively detect unmet requirements, that's also quite difficult to implement, even impossible: how would `NodeJSEnv` detect whether ES2015 exports are supported? It would have to inspect the command-line arguments *and* the run-time version of Node.js, and it wouldn't even be able to future-proof itself for a future version of Node.js that supports them by default.

I thought all we really needed to do here is that instead of a homogeneous list, we need a heterogeneous list where each file is specified as either a script, CommonJS module or ES module (rather than *all* files being uniformly specified as scripts, CommonJS modules or ES modules).

**Comment by gzm0** [comment]
That is a fair point. So we can settle for the much simpler:

```scala
object Input {
  final case class ScriptToLoad(script: Path) extends Input

  final case class ESModuleToLoad(module: Path)
      extends Input

  final case class CommonJSModuleToLoad(module: Path)
      extends Input
}
```

And take a `List` of these instead.

In that rename, shall we:

- Remove `ToLoad`
- Rename to actions (e.g. `LoadScript`, etc.)

**Comment by sjrd** [comment]
Probably removing `ToLoad` is the best, i.e., just using `Script`/`ESModule`/`CommonJSModule`.
