### ISSUE TITLE
The global-detection code is incorrect in an ES module for non-Node.js environments

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3677]
The global detection code fallbacks on reading `this` if everything else fails. This is incorrect in an ES module loaded by a browser, because `this` will be `undefined`.

It is unclear what we should do there.

The good news is that this is fixed by construction in Scala.js 1.x, because we don't need any global detection at all.

A workaround is to add the following script in the HTML page, before loading any Scala.js code:
```html
<script type="text/javascript">
var __ScalaJSEnv = { global: window };
</script>
```

**Comment by osxhacker** [comment]
This workaround resloved the first issue for me, but was immediately met with property write errors in both Firefox 68.0.1 and Safari.

What resolved the issue was invoking `patchESModule` (listed below) before test execution.  This allows `fastOptJS` (what I tested with) to produce the linked JavaScript without introducing a dead-lock, something I experienced when attempting to resolve `fastOptJS.value.data` in `Compile` tasks.  The dead-lock appears to be due to `concurrentRestrictions in Global` defined in ScalaJSPluginInternal.scala for my use-case.  Knowing that the `concurrentRestrictions` must be enforced, patching the emitted code during a `Test` task seemed wisest.

Note that the patch logic is specific to what ScalaJS v0.6.28 produces and would need adjustment should the emitted JavaScript vary (such as if `fullOptJS` produces differing code layout).

```
def patchESModule (generated : File) : Unit =
{
    val marker = "// generated - do not edit";
    val code = Source.fromFile (generated, "UTF-8");
    val existingMarker = code.take (marker.length).mkString;

    if (!existingMarker.isEmpty && existingMarker != marker)
        {
        val lines = Source.fromFile (generated, "UTF-8")
            .getLines
            .toSeq;

        IO.writeLines (
            generated,
            Seq (marker) ++
                lines.take (1) ++
                Seq ("var __ScalaJSEnv = { global: window };") ++
                lines.drop (1),

            append = false
            );
        }
}
```

**Comment by gzm0** [comment]
I propose to close this as wontfix.

**Comment by sjrd** [comment]
Yes, that's probably reasonable.
