### ISSUE TITLE
Scala-js-1.0.0-M8: Option not understood: sjsDefinedByDefault

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#3727]
Here is a minimal reproduction (https://github.com/fdietze/scala-js-d3v4/tree/sjsDefinedByDefault):

`build.sbt`:
```scala
name := "scala-js-d3v4"
version := "master-SNAPSHOT"
scalaVersion := "2.12.8"

enablePlugins(ScalaJSPlugin)
scalacOptions += "-P:scalajs:sjsDefinedByDefault"
```

`plugins.sbt`:
```scala
val scalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).getOrElse("0.6.28")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % scalaJSVersion)
```

Building with `0.6.28` works, while `1.0.0-M8` fails with:
```
Option not understood: sjsDefinedByDefault
```

Travis build: https://travis-ci.org/fdietze/scala-js-d3v4/builds/560544812

Must scalajs-projects be subprojects to apply the option as a scalajs setting only? Why does it work with `0.6.28` then?

For reference: https://www.reddit.com/r/scala/comments/786gco/error_bad_option_pscalajssjsdefinedbydefault/

**Comment by sjrd** [comment]
Hello,

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by fdietze** [comment]
I'm sorry for wrongly posting it here. I thought it was a bug, rather than a question. I didn't find any documentation for this behavior. I'm posting it on StackOverflow now....
