### ISSUE TITLE
Allow JSGlobalScope to be used for exporting

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js#3750]
Currently the only way to export top-level functions and values is like this:

```
object MainJS {
  @JSExportTopLevel("jsAppName")
  def jsAppName(): String = ???

  @JSExportTopLevel("actIdNameWrap")
  def actIdNameWrap(): String = ???

  @JSExportTopLevel("removeEvent")
  def removeEvent(time: String) = ???

}
```

Would it be possible to use `JSGlobalScope` for the same purpose? It seems to me annotating an object with `JSGlobalScope` without using `@js.native` and `extend js.Any` would be a possible alternative, resulting in a less verbose code:

```
@JSGlobalScope
object MainJS {
  def jsAppName(): String = ???

  def actIdNameWrap(): String = ???

  def removeEvent(time: String) = ???

}
```

**Comment by sjrd** [comment]
No, that wouldn't make sense. The reason is that exporting to the top-level is not always to the *global scope*. That is only true if we emit a *script*, but not if we emit a CommonJS module or an ES module.

Something that would make sense would be to add an `@JSExportAllTopLevel`, similar to `@JSExportAll`. We could consider that if the proposal gathers enough feedback. I'm not sure it is worth it, though. Reducing boilerplate is typically not a good enough reason to add more stuff to the language.

**Comment by sjrd** [comment]
I'll close as Won't Fix so that it doesn't fill in the tracker. But it can be reopened if it gathers enough support.
