### ISSUE TITLE
sbt-plugin's "run" not working as expected

### ISSUE THREAD

**Issue by edadma** [scala-js/scala-js#3812]
I'm using scalajs 0.6.29 and sbt-scalajs-bundler 0.15.0-0.6 with scala 2.12.10 and sbt 1.3.2.

The following code should just echo what is typed:

```scala
import typings.node.{nodeStrings, process}


object Main extends App {

  println( "type something" )

  process.stdin.setEncoding( "utf-8" )

  process.stdin.on_data( nodeStrings.data,
    message => {
      println( s"typed: $message" )
    } )

}
```

which it does if I run it with

```
node target/scala-2.12/scalajs-bundler/main/*js
```

as a console command in the root folder of the project.

If I use the sbt `run` command it just falls through and terminates without waiting for input, though it does print the `type something` prompt.

I'm wondering what I'm missing and whether this is a bug.

**Comment by sjrd** [comment]
If you're not sure whether it's a bug, please ask on Gitter first. And since you're using scalajs-bundler you should probably ask in that project's Gitter channel, and if it is indeed a bug it might be specific to that plugin as well.

I'm going to close this issue as a question. If it turns out it is actually a bug to be fixed in this repo, feel free to reopen.
