### ISSUE TITLE
Optimizer seems to not optimize 2.13 collection operations

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3884]
For example `takeRight` on a `js.Array` (see https://github.com/scala-js/scala-js-env-selenium/pull/106/commits/b9ebeeabacdc5b409a763a37a5f7a78eb8a4296c).

**Comment by sjrd** [comment]
I don't think that it's because it doesn't optimize array operations. I think it's simply that the implementation is completely different in 2.13:
https://github.com/scala-js/scala-js/blob/67953468f1a4c1de5630cc545af555dad5a0b155/library/src/main/scala-new-collections/scala/scalajs/js/ArrayOps.scala#L246
where it clearly relies on JavaScript's `slice`, whereas the 2.12 implementation implicitly delegates to `IndexedSeqOptimized.slice` or some other generic implementation.

If the fact of optimizing something or not changed the runtime behavior, unless hitting undefined behavior, that would be a severe bug (rather than just a missed opportunity for optimization).

**Comment by gzm0** [comment]
Yes, indeed. It seems that it's merely because of the different implementation.
