### ISSUE TITLE
fastOptJS error in scalaz 7.3 with Scala.js 1.0.0

### ISSUE THREAD

**Issue by xuwei-k** [scala-js/scala-js#3953]
- https://github.com/scalaz/scalaz/commit/382bb66e804ef0ec56ff4a4eb3508faebb916d36
- https://travis-ci.org/scalaz/scalaz/jobs/647661630#L513
- https://github.com/scalaz/scalaz/blob/382bb66e804ef0ec56ff4a4eb3508faebb916d36/tests/src/test/scala/scalaz/StreamTTest.scala#L160-L162

```
[error] https://raw.githubusercontent.com/scalaz/scalaz/382bb66e804ef0ec56ff4a4eb3508faebb916d36/tests/src/test/scala/scalaz/StreamTTest.scala(160:33:MethodDef): The signature of scalaz.StreamTTest$$anonfun$$nestedInanonfun$new$111$1.applyOrElse(scalaz.StreamT$Step,scala.Function1)java.lang.Object, which is (List(AnyType, ClassType(ClassName<scala.Function1>)),AnyType), does not match its name (should be (List(ClassType(ClassName<scalaz.StreamT$Step>), ClassType(ClassName<scala.Function1>)),AnyType)).
[error] There were 1 IR checking errors.
[error] (testsJS / Test / fastOptJS) There were 1 IR checking errors.
```

**Comment by sjrd** [comment]
Thanks for the report. I will look into it once we're through with all the release steps.

Since the IR error is in the tests, it probably means that the main artifacts, to be published, are correct. You could comment out the problematic test, and if things pass, then you can safely publish the main artifacts, I believe.

**Comment by sjrd** [comment]
It would help us fix the issue if you manage to provide a minimization.

**Comment by xuwei-k** [comment]
```scala
package example

sealed class StreamT[M[_], A](val step: M[StreamT.Step[A, StreamT[M, A]]])

object StreamT {
  sealed abstract class Step[A, S] extends Product with Serializable

  sealed abstract case class Done[A, S]() extends Step[A, S]
}

object Main {
  import StreamT._

  implicit class AnyOps[A](actual: => A) {
    def mustMatch(f: PartialFunction[A, Boolean]): Unit = {
      val act = actual
      def test = f.isDefinedAt(act) && f(act)
      def koMessage = "%s does not satisfy partial function".format(act)
      if (!test)
        sys.error(koMessage)
    }
  }

  type Id[A] = A

  def x[A](s: StreamT[Id, A]) = s.step mustMatch {
    case Done() => true
  }

  def main(args: Array[String]): Unit = {
    println(x(null))
  }
}
```

**Comment by gzm0** [comment]
Further reduction:

```scala
package example

import scala.language.higherKinds

sealed class StreamT[M[_]](val step: M[Step[StreamT[M]]])

sealed abstract class Step[S]

object Main {
  implicit class AnyOps[A](actual: A) {
    def mustMatch(f: PartialFunction[A, Boolean]): Unit = ()
  }

  type Id[A] = A

  def main(args: Array[String]): Unit = {
    (??? : StreamT[Id]).step mustMatch {
      case _ => true
    }
  }
}
```

Notably: The implicit conversion and the type function seem to be required to reproduce.

**Comment by gzm0** [comment]
So it seems the problem is that we take the param symbols from different locations:
- for the param list, we take them from [`vparamss` in the `DefDef` tree][1].
- for the name, we take them from the [`tpe` of the method symbol][2]

This is (for now), the only difference I can see between the ways we retrieve the types :-/

Both `genParam` and `paramOrResultTypeRef` seem to be calling [`convert`][3] at the end.

[1]: https://github.com/scala-js/scala-js/blob/v1.0.0/compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala#L1723-L1731
[2]: https://github.com/scala-js/scala-js/blob/v1.0.0/compiler/src/main/scala/org/scalajs/nscplugin/JSEncoding.scala#L203
[3]: https://github.com/scala-js/scala-js/blob/v1.0.0/compiler/src/main/scala/org/scalajs/nscplugin/TypeConversions.scala#L94-L127

**Comment by errikos** [comment]
@gzm0 you are right.

However, this seems to be an issue in `scalac` itself. I opened a bug report for it: https://github.com/scala/bug/issues/11884.

**Comment by gzm0** [comment]
Just to confirm my understanding (w.r.t. https://github.com/scala/bug/issues/11884#issuecomment-585291252): The reason we need all this uglyness and patching (and cannot simply use `tpe.params`) is because the refs to the parameters have the wrong types?

**Comment by errikos** [comment]
> Just to confirm my understanding (w.r.t. [scala/bug#11884 (comment)](https://github.com/scala/bug/issues/11884#issuecomment-585291252)): The reason we need all this uglyness and patching (and cannot simply use `tpe.params`) is because the refs to the parameters have the wrong types?

I don't know about "wrong", but I would say that "inconsistent" is a more accurate word. The `Defdef`'s symbol has the correct types (which the patch uses), but `Defdef.vparamss` has the wrong ones.

Plus, the easiest way to do this is to patch the IR Tree after it has been generated, in order to avoid touching the generation process itself, which would probably introduce far more code changes.

**Comment by sjrd** [comment]
PR in scala/scala: https://github.com/scala/scala/pull/8720

**Comment by sjrd** [comment]
The further reduction was a bit too far for 2.13. It fails with 2.12 but does not on 2.13. The following does fail, however:
```scala
package example

import scala.language.higherKinds

sealed class StreamT[M[_]](val step: M[Step[StreamT[M]]])

sealed abstract class Step[S]

object Main {
  implicit class AnyOps[A](actual: A) {
    def mustMatch(f: PartialFunction[A, Boolean]): Unit =
      f.applyOrElse(actual, (_: Any) => false)
  }

  type Id[A] = A

  def main(args: Array[String]): Unit = {
    new StreamT[Id](null).step mustMatch {
      case _ => true
    }
  }
}
```

---

In Scala 3, the bug does not exist. The above test passes. We can also see that the IR of the anonymous function, and of `applyOrElse(Step, Function1)` in particular, is correct:
```scala
class hello.Main$$anon$1 extends scala.runtime.AbstractPartialFunction implements java.io.Serializable {
  constructor def <init>;V() {le / packageBin / mappings 0s
    this.scala.runtime.AbstractPartialFunction::<init>;V()
  }
  def isDefinedAt;Lhello.Step;Z(x: hello.Step): boolean = {
    matchResult1[boolean]: {
      val x1: hello.Step = x;
      return@matchResult1 true
    }
  }
  def applyOrElse;Lhello.Step;Lscala.Function1;Ljava.lang.Object(x: hello.Step, default: scala.Function1): any = {
    matchResult2[any]: {
      val x2: hello.Step = x;
      return@matchResult2 true
    }
  }
  def isDefinedAt;Ljava.lang.Object;Z(x: any): boolean = {
    this.isDefinedAt;Lhello.Step;Z(x.asInstanceOf[hello.Step])
  }
  def applyOrElse;Ljava.lang.Object;Lscala.Function1;Ljava.lang.Object(x: any, default: scala.Function1): any = {
    this.applyOrElse;Lhello.Step;Lscala.Function1;Ljava.lang.Object(x.asInstanceOf[hello.Step], default)
  }
}
```
