### ISSUE TITLE
Provide a "sleep" method returning a Future in js.timers

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3963]
The Scala.js core library provides support for both JS timers and Scala `Future`s.

It seems natural that it should also provide the relevant helpers for their intersection. Notably a `setTimeout`-like method that returns a `Future[Unit]`.

Basically this:

```scala
def sleep(duration: FiniteDuration): Future[Unit] = {
  val p = Promise[Unit]()
  setTimeout(duration)(p.success(()))
  p.future
}
```

Questions:
- Should we add this?
- How should we call it?

**Comment by sjrd** [comment]
> How should we call it?

I believe the commonly used name for such a method is `delay`. Although that usually comes with the ability to delay an existing future, like:
```scala
def delay[A](duration: FiniteDuration)(future: Future[A]): Future[A] = {
  val p = Promise[A]()
  setTimeout(duration)(p.completeWith(future))
  p.future
}
```
For the variant that always returns a unit, `sleep` is probably a better name, even though it might give the wrong intuition (blocking, instead of returning a `Future`). Note that `sleep` can be trivially implemented in terms of `delay`, of course:
```scala
def sleep(duration: FiniteDuration): Future[Unit] =
  delay(duration)(Future.successful(()))
```

> Should we add this?

I don't know. It seems like something largely useful, but I'm worried of feature creep. If we let this one in, aren't we opening the door for all sorts of "useful helpers" like that?

**Comment by japgolly** [comment]
> I'm worried of feature creep. If we let this one in, aren't we opening the door for all sorts of "useful helpers" like that?

+1 here. Not only that, if you put it anywhere outside of `object Future`, then it blesses `Future` in a biased way. cats-effect users want `IO`, ZIO users `ZIO`, scalajs-react users `AsyncCallback`. I think the most unbiased return type in this context would be `js.Promise`, not `Future`.

Ideally it would be best to add a delay/sleep method to `object Future` itself in scala/scala, then add the above implementation here in scala.js IMO.

**Comment by exoego** [comment]
+1
 I found myself often implementing sleep/delay for several projects, since those are useful to implement exponential backoff or similar timing-related feature.

I agree with @japgolly that sleep/delay added in object Future in scala/scala, then ported to Scala.js/Scala native.

**Comment by sjrd** [comment]
The reason `sleep`/`delay` is not *already* in scala/scala is that it is actually impossible to implement it in a way that satisfies everyone on the JVM. On the JVM, you typically want to provide a specific `Scheduler`, because you don't want to create one thread for every `sleep`/`delay`.

I don't see that changing any time soon, so I do not think that adding `sleep`/`delay` in scala/scala realistic.

**Comment by gzm0** [comment]
From what I hear, it almost seems like we should move `scala.scalajs.concurrent` into its own library and provide the functionality there. Of course that would cause the problem that the std lib uses `QueueExecutionContext` as the global `ExecutionContext` in the scalalib :-/

**Comment by sjrd** [comment]
@gzm0 I don't think so. `scala.scalajs.concurrent` provides essential functionality that is advertised by the Scala stdlib in `scala.concurrent`, in a JS environment. That definitely has its place in the JS stdlib.

`sleep` is not essential. The functionality it provides is not advertised by the Scala stdlib.

Conclusions about one don't necessarily hold for the other.

**Comment by gzm0** [comment]
> sleep is not essential. The functionality it provides is not advertised by the Scala stdlib.

That's a fair way to look at it as well (and probably the stance we should take indeed). I personally do not agree with the Scala stdlib not containing a `sleep` function. But indeed, that seems to matter less here than the consistency.

So I guess we close this then?

**Comment by sjrd** [comment]
Yes, I think we can close.
