### ISSUE TITLE
Apply dispatch for Object.hashCode is not according to spec

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3976]
I have just realized that introducing a new IR node for ID hash code does not address the compatibility problem we have created here. My current understanding of the situation is as follows:

1. The Scala.js linker has a bug: It does not respect [`SJSIR 9.25.2`][1] but makes assumptions about the relevant implementations (leaving intrinsics aside for a moment).
2. The Scala.js library has a bug: It relies on the bug in the linker (1) for the implementation of `identityHashCode` to be correct.

Fixing just one of these two bugs will cause a user visible behavior change. Not fixing these bugs, will lower the value of the IR, because it does not behave as specified.

We seem to have the following options:
1. Fix the bugs in 1.0.x
1. Fix the bugs in 2.0.x
1. Change the IR spec (but no code).

IMHO our best course of action here is to do 1, with a bump to the IR version and the linker logging a warning if it is linking against 1.0 IR. Most users will be unaffected, because they just use the sbt plugin, which bumps the library version anyways. More advanced users might be affected, but at this point also should care, since they potentially "see" the bug pair described above.

[1]: http://lampwww.epfl.ch/~doeraene/thesis/sjsir-semantics/#sec-sjsir-apply-runtime-semantics-evaluation

_Originally posted by @gzm0 in https://github.com/scala-js/scala-js/pull/3971#issuecomment-593236225_

**Comment by sjrd** [comment]
I agree we should go with the first option. Since it requires an IR version bump, it should be in version 1.1.0, not 1.0.x.

Concretely, I suggest we do the following:
* We do add an IR node `IdendityHashCode(expr)`
* We change the library implementation of `java.lang.System.identityHashCode` to use that IR node (similarly to how `java.lang.Object.getClass` uses the IR node `GetClass`) -- we can't turn `identityHashCode` itself into a primitive, because it's a JDK method, so its outside contract must be to call that (static) method; not to replace calls to that method with an IR node.
* We add a deserialization hack for `java.lang.System.identityHashCode` in IR version 1.0 that disregards its body, and replaces it with an `IdentityHashCode` node.

The implementation cost of the last bullet is no greater than issuing a warning, and it actually *fixes* the problem instead of warning about it.
