### ISSUE TITLE
classOf[Array[Unit]] is different for JVM and Scala.js 1.0

### ISSUE THREAD

**Issue by ghik** [scala-js/scala-js#4005]
On JVM, `classOf[Array[Unit]].getName` is `[Lscala.runtime.BoxedUnit;`
On Scala.js 1.0 it's `[Ljava.lang.Void;`

This is an obscure corner case but _technically_ a regression in Scala.js 1.0

**Comment by sjrd** [comment]
Hi! This is by design. In Scala.js 1.x, the boxed class corresponding to the primitive class `Unit` is `java.lang.Void` --- just like the boxed class for `Int` is `java.lang.Integer`.

So just like `(5: Any).isInstanceOf[Integer] is true, so is `((): Any).isInstanceOf[Void]` is true.

This change simplified the fundamental design of Scala.js, and we considered it *better* than the JVM behavior. The existence of `scala.runtime.BoxedUnit`, and its observability, is an artifact of compiling for the JVM, not an intentional feature. While we usually favor consistency over improvements, this particular inconsistency was worth it for the design simplification.

**Comment by sjrd** [comment]
See also #3535 for the rationale.

**Comment by ghik** [comment]
Maybe we could list that difference in documentation among other semantic differences?

**Comment by sjrd** [comment]
Yes, indeed. I submitted a PR at https://github.com/scala-js/scala-js-website/pull/491.
