### ISSUE TITLE
Can't load test JS output with Scala.JS 1.x into other envs

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4057]
### Reproduction

1. In the `src/test/scala` of a SJS project, create something and export it. Example:

  ```scala
  import scala.scalajs.js.annotation._
  object X {
    @JSExportTopLevel("example")
    def example() = ()
  }
  ```

2. From sbt run `test:fastOptJS`
3. Load the `blah-test-fastopt.js` file into some other env. With Scala.JS 0.6 the file loads successfully and you can call `example()` where as with Scala.JS 1.0.1 the file fails to load:

```
Uncaught ReferenceError: scalajsCom is not defined
    at new $c_Lorg_scalajs_testing_bridge_JSRPC$ (/home/golly/projects/public/scala-graal/ext-boopickle-test-fastopt-sjs1x.js:13217:5)
    at $m_Lorg_scalajs_testing_bridge_JSRPC$ (/home/golly/projects/public/scala-graal/ext-boopickle-test-fastopt-sjs1x.js:13238:45)
    at new $c_Lorg_scalajs_testing_bridge_TestAdapterBridge$ (/home/golly/projects/public/scala-graal/ext-boopickle-test-fastopt-sjs1x.js:4081:157)
    at $m_Lorg_scalajs_testing_bridge_TestAdapterBridge$ (/home/golly/projects/public/scala-graal/ext-boopickle-test-fastopt-sjs1x.js:4099:57)
    at $c_Lorg_scalajs_testing_bridge_Bridge$.start__V (/home/golly/projects/public/scala-graal/ext-boopickle-test-fastopt-sjs1x.js:2829:7)
    at $s_Lorg_scalajs_testing_bridge_Bridge__start__V (/home/golly/projects/public/scala-graal/ext-boopickle-test-fastopt-sjs1x.js:2814:44)
    at Object.<anonymous> (/home/golly/projects/public/scala-graal/ext-boopickle-test-fastopt-sjs1x.js:42292:1)
```

### Y tho?

One of my OSS projects is https://github.com/japgolly/scala-graal, and one of its features is that you load and evaluate SJS output in the JVM using Graal. React SSR (server-side rendering) of scalajs-react code is my primary use case. Normally you'd only load normal `fullOptJS` output but in the scala-graal tests, I test this behaviour by loading in the test JS output from the JVM tests.

You can play with this yourself if it helps. 
* Branch: https://github.com/japgolly/scala-graal/tree/issue/scalajsCom
* I've saved `ext-boopickle-test-fastopt-sjs06.js` and `ext-boopickle-test-fastopt-sjs1x.js` in the root of that branch for quick inspection
* JS: https://github.com/japgolly/scala-graal/blob/issue/scalajsCom/ext-boopickle/js/src/test/scala/japgolly/scalagraal/ExampleGraalBoopickleClient.scala
* JVM: https://github.com/japgolly/scala-graal/blob/issue/scalajsCom/ext-boopickle/jvm/src/test/scala/japgolly/scalagraal/GraalBoopickleTest.scala#L10

**Comment by sjrd** [comment]
> Normally you'd only load normal `fullOptJS` output but in the scala-graal tests, I test this behaviour by loading in the test JS output from the JVM tests.

Is that something that a user's project would do? Or is it only your test suite that does that? If the latter, could the test suite load the .js file of the `Compile` configuration instead?

As far as I can tell, failing to load this file when `scalajsCom` is not defined is the correct thing to do. The .js file produced in the `Test` configuration has a main method that is designed to use a `scalajsCom`. What should it do if there isn't one? IMO throwing is the expected behavior.

If you are really loading that test file with a no-op `scalajsCom`, as you do in the workaround, you're entering some unspecified territory.

Perhaps, if you really need to load that test .js file, what you really are after is intentionally disabling the default method that communicates with the `scalajsCom`? If yes, you can achieve that very simply with an sbt setting:
```scala
Test / scalaJSUseTestModuleInitializer := false
```
Note that if you do that, trying to execute `test` (or its friends `testOnly` and `testQuick`) will report an error. Those *need* that main method to be activated.

**Comment by japgolly** [comment]
> Is that something that a user's project would do? Or is it only your test suite that does that? If the latter, could the test suite load the .js file of the Compile configuration instead?

The latter. A user should never do what I'm doing in the my library. In my specific case I can't put the code I want to export under `main` because that code is released publically to maven central.

> Perhaps, if you really need to load that test .js file, what you really are after is intentionally disabling the default method that communicates with the scalajsCom?

Like you say in the end, I can't do that because that disables the ability to run the tests, which I still need in that situation.

I've got a simple workaround for my case so I'm happy. I'm now thinking about this quite generally. What I would expect in general is that loading doesn't perform any side-effect, it literally just loads, and that there would be a method like "heyStartTheTestsNow()" that would become available that would only refer to `scalajsCom` on invocation. Running immediately on load enforces an assumption about usage. It would be nice to have a little more freedom by unbaking that assumption, seeing as the cost for doing so is so low.

That being said I think we can all agree this is super low priority. I'm imaging the fix is pretty quick and simple (move init code into method, modify runner to call method after load). If I'm wrong or you're strongly against this for some other reason feel free to close it. It's no problem :)

**Comment by sjrd** [comment]
Unfortunately, it's not that easy. In order to have a method like `heyStartTheTestsNow()` that is optionally callable, it basically needs to be an `@JSExportTopLevel def`. But then the test adapter needs a way to generate a JS file that will call that exported function. The issue is then that it needs to know *how* to call the function, which now depends on whether it's a Script, an CommonJS module or an ES module. And even then---and that's where it gets ugly---the way to correctly do that depends on the specifics of the JSEnv being used.

At this point we're stuck, because the test adapter can't possibly handle every JSEnv in existence. JSEnv being OO, there are an arbitrary number of them in the wild.

In 0.6.x we did have an exported function like that. And it kind of worked, but because of a number of hacks, and there was no guarantee that it would work with an unknown JSEnv somewhere else.

Embedding the start of the test bridge as a main method fixed these issues at the core. Now, the test adapter works with any compliant JSEnv, with any kind of script/module, and even with any crazy custom `jsEnvInput` that someone might throw at it (as long as it doesn't remove the product of `test:fastOptJS`/`test:fullOptJS`, which prevents the execution of the main, see #4054). Going back on this decision would reintroduce the above systemic issues, so that's not really an option.

---

Now, I think you can still achieve what you're trying to achieve with a custom `Configuration`. You would leave the `Test` configuration alone, and let it run the main method so that `test` works. But you'd then add another configuration, which extends `Test`, but disables `scalaJSUseTestModuleInitializer`. You would then load *that* configuration's fastopt.js file in your JVM tests. IMO the `IntegrationTest` configuration built in sbt could fit this use case. You can find the docs on how to enable it [here for sbt in general](https://www.scala-sbt.org/1.x/docs/Testing.html#Additional+test+configurations), which you'll have to complement with
```scala
.settings(
  ...
  inConfig(IntegrationTest)(Def.settings(
    ScalaJSPlugin.testConfigSettings,
    scalaJSUseTestModuleInitializer := false,
  )),
  ...
)
```

**Comment by gzm0** [comment]
@japgolly could you figure this out or do you still need help? Can we close this issue?

**Comment by japgolly** [comment]
Let's close this. It's a super rare scenario, I've got a workaround, and @sjrd has commented that the quick fix that I envisioned isn't feasible, and I don't think this deserves anything more than a quick fix.
