### ISSUE TITLE
@JSExportTopLevel("default") generates invalid JS code on Scala.js 1.0

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#4061]
Also reported in https://github.com/scalameta/scalameta/issues/2051

scalameta 4.3.12, published for Scala.js 1.0.1, seems broken on Scala.js 1.x project while running test:

See https://travis-ci.com/github/exoego/scalajs-util-types/jobs/339579547#L441
```
/home/travis/build/exoego/scalajs-util-types/macros/target/scala-2.12/macros-test-fastopt.js:1
let parseSource,default,parseStat;
                ^^^^^^^
```

Scalameta uses `@JSExportTopLevel("default")`, which was fine with Scala.js 0.6, in https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala#L111-

But it seems that Scala.js 1.0 generates JavaScript with a variable named `default` , which is [keyword in ECMAScript 2015](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/default).

**Comment by sjrd** [comment]
Oh boy.

`@JSExportTopLevel("default")` is meaningful and intended to work when emitting an ES module or, to a lesser extent, a CommonJS module. We need that to be valid at compile-time, otherwise there would be no way to emit a *default export* in an ES module.

It's not meaningful when emitting a Script, though. In 0.6.x, it would be tolerated, because we'd be assigning roughly `global["default"] = something;`, which is valid. However, in Scala.js we create bona fide global variables, with
```js
let default = something;
```
instead. It's better in general, not least because removes the requirement of Scala.js to somehow guess what the global object is. But obviously this breaks down when attempting to export under a name that happens to be a JavaScript keyword.

---

I see several paths forward:

1. Emit an error at link time when trying to export under a JS keyword when emitting a Script. This is the most correct thing to do, but it may be impractical: one may want to export under `default` when emitting an ES module, but still not crash when emitting a Script. Apparently the Scalameta example falls in that use case, because they also export the same thing under a different name.
2. *Ignore* exports to JS keywords when emitting a Script. This is perhaps more *convenient*, but silently ignoring some exports is not very *correct*. We'll have to clearly specify that.
3. Ignore `default` exports when emitting a Script, and report link-time errors for other exports under JS keywords. That's less silent ignoring, while keeping the legitimate use case of exporting under `default` when possible.

@gzm0 WDYT?

**Comment by exoego** [comment]
Are there any workaround for default export with Scala.js 1.x until this issue is fixed?

**Comment by sjrd** [comment]
The issue only happens when emitting a Script, and there's no such thing as a default export in a Script, so I'm not sure what you're asking?

**Comment by gzm0** [comment]
It feels to me like we might need something like `@JSImport` with a fallback but for exports.

Another way to look at this would be to make the behavior options you describe configurable when writing `@JSExportTopLevel` (with probably a bit more semantic meaning).

Just my 2cts for now. Sorry, don't have time to flesh it out.
