### ISSUE TITLE
@JSName on constructor error on Scala.js 1.x

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#4063]
This is bug report of Scala.js 1.x.
The below code was compile-able on Scala.js 0.6.x, but Scala.js 1.0.1 and 1.1 produces compile error:

```scala
import scala.scalajs.js
import scala.scalajs.js.annotation._

@js.native
@JSGlobal
class FetchError protected() extends js.Error {
  def this(message: String, @JSName("type") type_ : String, systemError: String) = this()
}
```

Error message says `FetchError.scala:7:30: vals in Scala classes, traits and objects may not have an @JSName annotation.`
But it is weird because the class `FetchError` extends `js.Error` which extends `js.Object`.

It seems that this error appear only against `@JSName` in consturctor.
`@JSName` in var/def are compile-able on Scala.js 1.x:
```scala
@js.native
@JSGlobal
class FetchError protected() extends js.Error {
  @JSName("val") def value: String = js.native
  @JSName("type") var type_ : String = js.native
}
```

A workaround is to use backquote names instead of `@JSName` annotation.

**Comment by sjrd** [comment]
The error message is not great, that's for sure. It's already less confusing on `master` (so for 1.1.1), thanks to #4056:
```
[error] C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\src\main\scala\helloworld\HelloWorld.scala:14:30: @JSName can only be used on members of JS types.
[error]   def this(message: String, @JSName("type") type_ : String, systemError: String) = this()
[error]                              ^
[error] one error found
```
since at least it doesn't pretend that it's in a Scala class.

It also says `@JSName` can only be used on *members* of JS types. A parameter is not a member. It makes no sense to put `@JSName` on a parameter, since parameter names are not significant.

So it's correct that an error is reported. It was an oversight that it would compile in 0.6.x, since effectively the `@JSName` annotation wasn't doing anything.

Perhaps we can make the error message still a bit clearer than it is? I'm not sure. To me it's clear that a parameter is not a member, but maybe not for everyone?

**Comment by exoego** [comment]
I think the new message is clear enough since method parameter is not a member.
