### ISSUE TITLE
Proposal: Allow @JSImport with a single argument

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4069]
This proposes to allow

```scala
@JSImport("fs")
@js.native
def foo = js.native
```

and expand into

```scala
@JSImport("fs", "foo")
@js.native
def foo = js.native
```

With the advent of JS native members we'll see a lot of code like this:

```scala
@JSImport("fs", "read")
@js.native
def read = js.native

@JSImport("fs", "write")
@js.native
def write = js.native
```

This requires repetition of the name, for no reason. Note that otherwise we infer names from Scala names where possible (`@JSGlobal`'s argument is optional, `@JSName` is optional).

This proposal backports that functionality to `@JSImport` allowing to write the above as:

```scala
@JSImport("fs")
@js.native
def read = js.native

@JSImport("fs")
@js.native
def write = js.native
```

**Comment by sjrd** [comment]
This makes sense, but what I'm afraid of is that it doens't obviously make more sense than the two other alternatives, namely defaulting to `JSImport.Default` or `JSImport.Namespace`.

If we look at the JS syntax for the three alternatives:
```js
// same-name import
import { read } from "fs";
// default import
import read from "fs";
// namespace import
import * as read from "fs";
```
at least we can fairly reasonably rule out `JSImport.Namespace` as the *default*, since it requires an explicit `*` in JS. However, if I see
```scala
@js.native
@JSImport("foo")
object Foo extends js.Object { ... }
```
it is not clear whether it is supposed to mean
```js
import Foo from "foo";
```
or
```js
import { Foo } from "foo";
```
or, in fact, even
```js
import * as Foo from "foo";
```
Perhaps we should rename the `module` argument of `@JSImport` to `from`, and encourage the use of the named argument as:
```scala
@js.native
@JSImport(from = "foo")
object Foo extends js.Object
```
At least that *clearly* rules out the namespace interpretation, and I guess encourages the named-import interpretation reasonably well.

**Comment by gzm0** [comment]
> `import Foo from "foo";`

Ugh... I didn't think about defaults indeed :S

I'm not sure renaming `module` to `foo` gives us enough "bang for the buck". I think it is unambiguous that the first argument is the module.

**Comment by aappddeevv** [comment]
I really like this idea as someone that has to deal with way too much interop. You'll probably never get consensus on default vs named, its alot like trailing comma debate in JS circles. I suggest we just pick one (or perhaps get a vote) and do it. At the very least 1/2 the people will be happier. I'll vote for it being a named import.

The other thing to do is introduce another annotation called @JSNamedImport that only takes 1 argument and uses the variable name as the named import. Sort of like pushing the 2nd argument into the annotation name. I know its another annotation, which is not great.

**Comment by sjrd** [comment]
Coming back to this issue, I believe there is actually an objective argument in favor of defaulting to named import, i.e.,
```scala
@js.native @JSImport("foo")
val bar: Int = js.native
```
would mean
```js
import { bar } from "foo";
```
The argument is that, for default or namespace, there is exactly 1 of each. If we make either of those the default, it reduces boilerplate for at most one `@JSImport` per JS module. For named imports, however, there can be an arbitrary number of them per module. So we save boilerplate on an arbitrary number of `@JSImport` per JS module.
