### ISSUE TITLE
ScalaJS SBT dependency cannot be resolved.

### ISSUE THREAD

**Issue by robertPiro** [scala-js/scala-js#4132]
I have checked the URL for the maven repo and `sbt-scalajs_2.12_1.0/1.1.1/sbt-scalajs-1.1.1.pom` does not exist. 
Setup: As described in ```https://www.scala-js.org/doc/tutorial/basic/index.html```

Always reproducible by calling: `sbt update`

```
sbt:project> ;clean;update
[success] Total time: 0 s, completed 20 Jul 2020, 09:04:41
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.scala-js:sbt-scalajs:1.1.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-js:sbt-scalajs;sbtVersion=1.0;scalaVersion=2.12:1.1.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/robertp/.ivy2/local/org.scala-js/sbt-scalajs/scala_2.12/sbt_1.0/1.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-js/sbt-scalajs_2.12_1.0/1.1.1/sbt-scalajs-1.1.1.pom
[error] Total time: 1 s, completed 20 Jul 2020, 09:04:42
```

**Comment by sjrd** [comment]
sbt-scalajs is an sbt plugin. The `addSbtPlugin` line should be in the `project/plugins.sbt` file, not in the `build.sbt` file.

---

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.
