### ISSUE TITLE
Bad error message when trying to define `apply` in an anonymous class extending js.Function

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4281]
While trying to break our detection of JS functions, I found this:

```scala
@js.native
@JSGlobal("bad")
abstract class BadFunction extends js.Function1[Int, String]

object Test {
  new BadFunction {
    def apply(x: Int): String = "f"
  }
}
```

This fails to compile with the following error:

```
Concrete members of JS native types may only call js.native.
      def apply(x: Int): String = "f"
                                  ^
```

Note that this does *not* happen for other native traits:

```scala
@js.native
trait MyTrait[T] extends js.Object {
  def apply(): T
}

@js.native
@JSGlobal("bad")
abstract class BadMyTrait extends MyTrait[Int]

object Test {
  new BadMyTrait {
    def apply(): Int = 1
  }
}
```

This fails as expected with:

```
A non-native JS class cannot declare a method named `apply` without `@JSName`
      def apply(): Int = 1
          ^
```

**Comment by sjrd** [comment]
We should not even allow extending any subclass of any `js.FunctionN`.

**Comment by gzm0** [comment]
> We should not even allow extending any subclass of any js.FunctionN.

As long as all that stuff stays native, it's probably OK? Or would the expectation for a facade be to define it's own `apply`s? (FWIW, `js.Object`'s compation does that *without* extending the relevant `js.FunctionN`s or even `js.Function`).

**Comment by sjrd** [comment]
I mean, it's not really possible for a `class`, native or not, to truly *extend* a `js.FunctionN`. One cannot create any kind of class (with `class` or `function`) whose instances would be *callable*. Native `object`s can meaningfully provide an `apply` because they're `function`s themselves (they are not of a class that extend `Function`); native `trait`s can define an `apply`, because in practice that means it's a function on which we've patched the other members of the interface. But a `class` can never provide an `apply`.

**Comment by sjrd** [comment]
Hum ... it appears there *is* a way to define a `class` that could provide a call syntax:
```js
>node
Welcome to Node.js v14.15.0.
Type ".help" for more information.
> class Foo extends Function { constructor(...args) { super(...args); } }
undefined
> var f = new Foo("x", "return x + 1;");
undefined
> f(5)
6
> typeof f
'function'
```

**Comment by gzm0** [comment]
Maybe, for now, we should simply disallow non-native subclasses of `js.FunctionN`?

**Comment by sjrd** [comment]
Yes, that sounds reasonable.
