### ISSUE TITLE
Optimize dynamicImports of native calls

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4315]
As discussed in https://github.com/scala-js/scala-js/pull/4262#issuecomment-738698144

**Comment by gzm0** [comment]
To optimize the imports, I need to retrieve the load spec (if any) for classes referenced in a specific method body (in `computeNewAttributes`). But that makes the attributes depend on other things than the method body itself. Options I see:

- Mark the method attributes as "dirty" in this case and always recalculate them (even if the method's version didn't change).
- Defer retrieval to the optimization stage (and abort inlining if the referenced class isn't native or not an import).
- Track method/class dependencies and introduce a pre-UPDATE UPDATE pass.
- Do not do this and wait for somebody to complain.

@sjrd ideas, opinions?

**Comment by sjrd** [comment]
IMO this:

> Defer retrieval to the optimization stage (and abort inlining if the referenced class isn't native or not an import).

is the best way to deal with this. Always dirty could have weird consequences. I'm not sure exactly what your third suggestion means.

Having the optimizer ask for that info and backtrack sounds reasonable.

**Comment by gzm0** [comment]
> I'm not sure exactly what your third suggestion means.

What I meant by that is recording which methods (when calculating attributes) needed information about which classes. If these classes change, invalidate the method attributes. So an overall pass would look like:

- Diff class changes / invalidate method attributes 
- Re-calculate method attributes (currently called UPDATE pass)
- Re-optimize tagged methods (currently called PROCESS pass)

My concern with the defer retrieval is that we need to duplicate some tree matching between update and optimize :-/

**Comment by sjrd** [comment]
> My concern with the defer retrieval is that we need to duplicate some tree matching between update and optimize :-/

To me it seems that that concern would be dwarfed by the added complexity (and impact on performance) of another entire pass.

**Comment by gzm0** [comment]
Well, to be clear, the additional pass would only be on classes, not on the methods. But maybe that is fair. I'll fiddle with it more once I fixed the other mess :P

**Comment by sjrd** [comment]
> would that be a viable option? I can recognize thunks by the common superclass (compiler runtime lib specific name, but we have a lot of precedent for runtime / optimizer collaboration like that).

Yes, that's a possibility. The optimizer can recognize shapes and references to stdlib stuff to do its job. However, it must not assume anything about the semantics of non-stdlib code. It can assume that `scala.scalajs.runtime.DynamicImportThunk` is what it is in the stdlib; but it may not assume that any class extending `DynamicImportThunk` is necessarily emitted for a `js.dynamicImport` and therefore follows the shape and semantics currently emitted by the compiler.

> We need to be extremely careful with these, since they might pull in lots of types too eagerly (depending on the exact usage site).

I don't think this is an issue in practice. Any type `t` appearing in this `.asInstanceOf[t]` will also appear at the call site of the `js.dynamicImport`, if it is actually used. In the above example, this doesn't happen because the result of `dynamicImport` is thrown away, but if you follow it with `.then[Unit](z => println(z))`, then the `.asInstanceOf[int]` also appears in the lambda passed to `then`, which is in the calling module.

So any practical use of `js.dynamicImport` will have the same cast in the calling module than in the called module.
