### ISSUE TITLE
[javalib] Collection.addAll(null) should throw NPE

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#4399]
Ref. https://github.com/scala-js/scala-js/pull/4367#discussion_r563618011

According to javadoc, [Collection.addAll](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#addAll-java.util.Collection-) and [ConcurrentHashMap.KeySetView](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.KeySetView.html#addAll-java.util.Collection-) are expected throw NPE if `collection` itself is `null`.
`col.addAll(null)` is not found in tests, so it may not be tested and implemented.

**Comment by sjrd** [comment]
This is a case of Undefined Behavior because NPEs are undefined behavior. So there is no issue issue, and we shouldn't spend extra cycles to throw NPEs on purpose in those cases.

The difference with `NullRejectingHashMap` and #4398 is that, there, letting through a null key or a null value can destroy the internal invariants of the data structures that use it. For example, relying on the fact that `get(key) == null` unambiguously means that the key was not present in the map. This is the only reason that `NullRejectingHashMap` exists at all.

When the JavaDoc says that an NPE should be thrown when some arguments are null, that's just because it would call a method on that value. In Scala.js that's Undefined Behavior, and we don't test that nor make an effort to make it happen.
