### ISSUE TITLE
JsComponent not found for React-bootstrap ModalHeader

### ISSUE THREAD

**Issue by marcadella** [scala-js/scala-js#4427]
I have defined the following facade for React-bootstrap ModalHeader:
```
package no.uit.sfb.facade.bootstrap.modal

import japgolly.scalajs.react.component.Js.Component
import japgolly.scalajs.react.vdom.{VdomElement, VdomNode}
import japgolly.scalajs.react.{Callback, Children, CtorType, JsComponent}

import scala.scalajs.js
import scala.scalajs.js.annotation.JSImport
import scala.scalajs.js.{UndefOr, undefined}

object ModalHeader {

  class Props(
      val closeButton: UndefOr[Boolean] = undefined,
      val onHide: UndefOr[js.Function0[Unit]] = undefined,
  ) extends js.Object

  @JSImport("react-bootstrap", "ModalHeader")
  @js.native
  object RawComponent extends js.Object

  val componentJS: Component[Props, Null, CtorType.PropsAndChildren] =
    JsComponent[Props, Children.Varargs, Null](RawComponent)

  def apply(closeButton: Boolean = false, onHide: Callback = Callback.empty)(
      content: VdomNode*): VdomElement =
    componentJS(new Props(closeButton, onHide.toJsCallback))(content: _*)
}
```
And I get the following error message:
```
Invalid JsComponent! You've called JsComponent(undefined)
Source: no.uit.sfb.facade.bootstrap.modal.ModalHeader.componentJS (line #23)
```

I have implemented a lot of facades for this library and ModalHeader is the only one causing troubles.

- Bootstrap-react version: 1.4.3
- Scala version: 2.13
- ScalaJS: 1.3.0

**Comment by sjrd** [comment]
Hello,

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by marcadella** [comment]
Thanks for your answer. I do think it might be a ScalaJs bug though!

**Comment by sjrd** [comment]
If you think it's a Scala.js bug, you'll have to give us enough analysis to show that it is at least as likely as the possible alternatives, i.e.:
* An issue in your code
* An issue in scalajs-react
* An issue in React itself

To do this, please try and minimize the issue by removing as much non-Scala.js stuff as possible:
* Get rid of the scalajs-react dependency by directly invoking the underlying React code
* Minimize that as much as possible
* If you can identify the particular call to React that is an issue, replace it by a call to a tiny JavaScript mock that only performs the check that causes the "Invalid JsComponent! You've called JsComponent(undefined)" error.

In the process, you might well discover that the issue is somewhere else.
