### ISSUE TITLE
WrappedSet doesn't handle Long and Char correctly

### ISSUE THREAD

**Issue by tom91136** [scala-js/scala-js#4449]
Tested on ScalaJS 1.5.0/Scala 2.13.5

It seems that the new `WrappedSet` can't handle types that are opaque in JS:

```scala

import scala.scalajs.js.{ WrappedSet , WrappedArray}

'a' == 'a' // true, OK
"a" == "a" // true, OK

WrappedSet(1, 2, 2) //  Set(1, 2), OK

WrappedSet(1L, 2L, 2L) // Set(1, 2, 2), equality broken?

WrappedSet('a', 'a', 'b')  // Set(a, a, b), same, broken
WrappedSet("a", "a", "b") // Set(a, b), OK

WrappedSet('a').contains('a') // false
WrappedSet("a").contains("a") // true

WrappedArray('a').contains('a') // true
WrappedArray("a").contains("a") // true

```
See demo at https://scastie.scala-lang.org/YzPPr0YcSkaPkg4esTUEDQ
This only occurs for the two opaque primitive types.
I think we might need a few more tests for #4070.

**Comment by sjrd** [comment]
By spec, `js.Map` and `js.Set` use the *identity* of the values that are passed to it. Since the identity of Longs and Chars is unspecified (they are primitives and they don't have corresponding values), they may or may not behave in a "sensible" way with Longs and Chars.

There is nothing we can do about it. Don't use Chars nor Longs in places that rely on reference identity. That is true just as much in a Scala `IdentityHashMap` as in a `js.Map`, by the way; it's not specific to JS interop.
