### ISSUE TITLE
1 ULP error when toFloat is called for some long values

### ISSUE THREAD

**Issue by plokhotnyuk** [scala-js/scala-js#4466]
`java.lang.Float.floatToIntBits(37930954282500097L.toFloat)` returns `1527169536` with Scala.js while `1527169537` is expected.

**Comment by sjrd** [comment]
What version of Scala.js are you using? We recently fixed a bunch of floating point related stuff, including float parsing, in 1.5.1.

**Comment by plokhotnyuk** [comment]
[1.5.1 ](https://github.com/plokhotnyuk/jsoniter-scala/blob/66ab6222e162bfd2c99c4c84c7997f7dd7323000/project/plugins.sbt#L6)

[here is a build failure](https://github.com/plokhotnyuk/jsoniter-scala/pull/690/checks?check_run_id=2327811190#step:7:1288)

**Comment by sjrd** [comment]
Thanks. I'll have a look tomorrow.

**Comment by sjrd** [comment]
I cannot reproduce the issue. The following code
```scala
object HelloWorld {
  def main(args: Array[String]): Unit = {
    println(java.lang.Float.parseFloat("37930954282500097") == 3.7930956E16f)
    println(java.lang.Float.floatToIntBits(3.7930956E16f))
    println(java.lang.Float.floatToIntBits(java.lang.Float.parseFloat("37930954282500097")))
  }
}
```
prints
```
true
1527169537
1527169537
```
on JS like on the JVM. I tested with Scala 2.12 and 2.13.

I tested with Node.js v14.15.0 and with Firefox.

Could you provide a more precise reproduction, please?

Could you provide more

**Comment by plokhotnyuk** [comment]
@sjrd the problem is in `toFloat` calls for some long values.

Sorry for inconvenience, I've updated title and description.

**Comment by sjrd** [comment]
Ah yes, that I can reproduce.

The root issue is similar to that of #4035: we currently implement `long.toFloat` as `long.toDouble.toFloat`, but that's not correct when `long` is close to a float midpoint. Unlike #4035 though, the fix should be relatively easy by copy/pasting the implementation of `toDouble` and adapting it for Floats.

**Comment by sjrd** [comment]
Well, of course I spoke too soon. We can't copy paste the `toDouble` implementation, because it relies on the fact all its operations, including the conversions of `lo` and `hi` to Doubles, are lossless, except the very last one. If we copy paste that strategy with Floats, we will immediately lose precision when converting `lo` and `hi` to Floats.

I guess we'll need a strategy similar to what we did for `parseFloat` with a first guess and then a correction. But this time we won't need `BigInteger`s because the input is already in base 2.

**Comment by sjrd** [comment]
Fix available here: https://github.com/scala-js/scala-js/compare/master...sjrd:fix-long-tofloat
I need to add more tests before opening a PR.
