### ISSUE TITLE
Better error message when executing tests with Node missing

### ISSUE THREAD

**Issue by AugustNagro** [scala-js/scala-js#4469]
I was running some tests via the ScalaJSJUnitPlugin, and got this error:

```
org.scalajs.testing.common.RPCCore$ClosedException: org.scalajs.testing.adapter.JSEnvRPC$RunTerminatedException
```

Which was fixed by installing Node. A better error message if Node is not installed would probably be nice.

**Comment by gzm0** [comment]
I think this is a valid request. The first step IMO is to improve `ExternalJSRun` so that it throws a more structured exception:

https://github.com/scala-js/scala-js-js-envs/blob/1262dbee020172fe1b0f47842ed6a4a3edfd332c/js-envs/src/main/scala/org/scalajs/jsenv/ExternalJSRun.scala#L186

Then, we can walk the cause chain in the sbt plugin and look for that exception specifically and improve the message. Similar to this (a bit more complicated though ;)):

https://github.com/scala-js/scala-js/blob/ddd750cdd937e140539f349f04331a6b83dc24e6/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L75
