### ISSUE TITLE
implicit parameters on native js types

### ISSUE THREAD

**Issue by ShahOdin** [scala-js/scala-js#4498]
I did a little experiment and defined a native trait as below:

```scala
trait MyTrait extends js.Object {
  def foo[E <: BaseTrait](enum: E): String
  def bar(enum: BaseTrait): String
  def baz[E <: BaseTrait: MyTypeClass](enum: E): String
  def qux[E <: BaseTrait: MyTypeClass](enum: E): String
}
```

with a basic impl of:

```scala
def apply(): new MyTrait{
      override def foo[E <: BaseTrait](enum: E): String = enum.name
      override def bar(enum: BaseTrait): String = enum.name
      override def baz[E <: BaseTrait: MyTypeClass](endpoint: E): String = {
        enum.name
      }
      override def qux[E <: BaseTrait: MyTypeClass](endpoint: E): String = {
        val _ = implicitly[Usher[E]].somethingCool()
        enum.name
      }
}
```

and exported the case-objects sub-typing `BaseTrait`.

From Javascript I could run:

```
myTrait.foo(myEnum)
myTrait.bar(myEnum)
myTrait.baz(myEnum)
```

just fine but running

```
myTrait.qux(myEnum)
```

gave me an error of the form:

> TypeError: Cannot read property 'uK' of undefined

Comparing `baz` and `qux` it looks like the implicit is simply being erased.

I have no idea how ScalaJS works internally but in my view: 
- either we shouldn't allow context bounds on methods in native js classes
- or perhaps we can somehow get ScalaJs to see and preserve `Enum`'s type to allow it to make the mapping between E and `MyTypeClass[E]` (not sure if that's possible)

**Comment by sjrd** [comment]
By definition of the Scala language, context bounds are just syntactic sugar over `implicit` parameters. Implicit parameters are real parameters, that must be explicitly supplied if called from JavaScript (because JavaScript can't possibly resolved implicits on its own).

I'm afraid all of this is as designed.

**Comment by ShahOdin** [comment]
> just syntactic sugar over implicit parameters
> because JavaScript can't possibly resolved implicits on its own

sure, sure. Shouldn't we therefore disallow implicits in native js traits as I suggested? 

also, it's a bit concerning that the functions with implicit params would just work unless we actually try to do something with that implicit? ie `baz` vs `qux`

**Comment by sjrd** [comment]
> > just syntactic sugar over implicit parameters
> > because JavaScript can't possibly resolved implicits on its own
> 
> sure, sure. Shouldn't we therefore disallow implicit params in native js traits as I suggested?
> 
> > that must be explicitly supplied if called from JavaScript
> 
> or are you suggesting we should keep them around because someone might want to explicitly export them and pass them on to the function? 🤔

Those methods could be designed to be called from Scala.js code, not from JavaScript. In a JS type, there might be methods meant to be called from JavaScript, and methods meant to be called from other Scala.js code. The compiler cannot know that in advance, so on what ground would it prevent those legitimate use cases?

Also, yes, it's not impossible, though less likely, that they are also designed to be called by JavaScript if it has an appropriate value to explicitly give to that parameter. Again, the compiler can't tell.

> also, it's a bit concerning that the functions with implicit params would just work unless we actually try to do something with that implicit? ie `baz` vs `qux` as a scala developer, I am conditioned to expect a function with implicit params that can't be resolved to fail at "call site", not "use site".

That only happens because you're running/testing in fullOpt mode. That's the production mode, which assumes that this kind of bugs doesn't exist, in order to optimize the program. The default is fastOpt, which performs expensive checks to detect those cases and report them as exceptions. It is always recommended to run/test in fastOpt in development and CI (perhaps with fullOpt in addition) to catch these bugs early.
