### ISSUE TITLE
JDK 12+ bug: Referring to non-existent class java.lang.constant.ConstantDesc

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4545]
The following doesn't link with Scala 3 and Java 14+

```scala
object Bug {
  @scala.scalajs.js.annotation.JSExportTopLevel(name = "Init")
  def bug(b: Boolean): String = { if (b) (1: Int) else 1d }.toString
}
```

```
[error] Referring to non-existent class java.lang.constant.ConstantDesc
[error]   called from issues.Bug$.bug(boolean)java.lang.String
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   issues.Bug$
[error] Referring to non-existent class java.lang.constant.ConstantDesc
[error]   called from issues.Bug$.bug(boolean)java.lang.String
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   issues.Bug$
[error] There were linking errors
[error] (Test / fastLinkJS) There were linking errors
```

**Comment by sjrd** [comment]
[`ConstantDesc`](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/constant/ConstantDesc.html) was added in JDK 12. It's a pain because:
* it is a supertype of the boxed class types,
* it is useless except for Java serialization, which is not supported in Scala.js, and
* we *cannot* implement its specification.

There is not much we can do, here.

### Workaround

The only solutions are to prevent the type checker from inferring that useless type:
* Either with explicit type ascription, like `{ if (b) ((1: Int): Double) else 1d }.toString`,
* or, in Scala 3, we could add `ConstantDesc` to [the list of assumed transparent traits](https://docs.scala-lang.org/scala3/reference/other-new-features/transparent-traits.html), like `Comparable`, `Serializable`, and others.

**Comment by DroneEnthusiast** [comment]
Just to fill out the bug report:

- Substituting `Short` or `Byte` into japgolly's repro causes the linker to look for a different Java class: `Constable`
- Substituting `Double` causes the linker to mysteriously fail with no message

**Comment by gzm0** [comment]
@sjrd, I don't quite understand what the problem is with adding support for `ConstantDesc` (without any methods, of course we cannot / don't want to implement the methods).

To address your points individually:

> it is a supertype of the boxed class types,

We have precedent / support for that (e.g. `java.lang.Number`)

> it is useless except for Java serialization, which is not supported in Scala.js, and

So is `java.lang.Serializable`, but we even have IR level support for that (because of Arrays).

> we cannot implement its specification.

I'm unclear about this point. If you mean `resolveConstantDesc`, then yes, of course, if you mean the spec of the type itself, I don't understand why. There doesn't seem to be any strange constraints on equality or anything. Maybe I missed something?

**Comment by gzm0** [comment]
> We have precedent / support for that (e.g. java.lang.Number)

`java.lang.Comparable` is obviously the better comparison (no pun intended) here, because it is an interface, not a class.

**Comment by sjrd** [comment]
> @sjrd, I don't quite understand what the problem is with adding support for `ConstantDesc` (without any methods, of course we cannot / don't want to implement the methods).
> 
> To address your points individually:

Individually, none of them is an issue. It's the combination that makes it problematic. The fact that it is on boxed class types means that it gets inferred even in simple situations. It's not really the boxed classes themselves; just the fact they're *very common* classes. The same issue would happen for any other common JDK class. The fact that it's useless in Scala.js is just annoying in the sense that we face a real issue because of the introduction of something that brings no value to us. But overall none of that would be a problem if it weren't for the last bullet:

> > we cannot implement its specification.
> 
> I'm unclear about this point. If you mean `resolveConstantDesc`, then yes, of course, if you mean the spec of the type itself, I don't understand why. There doesn't seem to be any strange constraints on equality or anything. Maybe I missed something?

Well, I guess we *could* define `ConstantDesc` as an empty interface, without declaring its method `resolveConstantDesc`. However, that's usually something we avoid doing for *interfaces*. If someone else tries to extend that interface, the separate compilation will demand that they implement `resolveConstantDesc` in their class, even though it is not defined in ours. Arguably, we can live with that issue for `ConstantDesc` itself because no one is supposed to extend it other than through `DynamicConstantDesc`, and the latter would itself not be implemented or implementable. It's a bit shady, though. :-s
