### ISSUE TITLE
`js.native` as default arg doesn't compile for top-level method facades

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4553]
```scala
  @js.native
  @JSGlobal("blah")
  def blah(i: Int = js.native): Int = js.native
```

fails to compile with

```
[error] js.native may only be used as stub implementation in facade types
[error]   def blah(i: Int = js.native): Int = js.native
```

**Comment by gzm0** [comment]
Is this a dotty / Scala3 issue? If yes, IIUC, you should report it to the dotty repository.

**Comment by japgolly** [comment]
I didn't think to check Scala 3 but no, I was hitting this with Scala 2.13.

**Comment by gzm0** [comment]
Huh, but aren't top-level methods a Scala 3 thing?

**Comment by japgolly** [comment]
Argh sorry. This is a full example:

```scala
import scala.scalajs.js.annotation._
import scala.scalajs.js

object Test {
  @js.native
  @JSGlobal("blah")
  def blah(i: Int = js.native): Int = js.native
}
```

**Comment by sjrd** [comment]
Oh no! This is really really bad. We actually generate *and call* default accessors of `@js.native def`s! The following code:
```scala
package helloworld

import scala.scalajs.js
import js.annotation._

object Test {
  @js.native
  @JSGlobal("blah")
  def blah(i: Int = 6): Int = js.native
}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    js.eval("var blah = function(i) { return i || 5; };")

    println(Test.blah(10))
    println(Test.blah())
  }
}
```
prints 6, instead of 5. The .sjsir files are:
```scala
module class helloworld.Test$ extends java.lang.Object {
  static native blah;I;I loadfrom global:blah
  def blah$default$1;I(): int = {
    6
  }
  constructor def <init>;V() {
    this.java.lang.Object::<init>;V();
    mod:helloworld.Test$<-this
  }
}

module class helloworld.HelloWorld$ extends java.lang.Object {
  def main;[Ljava.lang.String;V(args: java.lang.String[]) {
    mod:scala.scalajs.js.package$.eval;Ljava.lang.String;Ljava.lang.Object("var blah = function(i) { return i || 5; };");
    mod:scala.Predef$.println;Ljava.lang.Object;V(helloworld.Test$::blah;I;I(10).asInstanceOf[int]);
    mod:scala.Predef$.println;Ljava.lang.Object;V(helloworld.Test$::blah;I;I(mod:helloworld.Test$.blah$default$1;I()).asInstanceOf[int])
  }
  constructor def <init>;V() {
    this.java.lang.Object::<init>;V();
    mod:helloworld.HelloWorld$<-this
  }
}
```
Note that the last line of `main` actually calls `blah$default$1;I`, instead of not providing any parameter.

This means that to fix this, we'll have to:
1. Fix call sites to emit `<UndefinedParam>` for calls to default getters of `@js.native` defs. This will be a *change of behavior* for cases where the default value in the facade does not correspond to the default value of the native function. Since it happens at recompilation of the call site, it's a source breaking change and must go in a minor version.
2. Fix definition sites not to emit the default getters (to allow `= js.native`). Except we can't do that because that would break existing callers, so it would be a binary incompatible change. So we'll have to identify the ones that have `= js.native`, and emit the other ones but not those.

This is going to be so annoying. :confounded:
