### ISSUE TITLE
`String.strip` and variants missing

### ISSUE THREAD

**Issue by tom91136** [scala-js/scala-js#4591]
The stdlib is missing `String.strip` and the related `stripLeading`, `stripTrailing` methods as per the [JavaDoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html):

    Referring to non-existent method java.lang.String.strip()java.lang.String

Is this something that I can send a PR for?
I haven't looked at the actual JDK implementation (I saw that it delegates to different paths for Latin1 and some other static method but I stopped there and didn't look further) so hopefully this isn't an issue.

**Comment by sjrd** [comment]
Hi, and welcome.

Yes, you may send a PR. Make sure not to look at the *tests* of the JDK any more than the implementation.

Tests will have to go in https://github.com/scala-js/scala-js/blob/master/test-suite/shared/src/test/require-jdk11/org/scalajs/testsuite/javalib/lang/StringTestOnJDK11.scala, since those methods were added in JDK 11. Don't forget to test whitespace code points that are supplementary code points, if there are any.

**Comment by tom91136** [comment]
Closed with #4598
