### ISSUE TITLE
Allow shebangs in the header comment

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4596]
I know you explicitly decided against this in https://github.com/scala-js/scala-js/issues/3563 and suggested a workaround. This is a polite request to reconsider :)

I thought to ask again, because the OP of that issue didn't have a use case for shebangs. However, @ChristopherDavenport has created an [sbt plugin for publishing to npm](https://github.com/davenverse/sbt-npm-package) and started publishing CLI apps such as [curly](https://www.npmjs.com/package/curly4s). First-class support for shebangs would be immensely helpful here.

I think even simply allowing _exactly_ `#!/usr/bin/env node` as a valid first line would cover the majority of use cases for shebangs, without being too compromising?

Thanks in advance.

**Comment by sjrd** [comment]
I was going to reply that Scala.js core only deals with standard ECMAScript, and since shebang lines are not standard, we should not support them. But it turns out there's a Stage 3 proposal to make them official in ECMAScript:
https://github.com/tc39/proposal-hashbang
and which is already implemented in Chrome, Firefox, ChakraCore and Safari.

So PR at #4597.
