### ISSUE TITLE
Warn/fail if `ScalaJSPlugin` is enabled but `-scalajs` setting is missing on Scala 3

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4610]
Users frequently set their `scalac` options in sbt using `:=` instead of `++=`. I very publicly made this mistake in https://github.com/lampepfl/dotty/issues/13456. Others do too, for example today a user on Discord and in https://github.com/planet42/Laika/pull/230, where the author of that library wrote:

> Wow, that's the last thing I was expecting as the cause for the issue. Mainly because I would have expected that a build issue would affect Scala.js on any Scala version. I saw a few other projects with similar issues being unresolved for months, so I was concerned it's going to be a bigger kind of investigation :-)

Since you can't fix the root problem, if there's some way to fail more loudly with useful information I think that would be fantastic. The most common failure seems to be that tests appear to hang indefinitely which is extremely confusing.

**Comment by sjrd** [comment]
In my experience, this is a bigger problem than just Scala.js or even `scalacOptions`. Using `:=` instead of `++=` causes all sorts of issues, including erasing `ThisBuild`- and project-level configurations with settings that are more closely scoped.

Perhaps it would be worth escalating that to sbt itself, and have the `:=` warn if it is applied to usual suspects, such as `scalacOptions`, `libraryDependencies`, and so on?

**Comment by armanbilge** [comment]
> Perhaps it would be worth escalating that to sbt itself

It might be, but that feels like a larger and possibly more controversial sort of discussion :) However, in the meantime, if Scala.js can do anything to help users avoid this stumbling block, I think that would be fantastic.
