### ISSUE TITLE
Variable named `await` emitted in ESModule mode

### ISSUE THREAD

**Issue by dispalt** [scala-js/scala-js#4705]
So this code translated to javascript https://github.com/typelevel/cats-effect/blob/series/3.x/kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala#L74-L81 features something like 

```
function $c_lcats_effect_kernel_genconcurrent$memoize$evaluating(await) {
  this.lcats_effect_kernel_genconcurrent$memoize$evaluating__f_await = null;
  this.lcats_effect_kernel_genconcurrent$memoize$evaluating__f_await = await
}
```

Shouldn't we escape that name? Since I think in strict mode its a reserved word?

**Comment by sjrd** [comment]
Does it actually fail to parse?

**Comment by sjrd** [comment]
It seems to be reserved in modules, indeed:
https://262.ecma-international.org/13.0/#sec-keywords-and-reserved-words

**Comment by dispalt** [comment]
By the browser, I think it works, but stricter minifiers like https://github.com/swc-project/swc/issues/5359 apparently don't like it.

**Comment by sjrd** [comment]
There are two aspects to fixing this issue.

First, we should mangle any identifier that happens to be named `await`, like we do for many others at
https://github.com/scala-js/scala-js/blob/722d7246ac45fe12478694e6bf4835bf6ebc67d8/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/NameGen.scala#L350-L372
and similarly at
https://github.com/scala-js/scala-js/blob/722d7246ac45fe12478694e6bf4835bf6ebc67d8/linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/OptimizerCore.scala#L5948-L5964
That is fine, as it is only a codegen change that does not affect semantics.

The other thing is problematic: we must also forbid to use `await` as reference in the global scope. That means adding it to the list at
https://github.com/scala-js/scala-js/blob/722d7246ac45fe12478694e6bf4835bf6ebc67d8/ir/shared/src/main/scala/org/scalajs/ir/Trees.scala#L854-L875
which is tested at
https://github.com/scala-js/scala-js/blob/722d7246ac45fe12478694e6bf4835bf6ebc67d8/compiler/src/test/scala/org/scalajs/nscplugin/test/JSGlobalScopeTest.scala#L329-L338
but doing so is an incompatible change! There could be codebases that already use `await` as a global ref. Either when emitting a NoModule or CommonJSModule, for which it is valid, or even when emitting an ESModule, since apparently browsers don't actually complain.

I am not sure what is the best course of action for the global refs. My best idea so far is to only *warn* about them at compile time (not link time), saying that they may cause downstream `SyntaxError`s when emitting ES modules.
