### ISSUE TITLE
`BigDecimal("1.199999988079071").floatValue shouldBe 1.199999988079071f` fails

### ISSUE THREAD

**Issue by plokhotnyuk** [scala-js/scala-js#4726]
Source of the issue is using of [an intermediate `Double` value with subsequent rounding](https://github.com/scala-js/scala-js/blob/cbe00b116f0ffda90d812e31a9d35ad42571ee3f/javalib/src/main/scala/java/math/BigDecimal.scala#L1523).

**Comment by sjrd** [comment]
Meh, of course it does... 😮‍💨

Is that really a thing to use this method? I'm tempted to switch the implementation to `Float.parseFloat(x.toString())`. `toString()` should be lossless, and `parseFloat` is now correct. It would be slower than a direct implementation, but it seems like an obscure use case.

**Comment by plokhotnyuk** [comment]
Currently Scala.js version of circe and play-json parsers are affected by this issue.

**Comment by sjrd** [comment]
I'm not questioning whether this bug is worth *fixing*. It's a bug, and we fix all bugs.

I'm wondering if doing `java.lang.Float.parseFloat(toString())` is an acceptable implementation. Because it *does* fix the issue (I tried).

Why do circe and play-json use `BigDecimal` to then lose all their precision to *floats*, of all things? Is that the expected fast path people will use in the common case?

**Comment by armanbilge** [comment]
> Why do circe and play-json use `BigDecimal` to then lose all their precision to _floats_, of all things? Is that the expected fast path people will use in the common case?

I can't speak for play-json, but IIRC Circe uses `BigDecimal` for its internal `Json` representation to maintain precision. Of course, a user is then free to write to `decode` that to any numerical type (which may be `Float`).
