### ISSUE TITLE
Optimize JS methods

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4748]
When working on Exports, it seems to me we have potential for inlining a lot of trivial export forwarders. This might have real size impact on export heavy codebases.

**Comment by sjrd** [comment]
There are also a lot of missed optimizations in JS constructors. Because those actually contain user code (not just forwarders). That adds to the reasons to take care of this.

There's nothing hard about this in terms of doing the optimizations themselves. The only difficulty is in integrating this in our incremental handling, since we cannot use their names for identification.
