### ISSUE TITLE
Investigate why tools-sbtplugin tasks fail on Java 16

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4763]
It seems we must still exclude this task on JDK 16. The job "tools-sbtplugin scala=2.12.17 java=16" keeps failing.

_Originally posted by @sjrd in https://github.com/scala-js/scala-js/pull/4761#discussion_r1045048272_

**Comment by sjrd** [comment]
That issue also mentions that it's because of Scala < 2.12.9. And indeed, [its release notes](https://github.com/scala/scala/releases/tag/v2.12.9) mention a fix to that error. It doesn't appear that 2.13.x was affected (no mention in release notes).

I don't think that would be an issue, though, since our scripted tests always use the latest 2.12.x and 2.13.x.
