### ISSUE TITLE
Scala.js 2.11 supported.

### ISSUE THREAD

**Issue by djx314** [scala-js/scala-js#4807]
Since scala-js is dropped Scala 2.11 in scala-js 1.0
And method to change the scala-js version to 0.6 when the cross-build version is Scala 2.11 with JSPlatform?

**Comment by sjrd** [comment]
Hello,

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Discord](https://discord.com/invite/scala) (channel `#scala-js`), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by sjrd** [comment]
Regardless, if you need Scala 2.11, stay on Scala.js 1.12.0. This is the last version that supported Scala 2.11. We expect that if you can afford not to upgrade past Scala 2.11, you can also afford not to upgrade past Scala.js 1.12.0.

**Comment by djx314** [comment]
> 



> Regardless, if you need Scala 2.11, stay on Scala.js 1.12.0. This is the last version that supported Scala 2.11. We expect that if you can afford not to upgrade past Scala 2.11, you can also afford not to upgrade past Scala.js 1.12.0.

Thanks, that I know what I need to do with this problem.
