### ISSUE TITLE
`js.BigInt(0).isInstanceOf[js.BigInt]` is false

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4818]
```scala
import scala.scalajs.js

object Main {
  def main(args: Array[String]): Unit =
    println(js.BigInt(0).isInstanceOf[js.BigInt])
}
```

It seems this is compiled to:
```js
BigInt(0) instanceof BigInt
```

Ideally it should be something like:
```js
(typeof BigInt(0)) === "bigint"
```

but I don't know if this is fair to expect :)

**Comment by sjrd** [comment]
Hum, I agree it's a bit annoying as a user. But since `js.BigInt` is a regular `js.Any` class, that behavior is definitely according to spec. There's no spec reason we should emit a `typeof` test for that class in particular.

Arguably we should have defined is as a `trait` to *forbid* `isInstanceOf[js.BigInt]` in the first place, but I don't think we can change that at this point.

**Comment by armanbilge** [comment]
If you don't mind dumb questions 😇  ... why is `BigInt` different from, say, `String`? At least from this MDN page it seems that `BigInt` is one of the handful types that has its own `typeof` classification. So without knowing anything it _seems_ like it is special to me.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#description

**Comment by sjrd** [comment]
> If you don't mind dumb questions 😇 ... why is `BigInt` different from, say, `String`?

In the Scala.js spec, there's a fundamental difference between classes that extend `js.Any` and classes that don't. The former have JavaScript semantics, while the latter have Scala semantics. They are also called JavaScript classes and Scala classes. All JavaScript classes `C` share the definition that `x.isInstanceOf[C]` is equivalent to `js.special.instanceof(x, js.constructorOf[C])`. All Scala classes `C` share the definition that `x.isInstanceOf[C]` follows the Scala semantics.

Then, there is a finite set of Scala classes that are specified to be *hijacked classes*. They have Scala semantics (they don't extend `js.Any`), but are also guaranteed to be seen by JavaScript as a particular primitive data type. `String` and `Integer` are two of them. A `String` follows all the Scala semantics, but is also guaranteed to be seen by JavaScript as a primitive `string`.

`js.BigInt` does not fall in that category. It cannot, because it extends `js.Any`, and we don't have any spec or precedent for a `js.Any` type that doesn't actually behave like a JavaScript type. It also could not be a hijacked class because that would require it to have guaranteed implementations of all its methods even when the underlying JS does not support it (because it would have Scala semantics). The only thing we should probably have done is make it a `trait`, but that's not a backward binary compatible change.

We could potentially *warn* when trying to do `x.isInstanceOf[js.BigInt]`, noting that this is probably not what the user wants to do.

**Comment by armanbilge** [comment]
Thanks for the detailed explanation! So if I understand correctly:
1. `BigInt` is a rare example of a JavaScript primitive that is not represented by a hijacked class. Another one is `Symbol`.
2. `instanceof` does not work for JavaScript primitives, in JavaScript itself.
3. Because the other common primitives are represented by hijacked classes, this gives the _impression_ that `isInstanceOf` works for JS primitives. It doesn't. It just _happens_ to work for primitives that are represented by hijacked classes.

Suffice to say: when you are working with JS stuff, Scala semantics don't apply. 🙂 In my case, I actually wanted `typeof` all along, but I was led astray by (3).
