### ISSUE TITLE
Ability to remap `@JSImport`s at linking time

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4837]
An interesting alternative to bundling is loading dependencies from a CDN. [esm.run](https://esm.run/) for example serves dependencies as minified, bundled ESM modules.

The catch is that import statements need refer to the CDN urls. If you control all the `@JSImport`s used by your application this is fine, but in general libraries will not want to hard-code a particular CDN into their imports. So ideally there would be a way to remap the imports at application linking time.

Many browsers offer an ["importmap"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) feature to achieve this kind of remapping. Still, I think this is an interesting feature for Scala.js itself, because it allows to deploy "self-contained" JS files that would work in any browser that supports ESM as well as Node.js (or Deno), without requiring additional configuration to remap imports.

**Comment by sjrd** [comment]
That sounds like something that could be done outside the core, by preprocessing the `IRFile`s consumed by the linker. They can be customized with the `Compile/scalaJSIR` task, which is a `Seq[IRFile]`. Each `IRFile` can be mapped to an adapter `IRFile` that applies the preprocessing in its [`tree`](https://github.com/scala-js/scala-js/blob/9667b6a3b9ff4ca921ae03a2a823592b5e2bcae7/linker-interface/shared/src/main/scala/org/scalajs/linker/interface/unstable/IRFileImpl.scala#L50) method.

**Comment by armanbilge** [comment]
Thank you for the pointers, that was quite straightforward actually :)

I do still think this is a compelling, works-out-of-the-box alternative to dealing with JS bundlers and personally I'd love to see this graduate to a core feature.
1. Implementing outside of core relies on `unstable` APIs.
2. It's harder to get traction with non-userland-extensible tooling such as scala-cli.
3. IDK what I'm doing when it comes to compilery stuff 😆

**Comment by sjrd** [comment]
The good thing about something separate, though, is that it can iterate until the best design is found. It could be an external sbt plugin. If and when the design stabilizes and the feature gets traction, we can consider whether it's worth putting in the core.

If we want to put it in the core straight away, we have to spend upfront time discussing the perfect design, because it can never change afterward.

(`unstable` APIs can break now and then, but they usually last for several release cycles)

**Comment by gzm0** [comment]
Is this a candidate for a linker plugin? (for context: we've been toying with this idea for years, but never had use cases to design an API / interface against).

**Comment by Quafadas** [comment]
Arman did SBT : https://github.com/armanbilge/scalajs-importmap and published a library that dealt with the heavy lifting 🙏 .

From that starting point, PRs have also been merged into in mill,  scala-cli and mdoc. 

I'm wondering for the sake of hygiene; could this issue be closed? It's one less in the repo, and if the desire to suck it into the core were to re-emerge, it would be because of some quite concrete use case that motivates that "ideal" design...

**Comment by sjrd** [comment]
Indeed, it looks like this is now addressed in the various repos.

Feel free to reopen (or comment) if we're still missing something.
