### ISSUE TITLE
Linker emits modules with colliding names on case-insensitive filesystems

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4855]
So first of all, this almost definitely a user error. But maybe it's in scope to provide a more helpful error?

I have a reproducer in https://github.com/armanbilge/sandbox/commit/e5e14fd627666c2450eb918322e03affd1a43d2a, but it will only work on a case-insensitive file system (such as macOS).

```
sbt:sandbox> app/run
[info] Running Main.
TypeError: $j_Main.$s_LMain__main__AT__V is not a function
    at file:///Users/armanbilge/code/sandbox/app/target/scala-2.12/app-fastopt/Main.js:4:9
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[error] org.scalajs.jsenv.ExternalJSRun$NonZeroExitException: exited with code 1
[error] 	at org.scalajs.jsenv.ExternalJSRun$$anon$1.run(ExternalJSRun.scala:200)
[error] stack trace is suppressed; run last app / Compile / run for the full output
[error] (app / Compile / run) org.scalajs.jsenv.ExternalJSRun$NonZeroExitException: exited with code 1
[error] Total time: 0 s, completed Apr 20, 2023, 3:18:12 PM
```

You can encounter this when using:
1. a case-insensitive file system
2. two classes with the same case-insensitive name in different compilation units e.g. `object Foo` vs `object foo`
3. some form of small modules that causes both classes to be emitted in their own file

The "different compilation units" bit is actually pretty important. In the same compilation unit, scalac would warn about this. In different compilation units on the JVM, the classes can peacefully co-exist on the same classpath by living in different folders/jars. But in Scala.js, because all the files are emitted by the linker into the same folder, we can run into trouble.

**Comment by sjrd** [comment]
Thanks for the report. I'm not so sure it's a user error. It is definitely a user error when the two like-named classes end up in the same classpath entry. But nothing says that if they come from different classpath entries, that they should clash.

Now one might argue that putting two classes that differ only by their case in two different classpath entries is dubious at best, and I would agree with that, but that's no excuse for the linker not to deal with it, AFAICT. Especially since the problem surfaces as an artifact of how module splitting generates internal module names.

IMO this is a bug.
