### ISSUE TITLE
Deploy site via GitHub Pages

### ISSUE THREAD

**Issue by alex-hedley** [scala-js/scala-js#4858]
Do you have an example of a GitHub Workflow for deploying the website statically to [GitHub Pages](https://pages.github.com)?

**Comment by alex-hedley** [comment]
`sbt fullLinkJS`

`cp target/scala-*/*.js ..`

**Comment by gzm0** [comment]
This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Discord](https://discord.com/invite/scala) (channel #scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by alex-hedley** [comment]
Is it worth turning on GitHub Discussions?
Means everything is in one place.

Could this be a feature request to add an example of how to do it to docs?

**Comment by sjrd** [comment]
We're building our knowledge base on StackOverflow for long-form, long-lasting questions, and Discord for direct messaging. Opening GitHub Discussions would *dilute* things to more places.

**Comment by exoego** [comment]
@alex-hedley 
This repo could be an example.
It deploys a small app written with Scala.js using GitHub repo and GitHub Actions.
https://github.com/xuwei-k/scalameta-ast/blob/main/.github/workflows/ci.yml

**Comment by alex-hedley** [comment]
@exoego thanks for the example, I'll give it a try.
