### ISSUE TITLE
Support `TrieMap`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4866]
I'm pretty sure this one is do-able, maybe just a bit annoying because it requires patching scalalib, including replacing Java sources? The naive port would be suboptimal in performance, but at least ease cross-platform pains.

https://github.com/scala/scala/tree/d54204504da401487cffb0ec78623f222194d70f/src/library/scala/collection/concurrent

**Comment by sjrd** [comment]
I don't think maintaining two diverging copies (for 2.12 and 2.13) of the upstream 1000-LoC `TrieMap.scala` is something we want to do. It looks to me like this is something that a small portable library would be better suited for.

**Comment by gzm0** [comment]
I agree with @sjrd here. This is not maintenance burden we can accept.

I've had a quick look a TrieMap: It seems that it's basically about AtomicReferenceFieldUpdater which we cannot implement in SJS since it relies on reflection.

IMHO, if this is important, we should have the support from the Scala core team for this: The relevant parts can likely be shimmed out and we (Scala.js) can provide these.

Having scalalib overrides was a way to allow Scala.js to bootstrap. But I believe the incur significant cost and risk of drift at this point. So I really think we shouldn't add any, unless absolutely necessary.
