### ISSUE TITLE
ScalaJs as a code generator

### ISSUE THREAD

**Issue by kincsescsaba** [scala-js/scala-js#4868]
Hi, I skimmed the most relevant results to what I'd like to implement and did not find anything appropriate (or I should refine my search). Therefore, I assume that what I'd like is something new.

What I'd like to do:
**I'd like to use ScalaJS as a code generator in JVM projects**. I don't want to create 2-3 projects for this (like one for JVM, one for JS, and a shared code lib), but I believe I could solve this with one project.

How this should work:
With some SBT hack (please mind that I'm not an SBT expert), I'd identify those files of which I'd need generated JS. It's not a problem if those files are both compiled by the JVM and ScalaJS, as the generated JS is the thing that would be invoked, for example, in a website.
The SBT hack could be simply setting two properties, like input files and output js files.

It seems like something that would require minor additions to the existing SBT plugin.

Let me know if you're interested and/or if you could assist me in creating such a contribution; if this is not overly complicated, I'd be happy to.

**Comment by sjrd** [comment]
Hello,

This is clearly out of scope for the core. Scala.js compiles Scala code to JavaScript, on a per-project basis. If you want to do some sbt hackery to have it another way, then it's on you to do it in your project or in a separate sbt plugin.

If you would like guidance on *how* to achieve that, then it becomes a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Discord](https://discord.com/invite/scala) (channel `#scala-js`), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by kincsescsaba** [comment]
I filed it as a feature request; I did not treat this as a bug.

Thank you for your guidance, so what I'd like would be something new; it's important to know that I won't reinvent the wheel.

I'll check the codebase so that I can accomplish the wished behavior, though most likely won't be easy, that would save me time as I won't need to write a JS DSL then.
