### ISSUE TITLE
Excess modules are generated

### ISSUE THREAD

**Issue by scf37** [scala-js/scala-js#4977]
**Reproduction steps**
1. sbt fastLinkJS

**Expected**
4 modules: 3 classes annotated with `@JSExportTopLevel(name = ..., moduleID=...)` and common module with runtime

**Actual**
6 modules: 3 named and 3 internal

**Motivation**
- Increased loading time
- harder to post-process since generated module dependency graph differs from source dependency graph

[bug2.tar.gz](https://github.com/scala-js/scala-js/files/14892729/bug2.tar.gz)

**Comment by scf37** [comment]
General expectations: Web application consists of pages where page is a class with `JSExportTopLevel` annotation. When application loads, user should receive two js files - common for everything and single file containing current page implementation.

> For n different exported module IDs, always n + 1 modules?

Yep. Given n module definitions (in this case via `@JSExportTopLevel` with `moduleID`), I expected n+1 modules - n defined modules + single "common stuff". After second thought, it is not optimal for minimizing total javascript size but is great for common web application - deliver single gzipped "common js" and then deliver pages on demand.

In any case, current approach does not look optimal - named modules contain nothing but `require` and export with implementation delegated to internal module. Maybe there is a technical reason for that?

> Increased loading time

Every module dependency is additional RTT to page load time

> what kind of post-processing steps will be made easier if the module dependency graph matches the source dependency graph?

a) hot reloading. When source file changes I hoped it would lead to change of single js module
b) packaging for production: again common.js and single js module per web page.

With current implementation, I will have to parse and transform generated modules which is not cool.

**Comment by sjrd** [comment]
> a) hot reloading. When source file changes I hoped it would lead to change of single js module

This is best served by the `SmallModulesFor` module splitting configuration.

> b) packaging for production: again common.js and single js module per web page.

That can lead to a page downloading more than necessary. If two *other* pages depend on a common subset A that your page does not depend on, insisting on one `common.js` file means that the latter page needs to download and process the subset A, which it does not care about.

It seems you want a new module splitting scenario whose criteria would be:
* If some class C is needed by *at least 2* modules, put it in `common.js`.
* Otherwise, put it in the only module that needs it.

But that won't be optimal in terms of dependency weight. It's also not optimal in terms of dependency chain length, since for that the best solution is to put *all* the required code in every page, and have no common code (that is served by using a separate `project` per module). So it seems what you're asking is some sort of trade-off between dependency weight and dependency chain length. Trade-offs are annoying to specify, though, and there could be zillions of intermediate configurations. I believe configuring a separate JS bundler that feeds from the `FewestModules` configuration of Scala.js would be able to serve any intermediate trade-off.

**Comment by scf37** [comment]
Got it - scala-js for compilation, additional post-processing for bundling and further optimizations.

It is not exactly great since external post-processing does not have access to type information (GCC advanced mode is unbeatable) but is good enough.

**Comment by sjrd** [comment]
GCC advanced mode does not receive type information from Scala.js either. ;)

**Comment by scf37** [comment]
Now that's interesting. I was assuming scala-js output is not suitable for advanced compilation mode or it will produce inferior results but GCC seems to run fine on `ModuleSplitStyle.SmallestModules`. Sooo unavailability of GCC for CommonJS modules in scala-js is just a missing feature?

**Comment by gzm0** [comment]
GCC advanced mode does receive name information from Scala.js:

https://github.com/scala-js/scala-js/blob/95c38be0501fb81c992f3ce8b9e5a9828c2e831e/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureLinkerBackend.scala#L60-L61

https://github.com/scala-js/scala-js/blob/95c38be0501fb81c992f3ce8b9e5a9828c2e831e/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureLinkerBackend.scala#L120-L126

> Sooo unavailability of GCC for CommonJS modules in scala-js is just a missing feature?

If you talk about *multiple* CommonJS modules (it should work for single CommonJS modules), then yes, this might indeed be the case:

https://github.com/scala-js/scala-js/blob/95c38be0501fb81c992f3ce8b9e5a9828c2e831e/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureLinkerBackend.scala#L101-L102

> GCC seems to run fine on ModuleSplitStyle.SmallestModules

With which module style? And invoked how (on individual files, all files)?

**Comment by scf37** [comment]
Looking at the code, optimizeBracketSelects is true by default which is good for me :-)

> With which module style? And invoked how (on individual files, all files)?

CommonJS, all files. with `--process_common_js_modules`, single module output. It produces compact executable js file. I didn't test it but I believe it will work with GCC chunks as well.

**Comment by gzm0** [comment]
> CommonJS, all files. with --process_common_js_modules, single module output. It produces compact executable js file. I didn't test it but I believe it will work with GCC chunks as well.

Ah, OK. But then it also processes all your JS dependencies / node_modules?

If yes, this is not a missing feature in Scala.js, but a deliberate omission: The Scala.js linker deliberately does *not* implement any ES (or CJS) module resolution modes, so it cannot execute GCC with module processing enabled (otherwise GCC would bail out, because imported non-Scala.js code cannot be found).

It is unclear to me, whether it would make sense to offer an output mode suitable for GCC advanced optimization mode. IIUC this would not work with general purpose JS / npm modules (but only with modules specifically written for GCC). In this case, I'm not sure it's worth offering such a mode.

In any case, it feels we're very much digressing from the initial issue here.

I propose we close this as wontfix / as-designed and if you feel you need more control over the specific output the linker generates (e.g. optimize bracket selects or globals for externs), let's discuss it in a follow-up issue?

**Comment by scf37** [comment]
I don't plan to use npm modules. I look at scala-js as a *replacement* of npm ecosystem (including packaging!) while it seems to be aimed to be part of hybrid environment.

Sure, it can be closed as well as https://github.com/scala-js/scala-js/issues/4976

**Comment by gzm0** [comment]
> while it seems to be aimed to be part of hybrid environment.

Yes, absolutely. That is an explicit design goal.
