### ISSUE TITLE
JS Emitter crashes on helloworld with big ints

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#5005]
How to reproduce:

```
$ sbt
sbt:Scala.js> set scalaJSLinkerConfig in helloworld.v2_12 ~= (_.withESFeatures(_.withAllowBigIntsForLongs(true)))
// snip
sbt:Scala.js> helloworld2_12/fastLinkJS
[info] compiling 3 Scala sources to /home/tos/gh/scala-js/linker/jvm/.2.12/target/scala-2.12/classes ...
[info] Fast optimizing /home/tos/gh/scala-js/examples/helloworld/.2.12/target/scala-2.12/helloworld-fastopt
[error] stack trace is suppressed; run last helloworld2_12 / Compile / fastLinkJS for the full output
[error] (helloworld2_12 / Compile / fastLinkJS) java.util.NoSuchElementException: key not found: ClassName<java.lang.ArithmeticException>
[error] Total time: 11 s, completed Jul 6, 2024, 4:08:52 PM
```

**Comment by sjrd** [comment]
Ouch. That happens because the `Infos` builders only register a dependency on `ArithmeticException` if there is a division/modulo somewhere in the program:
https://github.com/scala-js/scala-js/blob/9f5cc98f7f8f1d93a07ca6592aea2e953488b062/linker/shared/src/main/scala/org/scalajs/linker/analyzer/Infos.scala#L653-L674
while the `CoreJSLib` unconditionally emits the `intDiv` and `intMod` helpers (and under bigints-for-longs, also `longDiv` and `longMod`, which need `ArithmeticException`:
https://github.com/scala-js/scala-js/blob/9f5cc98f7f8f1d93a07ca6592aea2e953488b062/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala#L912-L929

The issue does not appear with `RuntimeLong`-for-longs because the emitter then unconditionally declares a dependency on `RuntimeLong./`, which itself depends on `ArithmeticException`, and so the latter is unconditionally required.

The ideal fix would be to only emit the four `{int,long}{Div,Mod}` helpers if `ArithmeticException` is instantiated. We have precedent for that kind of stuff with `GlobalKnowledge.isClassClassInstantiated`.
