### ISSUE TITLE
allow `fastLinkJS` lowercased alias `fastlinkjs`

### ISSUE THREAD

**Issue by spaceunifyfifty** [scala-js/scala-js#5006]
**Low priority recommendation**

`sbt fastLinkJS` works while `sbt fastlinkjs` does not. 

camelCasing is idiomatic for source code, but a bit weird and tiresome for command-line tools. As far as I know, it's not common in the linux world where cli usage is heavy and users want to be able to execute commands effortlessly and fast, to have to worry about uppercasing every subsequent word in a command.  The sbt cli would feel a bit more ergonomic for people of that unix background if lower-cased versions of the command were allowed as well.

**Comment by gzm0** [comment]
Thank you for taking the time to write your suggestions.

Unfortunatley, I have to disagree with this one. I agree that CLI tools would usually use all lower or kebab case, this is not sbt idiomatic: one example is sbt's core command `testQuick`.

I feel for the Scala.js sbt plugin, it is more important to be consistent with sbt than with general CLI feel.

You are of course free to upstream this to sbt (but I suspect that this will likely not get done, even just for compatibility reasons).

I'll close this opportunistically because I'm pretty sure @sjrd will agree. @sjrd in case you don't, please re-open :)
